### ISSUE TITLE
Table list doesn't expand when current table on different page

### ISSUE THREAD

**Issue by svivian** [phpmyadmin/phpmyadmin#11349]
To reproduce:

1. In phpMyAdmin, click a database name on the left panel. (It should have more tables than fit into one page.)
2. Scroll down the table list (in the main panel, not the left one) and click a table that's not on the first page of tables shown at the left.

Expected: To go to the table (browse view) in the main panel, and the table list to be shown at the left with said table highlighted.

Actual: Table list on left collapses instead.

This is a regression, I've reported it before (DisgruntledGoat on sourceforge) and it got fixed once.

PMA 4.4.12 (git STABLE branch), same issue occurs on Apache (localhost) and nginx (live server).

**Comment by lem9** [comment]
@svivian Can you give more precisions about when you reported this, or about a version where this worked?

**Comment by svivian** [comment]
https://sourceforge.net/p/phpmyadmin/bugs/4439/

**Comment by madhuracj** [comment]
The same issue is there at the database level. Looking at the commit that fixed the bug #4439 it is unlikely that this issue was fixed there.

Anyway, while this is a bug, I'm not sure whether there is any clean way of fixing it. Highlighting the current database/table is handled in the front end and we will have to navigate using the pagination to hightlight when the current database/table is not in the current page. This will be problematic when there are a number of pages. So, I am inclined to mark this as won't-fix.

**Comment by lem9** [comment]
@madhuracj I agree with your findings.

**Comment by svivian** [comment]
I wasn't talking about highlighting tables specifically. I was talking about the table list showing at all.

Basically, when you load a table that isn't on the current page of the list of tables, the table list closes up. But this makes no sense... if you're unable to determine the page to show, at least just leave the table list open instead of purposely making things worse by closing it.

**Comment by lem9** [comment]
@svivian This closing behavior is fixed with https://github.com/phpmyadmin/phpmyadmin/commit/fe12f2f9e26574fe47befd13871dcf76cc385a99 for the upcoming 4.4.13 release.
