### ISSUE TITLE
phpseclib < 2.0 produces deprecated messages on PHP 7

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#11387]
We are using phpseclib < 2.0. I contacted one of their developers who told me that we could try https://github.com/phpseclib/phpseclib/tree/2.0 which does use __construct(). However, due to it being namespace'd, the API is slightly different.

Target for this should be QA_4_4 because we have to be ready for PHP 7.

**Comment by AlbertoDiazC** [comment]
Upgraded to 4.14, blank page displayed:
PHP Fatal error:  Class 'phpseclib\\Crypt\\AES' not found in /usr/share/phpMyAdmin/libraries/plugins/auth/AuthenticationCookie.class.php on line 824
Reverting that file from 4.13 brings back login screen.

**Comment by lem9** [comment]
@AlbertoDiazC In libraries/vendor_config.php, do you have this line?
````
define('PHPSECLIB_INC_DIR', './libraries/phpseclib/');
````
Probably not, and your vendor config refers to a CentOS-specific older phpseclib library.

**Comment by AlbertoDiazC** [comment]
directory is /usr/share/pear/ , as this is a rpm-packaged phpMyAdmin:

define('PHPSECLIB_INC_DIR', '/usr/share/pear/');
It's exactly the same in 4.4.13 and it works.

**Comment by lem9** [comment]
Well, phpMyAdmin 4.4.14 requires a phpseclib more up to date, to remove deprecated messages under PHP 7. Please try with the line I suggested.

**Comment by AlbertoDiazC** [comment]
PHP Fatal error:  require(): Failed opening required './libraries/phpseclib//Crypt/AES.php' (include_path='.:/usr/share/pear:/usr/share/php') in /usr/share/phpMyAdmin/libraries/plugins/auth/AuthenticationCookie.class.php

It seems that that files have been removed from the phpMyAdmin rpm , in order to use system phpseclib.

BTW; these are their version numbers:
php-channel-phpseclib-1.3-1
php-phpseclib-crypt-aes-0.3.9-1
php-phpseclib-crypt-base-0.3.9-1
php-phpseclib-crypt-blowfish-0.3.9-2
php-phpseclib-crypt-des-0.3.9-2
php-phpseclib-crypt-hash-0.3.9-1
php-phpseclib-crypt-random-0.3.9-1
php-phpseclib-crypt-rc4-0.3.9-2
php-phpseclib-crypt-rijndael-0.3.9-2
php-phpseclib-crypt-tripledes-0.3.9-2
php-phpseclib-crypt-twofish-0.3.9-2
php-phpseclib-math-biginteger-0.3.9-1
php-phpseclib-net-sftp-0.3.9-1
php-phpseclib-net-ssh2-0.3.9-1

**Comment by lem9** [comment]
So please tell this to those who have removed these files from their phpMyAdmin rpm.
