### ISSUE TITLE
Paste command is gone in 4.4

### ISSUE THREAD

**Issue by lwavery769** [phpmyadmin/phpmyadmin#11453]
I upgraded to phpmyadmin 4.4.14, and am now unable to right click to a paste command in the Run SQL window. The menu that I do get is the common browser right-click menu, (back, reload, save as...). How else can I verify my PHP SQL statements?

**Comment by madhuracj** [comment]
CodeMirror editor which is used to provide additional functionality does not support this. However, it still support pasting with Ctrl + v.
You can still enable the old style editor by Settings -> SQL queries -> Uncheck 'Enable CodeMirror'

**Comment by lwavery769** [comment]
Awesome. Thanks

**Comment by davelogear** [comment]
CodeMirror supports right-click copy/paste by default: http://codemirror.net/

![image](https://user-images.githubusercontent.com/32692076/40859820-4abf0ace-65a0-11e8-9df5-fc855b364f3b.png)

The problem is phpMyAdmin. Either it's using an outdated or overly-customized version.

Apparently the issue was fixed in 2015: https://github.com/codemirror/CodeMirror/issues/3238#issuecomment-158404424

phpMyAdmin should have right-click copy/paste enabled by default, not require disabling CodeMirror.
