### ISSUE TITLE
Impossible to cancel "Drop files here" overlay

### ISSUE THREAD

**Issue by GuillaumeRossolini** [phpmyadmin/phpmyadmin#11470]
I had a tab open on a phpMyAdmin page (which might be a tables list or a query results) with Firefox.
Then I switched to a Windows Explorer window and started dragging a file to another program on another screen. While doing that, the file being dragged happened to pass over the phpMyAdmin window in Firefox, and a message "Drop files here" appeared in that window.
At that point, it became impossible to resume control of the phpMyAdmin Firefox window: the Esc key wouldn't work and nothing in the UI allowed me to cancel the overlay. I could either close the tab or reload the whole page.

Reproduce: always

Simplest reproduce case:
Open the PMA homepage (installed webapp, not the project homepage) with Firefox and start dragging a file from Windows Explorer passing over the PMA window. An overlay then blocks the whole PMA page with a "Select database first" message.

Versions:
Windows 7 x64
phpMyAdmin 4.4.14.1
Firefox Developer Edition 42.0a2

This issue doesn't affect Chrome 47.0.2505.0 canary (64-bit)

**Comment by madhuracj** [comment]
Unable to reproduce on Windows 10 x64, phpMyAdmin 4.4.14.1, Firefox 40.0.3

**Comment by ibennetch** [comment]
I'm also unable to reproduce, though I'm on a Mac so perhaps my test is a bit less relevant. If I hold in the mouse button while dragging, I'm able to press escape to cancel the dialog while still holding the mouse button.

**Comment by Kirkis** [comment]
I could also reproduce while dragging a file from the Firefox download manager (Ctrl+J).
When the file passes over PMA, the overlay appears; when the file is dragged away from the PMA window, the overlay disappears and then reappears right away, and I have been unable to make use of that window afterwards.

**Comment by lem9** [comment]
@Kirkis How about the current version? (phpMyAdmin 4.5.0.2) ?

**Comment by Kirkis** [comment]
@lem9 yes, the issue is still present with PMA v4.5.1

**Comment by nijel** [comment]
@Kirkis can you reproduce this with stable version of Firefox? I've just tried it in Firefox 42.0 and I can not reproduce the issue either...

**Comment by Kirkis** [comment]
Thanks for the pointer @nijel - the issue is not present on Firefox stable v42.0. Confirmed again on Firefox Developer Edition v44.0a2, though.

**Comment by Kirkis** [comment]
Just improving on my previous comment: I know this is a low-prio request / bugreport.
That being said, please keep in mind that at some point, Developer and/or beta version features will be made part of the stable branch.
Unless someone points out any bug.

**Comment by nijel** [comment]
It would be great if somebody could track this down to feature/bug in Firefox causing this...

**Comment by Kirkis** [comment]
I can surmise it might have to do with their multiprocess / x64 support, which I believe they call e10s.
I just did a quick test: unchecked "Options > General > Startup > Enable multi-process Nightly", restarted the browser, then everyhting worked fine in PMA.
I then re enabled e10s and tried again in PMA: problem confirmed again.
I reported the issue to Mozilla and referenced them to this issue here.

**Comment by nijel** [comment]
Hmm, this really looks more like a Firefox bug than something on our side, but let's see. Can you please link the Mozilla issue here as well?

**Comment by Kirkis** [comment]
I'd love to, but providing feedback this way does not give an issue ID.

**Comment by nijel** [comment]
Has anything changed here?

**Comment by Kirkis** [comment]
The problem is only with Firefox's Developer Edition. The Firefox v44 release has the same multiprocess functionality as the Developer Edition, but it doesn't reproduce this PMA bug.
I can't upgrade PMA because of the issue with the SQL parser (#11604) so I'm working around it in the meantime.
The issue might be with Firefox more than PMA anyway.

**Comment by nijel** [comment]
Okay let's close this one until it's in some stable release of Firefox (or we know what is causing this).

**Comment by albino1** [comment]
I just stumbled across this Issue page while searching for a solution to this problem.

FWIW, I'm using Firefox 44.0.2 and PMA 4.5.5.  Sometimes it goes away, but other times (like right this moment) I can't seem to get out of it, which is annoying because I have a bunch of newly entered information that hasn't been saved yet.

I'm not a dev, so I'm not sure I can help in any manner other than to let you know that at least in 4.5.5 it still happens sometimes using Firefox.  HTH.

**Comment by albino1** [comment]
Just an update: I was able finally to get back to my work area by dragging a random file and letting it upload.  The screen then went away, and I was able to save my work and then just go delete the uploaded file.

**Comment by Kirkis** [comment]
@albino1 thanks for the tip!

**Comment by StreelRodent** [comment]
Happens to me with PMA 4.6.3 in Firefox 48 whenever I copy/paste files in Windows explorer and have the PMA tab active in Firefox. The files don't even have to be moved over the Firefox window for it to happen. Only workaround is to reload the PMA tab. 

What I don't understand is why the "drag/drop" script is even active outside the import tab - or why it comes on by itself. That's just begging for disaster to happen.

**Comment by scottbomb** [comment]
Any progress on this? Is it a FF bug? It's a real pain in the neck and probably shouldn't even be a feature.

**Comment by hotelexpress** [comment]
Same issue here. When dragging files, the layer "Drop files here" show on the screen. There is no way of getting it away forcing you to close and loose all query etc in the windows. Running version 4.7.5 of PHPmyadmin and Firefox 57.0.4 (64-bit). 

This issue could be resolved by making it possible to click to get the layer to disappear or have a cross on upper right corner or similar so that we can close it down and keep working. 

![image](https://user-images.githubusercontent.com/12250076/34721283-75a40b64-f542-11e7-89ad-1b7e331799cb.png)

**Comment by shucon** [comment]
I am not able to reproduce the issue on master branch . Using Firefox 57.0.4 (64-bit) on Ubuntu.

**Comment by GuillaumeRossolini** [comment]
I am now unable to reproduce with:
Firefox Developer Edition v63.0b3 (64 bits)
Windows 10 v17134.228
phpMyAdmin v4.7.8

It may have been fixed for a while.
