### ISSUE TITLE
Packagist version

### ISSUE THREAD

**Issue by carduz** [phpmyadmin/phpmyadmin#11508]
There is no version that respects the packagist version guidelines, so if I try to use phpmyadmin as composer dependency (require) I get a composer error (there are no `dev-STABLE` versions).

Library that uses phpmyadmin as dependency: https://github.com/thecsea/twofactor-phpmyadmin

**Comment by madhuracj** [comment]
My knowledge on Composer is limited. Shouldn't the STABLE branch (https://github.com/phpmyadmin/phpmyadmin/commits/STABLE) satisfy dev-STABLE dependency?

**Comment by carduz** [comment]
I think that composer considers as stable only versions that follow this structure: vx.x.x (for example v1.2.3)

**Comment by Tithugues** [comment]
The rules to consider branches as stable are here: https://packagist.org/about
So it seems that "dev-stable" can't be considered as stable. Can you please try the following in your require?

    "phpmyadmin/phpmyadmin": "dev-STABLE@dev"

**Comment by carduz** [comment]
I've tried but it doesn't work

https://github.com/thecsea/twofactor-phpmyadmin/blob/master/composer.json

**Comment by nijel** [comment]
I've also tried to create composer repository with all releases, however I have no clue how to properly integrate it. The repository lives at https://www.phpmyadmin.net/packages.json

See also #6261

**Comment by udan11** [comment]
I did some research on Composer. So far, from what I understand, if we want to use [Packagist.org](https://packagist.org) as repository (recommended, since it is the default one in Composer) we have to rename the current tags or create aliases. I think that renaming the tags would be the way to go, because the other way implies updating `composer.json` for each new version and it will be a mess. I am not sure if it would break anything (bots, scripts used for release, etc.). I created a script that renames the tags which can be found [here](https://gist.github.com/udan11/df384c10d6f5265971aa).

The other way, is to create our own repository. The repository already exists at https://www.phpmyadmin.net/packages.json. Anyway, to use this repository you have to manually specify it, in the `composer.json` file or as a parameter in terminal. 

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://www.phpmyadmin.net/packages.json"
        }
    ],
    "require": {
        "phpmyadmin/phpmyadmin": "4.*"
    }
}
```

```bash
composer create-project phpmyadmin/phpmyadmin --repository-url=https://www.phpmyadmin.net/packages.json
```

The repository also has to be updated everytime a new version is released.

At this moment, `composer create-project phpmyadmin/phpmyadmin -s dev` might also work, but it should install the `master` branch. I believe that you can also replace `dev` with `dev-NAME_OF_THE_BRANCH`.

To make it easier for our users, I propose renaming the tags. Maybe this can be one of the topic for the next meeting?

**Comment by lem9** [comment]
Thanks, added to the agenda: https://wiki.phpmyadmin.net/pma/2015-10_Meeting

**Comment by nijel** [comment]
Only changing tag names won't solve the problem - we do quite a lot of things on release time (compile .mo files, generate documentation,...) and these files would be missing (see #6261).

**Comment by unreal4u** [comment]
I finally gave up and started using https://github.com/wp-cloud/phpmyadmin as it uses proper semver.

What about making 2 tags on each release? One the old way, another one which uses semver?

Greetings.

**Comment by nijel** [comment]
Just to summarize the status here we have following options:

1. Keep current release process and tagging and promote own composer repository - harder to setup by users, but we can use generated tarballs instead of git snapshots in own repository. All this needs is a documentation.
2. Keep current release process and change tagging - this will allow to install tagged versions by composer, but they will lack some files like locales or documentation. We would need to change tags and release script.
3. Include generated files in git and change tagging - this will make composer installation complete, but the git repository will contain lot of generated content.

**Comment by carduz** [comment]
What do you think to download these files with a post installation composer
script?

**Comment by nijel** [comment]
I don't think there is way to execute script on installing something, it works only in your project (see https://github.com/composer/composer/issues/1193).

**Comment by udan11** [comment]
After the last meeting, I created this issue composer/packagist#594 hoping that they would let us import the phpMyAdmin repository into theirs, to ease the installation, but there is not much support.

**Comment by nijel** [comment]
I've added documentation how to install using our own repository as that seems to be currently only way to do it.
