### ISSUE TITLE
PHP Fatal error:  Class 'SqlParser\\Lexer' not found

### ISSUE THREAD

**Issue by y2kbadbug** [phpmyadmin/phpmyadmin#11528]
On master, with a configuration using cookie auth and multiple servers in 1 installation, we are receiving a PHP error of:

 PHP Fatal error:  Class 'SqlParser\\Lexer' not found in /libraries/Util.class.php on line 634

This only occurs on some of our servers, not all of them, when logging in.

**Comment by lem9** [comment]
Thanks. What is the last commit in the master branch you are testing?

**Comment by madhuracj** [comment]
Can you also paste the stack trace here.

**Comment by lem9** [comment]
@y2kbadbug Any feedback?

**Comment by y2kbadbug** [comment]
Sorry for the non-reply.  Been busy this week.  This error has gone away since the last pull I made.

**Comment by nazar-pc** [comment]
I'm having this problem with MariaDB 10.0.22 running as first and single node in Galera cluster (Debian Jessie, node upgraded from regular MariaDB server instance to MariaDB Galera server) with PhpMyAdmin 4.5.1.

How to reproduce:
1) Have MariaDB 10.0.22 running on Debian Jessie
2) Have PhpMyAdmin 4.5.1
3) Stop MariaDB
4) Install `mariadb-galera-server` package
5) Add/modify `/etc/mysql/my.cnf` to contain this:
```
[mysqld]
wsrep_provider=/usr/lib/galera/libgalera_smm.so
binlog_format=ROW
bind-address=0.0.0.0
default_storage_engine=InnoDB
innodb_autoinc_lock_mode=2
innodb_doublewrite=1
innodb_flush_log_at_trx_commit=0
wsrep_on=ON
```
6) `service mysql start  --wsrep_on=OFF`
7) `service mysql stop`
8) `service mysql start --wsrep-new-cluster`

Now you should experience corresponding error (at least this is how I got it, my actual commands were a bit different because I'm building Docker image for MariaDB Galera server cluster and found this error when attaching my PhpMyAdmin container to it).

**Comment by nazar-pc** [comment]
Stacktrace:
```
Array
(
    [0] => Array
        (
            [file] => /var/www/html/libraries/DatabaseInterface.class.php
            [line] => 95
            [function] => mysqlDie
            [class] => PMA_Util
            [type] => ::
            [args] => Array
                (
                    [0] => #1047 - WSREP has not yet prepared node for application use
                    [1] => SELECT * FROM information_schema.CHARACTER_SETS
                )

        )

    [1] => Array
        (
            [file] => /var/www/html/libraries/mysql_charsets.inc.php
            [line] => 23
            [function] => query
            [class] => PMA_DatabaseInterface
            [object] => PMA_DatabaseInterface Object
                (
                    [_extension:PMA_DatabaseInterface:private] => PMA_DBI_Mysqli Object
                        (
                        )

                    [_table_cache:PMA_DatabaseInterface:private] => Array
                        (
                        )

                )

            [type] => ->
            [args] => Array
                (
                    [0] => SELECT * FROM information_schema.CHARACTER_SETS
                )

        )

    [2] => Array
        (
            [file] => /var/www/html/libraries/common.inc.php
            [line] => 1063
            [args] => Array
                (
                    [0] => /var/www/html/libraries/mysql_charsets.inc.php
                )

            [function] => include_once
        )

    [3] => Array
        (
            [file] => /var/www/html/index.php
            [line] => 12
            [args] => Array
                (
                    [0] => /var/www/html/libraries/common.inc.php
                )

            [function] => require_once
        )

)
```

**Comment by nazar-pc** [comment]
Yes, because `include_once SQL_PARSER_AUTOLOAD;` is executed only on line 1037: https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/common.inc.php#L1037
While `mysql_charsets.inc.php` is included on line 1027 (10 lines before autoloader inclusion, upstream lines are refactored a bit since 4.5.1).
So you need to move autoloader higher (or, better, make correct autoloader and use it everywhere as early as possible).

**Comment by c786836332** [comment]
我也是遇到这样的问题 不知道怎么解决

**Comment by LuisKrotz** [comment]
I'm having the same problem on Linux Mint, since I updated to the last PHP and MYSQL

```
[Tue Jun 05 11:20:13.414530 2018] [:error] [pid 14228] [client 127.0.0.1:40172] PHP Fatal error:  Uncaught Error: Class 'SqlParser\\Lexer' not found in /usr/share/phpmyadmin/libraries/Util.class.php:634\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/DatabaseInterface.class.php(95): PMA_Util::mysqlDie('#1449 - The use...', 'SELECT * FROM i...')\n#1 /usr/share/phpmyadmin/libraries/mysql_charsets.inc.php(23): PMA_DatabaseInterface->query('SELECT * FROM i...')\n#2 /usr/share/phpmyadmin/libraries/common.inc.php(1070): include_once('/usr/share/phpm...')\n#3 /usr/share/phpmyadmin/index.php(12): require_once('/usr/share/phpm...')\n#4 {main}\n  thrown in /usr/share/phpmyadmin/libraries/Util.class.php on line 634, referer: http://phpmyadmin.local/index.php?token=c12ecd1280b65b13964f9cd7d8aa5e17
```

**Comment by williamdes** [comment]
@LuisKrotz did you upgrade to the last version of phpMyAdmin ?
what version are you using ?

**Comment by joatorreshi** [comment]
I am having the same problem as @LuisKrotz and so it happens when I activate the ssl connection for my remote database. Version 4.5.4.1deb2ubuntu2.

**Comment by pklapperich** [comment]
@pleizi I'm also using ubuntu (version 4.5.4.1-2ubuntu2.1) and was experiencing this issue. I downloaded phpMyAdmin-4.8.5 and manually installed it (with a symlink to /etc/phpmyadmin/config.inc.php) and things are working fine. I will keep this setup until Ubuntu updates their package.
