### ISSUE TITLE
Copy multiple tables to database

### ISSUE THREAD

**Issue by mvl22** [phpmyadmin/phpmyadmin#11538]
As of PhpMyAdmin 4.5.0(.2), the option to copy multiple tables to another database seems to have disappeared:

![copy table gone](https://cloud.githubusercontent.com/assets/361423/10279329/be92dd2c-6b5c-11e5-8eb7-65b86721fdcb.png)

**Comment by lem9** [comment]
In which version did you see this option?

**Comment by mvl22** [comment]
Mea culpa - I could have sworn this was there, but it's not!

Perhaps treat this as a feature request? :)

**Comment by madhuracj** [comment]
Had a look at this with the intention of using `Table::moveCopy` function to copy selected tables to another database. However, this seems to need quite some changes to the `mult_submits.lib.php` as all the multi submit functionality provided there are oriented towards changes done by executing SQL queries rather than calling functions.

**Comment by Achilles-96** [comment]
So, is the implementation supposed be like this - 

* One more option under 'Table maintenance' called 'Copy table'.
* When that option is clicked target database is asked.
* On submit tables are copied.

**Comment by devenbansod** [comment]
Seems correct, @Achilles-96. Just a few things.

One thing I would suggest is not to include it under 'Table Maintenance', but rather as a separate option because 'Table maintenance' on tbl_operations.php also has the same options like : Analyze table, Check table, Checksum table, Optimize table etc. while copy is a different option.

Another is, after selecting 'copy' from the drop-down, should we provide some subset of the options (which might be generic to all selected tables) from the 'Copy table' form on tbl_operations.php and then proceeding to actual copying may be ?

**Comment by Achilles-96** [comment]
@devenbansod Yes, we can show those options when we ask for target database.
