### ISSUE TITLE
Notices when setting NavigationTreeDbSeparator to an array

### ISSUE THREAD

**Issue by tiennou** [phpmyadmin/phpmyadmin#11647]
With `NavigationTreeDbSeparator` set to`array('-', '_')`, the following notices are reported :

- Notice in ./libraries/navigation/NavigationTree.php#177
- Notice in ./libraries/navigation/nodes/Node.php#441
- Notice in ./libraries/navigation/nodes/Node.php#451
- Notice in ./libraries/navigation/nodes/Node.php#453
- Notice in ./libraries/navigation/nodes/Node.php#607

**Comment by devenbansod** [comment]
Hi @tiennou , which phpMyAdmin version are you getting these notices ?

Also could you please the text of notices, it will make it more clear for our developers to fix it.

**Comment by tiennou** [comment]
Restest against both `master` and `RELEASE_4_5_1`, from a pristine config file with just "
$cfg['NavigationTreeDbSeparator'] = array('-', '_');" added at the end, here are the notices :

`master` (looks completely unusable, but the notices are still present) : https://gist.github.com/tiennou/85f6050c94b5f65599d8

`RELEASE_4_5_1` : https://gist.github.com/tiennou/24781081370a7b3754b3

**Comment by devenbansod** [comment]
I could reproduce this on both master and QA_4_5.

**Comment by madhuracj** [comment]
Fixing this is problematic since `$cfg['NavigationTreeDbSeparator']` is used with `SUBSTRING_INDEX` in SQL query. Loading all the table names and trying to do the grouping in PHP level would be disastrous for servers with a very large number of databases.

However, `$cfg['NavigationTreeTableSeparator']` works as expected
