### ISSUE TITLE
Export/import of escaped single quote

### ISSUE THREAD

**Issue by jeremyVignelles** [phpmyadmin/phpmyadmin#11721]
Hi,
I have in my database a text field that contains an escaped single quote like this `\'`.
I made a dump of the prod database with phpmyadmin and imported it on my local database, but mysql answered that there was a syntax error at the next statement.

I reproduced te same behavior on my computer with the following script:
```
CREATE TABLE `test_escape` (
  `value` varchar(20) NOT NULL
) ENGINE=InnoDB;

INSERT INTO `test_escape` VALUES ('\\\'');
```

Observations:
+ PMA executes this SQL sucessfully.
+ PMA exports the value as ```INSERT INTO `test_escape` (`value`) VALUES ('\\''');``` and can't reimport it
+ mysqldump exports it as ```INSERT INTO `test_escape` VALUES ('\\\'');``` and PMA is able to import it

Versions : 
+ PMA 4.5.2
+ mysql 5.7.9

**Comment by nijel** [comment]
Reproduced with current master as well.

**Comment by nijel** [comment]
Fixed in git. Just to clarify yhis error happens only if MySQL server is in the [ANSI_QUOTES](http://dev.mysql.com/doc/refman/5.7/en/string-literals.html) mode, what is not the default setup.

It seems nobody is really using this mode as the bug is there for more than 10 years since  36f2eb3055c7e08fbae231387a8baa359de6d141 (committed for #7383, but the fix is wrong in this part).
