### ISSUE TITLE
While 'changing a column', query fails with a syntax error after the 'CHARSET=' keyword

### ISSUE THREAD

**Issue by netmou** [phpmyadmin/phpmyadmin#11777]
![20151226082703](https://cloud.githubusercontent.com/assets/7068058/12004699/8d827af6-abaa-11e5-9176-f18963a16af9.jpg)
more info like this after refresh the page:
![20151226082902](https://cloud.githubusercontent.com/assets/7068058/12004701/c3909c22-abaa-11e5-9b3a-f5fb31ed6257.jpg)

**Comment by netmou** [comment]
multi-byte-char:  CJK

**Comment by devenbansod** [comment]
This is not exactly an issue with using multi-byte-char in comments, but rather is a syntax error introduced by mistake in fixing #11757 (in PR #11762) by me.

The problem is that the syntax of `CHARSET=` works fine when used at the end in `CREATE DATABASE ...` and `CREATE TABLE` statement (with `=` being an optional but showed in SHOW CREATE` output), but is a syntax error while used in `ALTER TABLE`'s column_definition's  syntax` .

I will fix this soon.

**Comment by devenbansod** [comment]
What is the PMA version you are using ?

**Comment by netmou** [comment]
yes v4.53

**Comment by devenbansod** [comment]
@netmou : does a normal utf-8 comment work fine ? 

If it does, could you test out if this patch works fine for you : https://github.com/devenbansod/phpmyadmin/commit/075675acd7c9ee00be9f4385a49ebf0315007bb5.patch

**Comment by netmou** [comment]
clone the repo and apply the pack?
![20151226152903](https://cloud.githubusercontent.com/assets/7068058/12005544/79a65e4a-abe5-11e5-9363-6b0dc0cacd25.jpg)
maybe something wrong for me?

**Comment by devenbansod** [comment]
Sorry, but the patch is actually aimed at the branch QA_4_5 so that the fix gets included in 4.5.4 for sure (may be earlier in 4.5.3.2 if the team thinks so). 
Could you please clone the QA_4_5 branch and try to re-apply it?

**Comment by netmou** [comment]
![aaa](https://cloud.githubusercontent.com/assets/7068058/12005760/0cb2f418-abf1-11e5-8931-55016326dfc2.jpg)
it's ok after apply the pack

**Comment by netmou** [comment]
![5530](https://cloud.githubusercontent.com/assets/7068058/12005776/84cdbadc-abf1-11e5-92b0-72edfc0c9253.jpg)

**Comment by devenbansod** [comment]
Thanks for the testing and feedback!
