### ISSUE TITLE
Table engine detection fails with dot in database name

### ISSUE THREAD

**Issue by bjdelange** [phpmyadmin/phpmyadmin#11798]
When there's a dot in de name of the database, the explode in util.lib.php#27 provides an incorrect array, causing the table cache lookup to fail.
I noticed it because, when using InnoDB tables, it made the engine detection fail (returning "" instead of "InnoDB") which causes the Relation View to not display the foreign keys form.

**Comment by lem9** [comment]
Note: unfortunately, MySQL (from version 5.1.6) allows a dot in database name (if the name is escaped by backticks), see http://stackoverflow.com/questions/776123/does-mysql-allows-to-create-database-with-dot. So it seems we should fix this.

**Comment by Achilles-96** [comment]
Alright, the main problem here is joining database name and table name with dot as in https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/Table.php#L329 but dot is accepted character in database name and table names by MySQL. Small modification may fix this particular bug but definitely there will be a problem in future.
In order to avoid future bugs due to this convention, we have to change all those instances where db name and table name are joined with dot and corresponding explode statements as well. The solution is that we should change separator to some character which is invalid for naming MySQL tables, but MySQL allows all characters in names.
Any suggestions are welcome.

**Comment by nijel** [comment]
Wouldn't be best to simply pass array in these cases? We already know all the individual items and the concatenation and parsing just makes the code slower...
