### ISSUE TITLE
SQL Syntax error while editing single column

### ISSUE THREAD

**Issue by peku33** [phpmyadmin/phpmyadmin#11809]
phpMyAdmin: 4.5.3.1
MySQL: 5.6.28

If I try to make an edit to column in table I'm getting following error:

    #1064 - Something is wrong in your syntax near '=utf8 COLLATE utf8_bin NOT NULL' in line 1

Full SQL looks LIKE:

    ALTER TABLE (...) CHARSET=utf8 COLLATE utf8_bin NOT NULL;

I have to choose 'empty' for this column collation or manually remove `CHARSET` part from SQL to make it work.

**Comment by devenbansod** [comment]
Hi @peku33 , this was first introduced while fixing #11777 but has been marked fixed in 4.5.4 .(https://github.com/phpmyadmin/phpmyadmin/commit/28a5a2693bb6bd079c1feddd3d0c4b5753156d44)

Could you confirm if this patch (https://github.com/phpmyadmin/phpmyadmin/commit/28a5a2693bb6bd079c1feddd3d0c4b5753156d44.patch) works for you ?
