### ISSUE TITLE
Row count displayed by PMA does not match real result

### ISSUE THREAD

**Issue by luis-kc** [phpmyadmin/phpmyadmin#11905]
We are getting discrepancies between the row count shown by PMA after executing a query and the real row count.

We don't know if this is a php driver issue a mysql issue or a PMA issue so we are reporting it. We are running the following:

Server version: 10.0.23-MariaDB-1~wily-log - mariadb.org binary distribution
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503
PHP extension: mysqli
PHP version: 5.6.11-1ubuntu3.1
phpMyAdmin Version information: 4.5.4.1 (up to date)

![pma discrepancy](https://cloud.githubusercontent.com/assets/6793575/12695975/e319a0a6-c75d-11e5-84e8-bff0cf5cf1b4.png)

**Comment by 007durgesh219** [comment]
This is because PMA don't calculate exact records on a large table to speed up. When the size of table is large then only this error occurs. I think there should be an option to count exact number of records because sometime this will introduce other errors like this one:

![screen1](https://cloud.githubusercontent.com/assets/7701929/12910883/49d54510-cf34-11e5-8287-71a09d5a5a97.png)
![screen2](https://cloud.githubusercontent.com/assets/7701929/12910884/49e5c0f2-cf34-11e5-959d-b23a6d5e2a1c.png)

When I tried to browse last page of the table it shows nothing because of wrong count.

**Comment by nijel** [comment]
This is already configurable using [$cfg['MaxExactCount']](http://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount).
