### ISSUE TITLE
Cookie auth keep asking for the password

### ISSUE THREAD

**Issue by 007durgesh219** [phpmyadmin/phpmyadmin#11916]
PMA with Cookie auth is asking for the password everytime I click on any tab. This problem is in the current master branch. I tried demo server with cookie auth same problem their also.

**Comment by ibennetch** [comment]
I had this occur within the past day or two. At the time, I had been changing the language and theme quite often. Clearing my phpMyAdmin cookies (which start with "pma") fixed the problem. I've been working off of a few day old version of master due to #11914 and I'm unable to reproduce it from the older version (at the moment I'm on commit e98f63110cec9a700095cf92b34b05cd51abfaf6).

So I'm not sure what that means for you. I suggest starting with clearing your cookies and seeing if that helps.

**Comment by 007durgesh219** [comment]
I tried removing all cookies starting with "pma" but this problem still exists

**Comment by poush** [comment]
Same issue here too. Cleared all cookies still PMA is asking for user and password on each request

**Comment by nijel** [comment]
Probably caused by my changes to remove PmaAbsoluteUri. Will look into that.
