### ISSUE TITLE
4.0.10.12 Fatal error: Cannot 'break' 2 levels in ../phpmyadmin/export.php on line 864

### ISSUE THREAD

**Issue by osben** [phpmyadmin/phpmyadmin#11912]
Когда нажимаю експорт 
Fatal error: Cannot 'break' 2 levels in ../phpmyadmin/export.php on line 864

`            )) {
                break 2;
            }
`
Apache/2.4.17 (Win32)
MySQL 5.6.26
PHP 7.0.0, mysqli 
phpMyAdmin 4.0.10.12

**Comment by devenbansod** [comment]
Actually this version is no longer supported, except for security fixes. 
Please try a newer version.

**Comment by bbalet** [comment]
You can solve this issue my modifying line 864, change :

    break 2;

By:

    break;

Don't worry, this is a code mistake from the phpMyAdmin team: you are into one loop and not two nested loops. That's why you can't "break 2" (because 2 denotes that you're inside a nested loop). The error appears because PHP7 is stricter than former versions. By the way, this can fix other packages (PHPExcel, newer versions of phpMyAdmin etc.). Most of the time, the developper deleted the nested loop and forgot to update this line of code.

**Comment by angelfreedomv** [comment]
thank you to solve problem in phpstudy.

**Comment by angelfreedomv** [comment]
phpstudy is a PHP development tool of Windows.

**Comment by DOCTOR-5** [comment]
@BBakket : THANK YOU!!

**Comment by steadistone** [comment]
Thank you bbalet. Appreciate you documenting this. 

Found the export.php file on Ubuntu 14.04 LTS at:

/usr/share/phpmyadmin

and it was indeed located at line number 864,

Got the rest of my day back. Thanks!

-Andrew Stone

**Comment by rsedger** [comment]
Thank you bbalet. I have a fresh install of mysql (Ver 14.14 Distrib 5.5.58) and php7.1 with phpmyadmin version 4.0.10deb1. This issue still exists.

**Comment by akuladouglas** [comment]
Thanks you. Worked for me as well

**Comment by invomDing** [comment]
thank you @bbalet
