### ISSUE TITLE
Uncaught ReferenceError: isStorageSupported is not defined

### ISSUE THREAD

**Issue by joseluisq** [phpmyadmin/phpmyadmin#11959]
OS: `Fedora 23 x64`
URL: `phpmyadmin/setup/index.php`
Browser: `Chrome v48.0.2564.109 (64-bit)` 
phpMyAdmin: `v4.5.4.1`

![Uncaught ReferenceError: isStorageSupported is not defined](https://cloud.githubusercontent.com/assets/1700322/13031216/54c174fa-d293-11e5-84f4-949f63f25e51.png)

**Comment by poush** [comment]
This error is most likely due to failure of loading of ```functions.js```. 
Can you do one thing 
1. Go To Inspect Element
2. Click on Sources tab
3. Open JS field from left
and click on file as shown in image and do a search of ```isStorageSupported``` function (as shown i image) 
<img width="1105" alt="screen shot 2016-02-14 at 11 39 17 am" src="https://cloud.githubusercontent.com/assets/1812082/13032207/ef28451a-d30f-11e5-9ede-2990ff82c1a9.png">

**Comment by 007durgesh219** [comment]
It's because functions.js is not included in setup/index.php. I tried including it but again it depends upon lots of other scripts.  I think best solution would be to define isStorageSupported separately for setup/index.php

**Comment by nijel** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |Uncaught ReferenceError: isStorageSupported is not defined
 Exception Type |js
 Link | [Report#8989](https://reports.phpmyadmin.net/reports/view/8989)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](http://reports.phpmyadmin.net).*
