### ISSUE TITLE
DECLARE not accepted as valid SQL

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11979]
It appears as if DECLARE is not recognized as valid SQL. Related: #11776 and #11191

This is valid at the MySQL command line:
```
DELIMITER |
CREATE PROCEDURE SPTEST()
BEGIN
  DECLARE V INT UNSIGNED DEFAULT 1;
END
|
```

But trying 
`DECLARE V INT UNSIGNED DEFAULT 1;`
in the Routines window gives an immediate red x syntax error and this message on submission:
One or more errors have occurred while processing your request:

> The following query has failed: "CREATE PROCEDURE `ads`() NOT DETERMINISTIC NO SQL SQL SECURITY DEFINER DECLARE V INT UNSIGNED DEFAULT 1; "
>
> MySQL said: #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DECLARE V INT UNSIGNED DEFAULT 1' at line 1

Tested with QA_4_5 and master.

**Comment by madhuracj** [comment]
Following are a couple of observations related to this.

1. If you type the whole SQL in SQL tab, Linter does not complain. SQL parser seems to correctly parse the full SQL.
2. In Routine edit window, if you type
```
BEGIN
  DECLARE V INT UNSIGNED DEFAULT 1;
END
```
There will be no MySQL error even though the Linter complains.

So, the issue here seems to be Linter's inability to parse partial SQL from BEGIN to END.

**Comment by ibennetch** [comment]
Thanks Madhura. I also got the Linter syntax warning when just entering

    DECLARE v INT; 

without any `BEGIN` or `END`.
