### ISSUE TITLE
Exporting with ARCHIVE engine - index problem

### ISSUE THREAD

**Issue by Volvoxpl** [phpmyadmin/phpmyadmin#12082]
### Steps to reproduce
1. Create table with ARCHIVE engine and INDEX:

    CREATE TABLE \`archive\` ( \`id\` INT NOT NULL AUTO_INCREMENT , \`name\` VARCHAR(50) NOT NULL , PRIMARY KEY (\`id\`)) ENGINE = ARCHIVE;

2. Export table to file (ordinary SQL file)
3. Try to import table from file

### Expected behaviour
I should get this same table as it was before exporting (with INDEX / PRIMARY_KEY)

### Actual behaviour
Exported file has creation of table and adding indexes as separate commands.

    CREATE TABLE `archive` (
      `id` int(11) NOT NULL,
      `name` varchar(50) NOT NULL
    ) ENGINE=ARCHIVE DEFAULT CHARSET=latin1;

    ALTER TABLE `archive` ADD PRIMARY KEY (`id`);

This causes MYSQL to fail with error: `#1030 - Got error -1 from storage engine`. (and stops further import)

### Server configuration
**Operating system**:
Linux Ubuntu 12.04, 14.04 (most likely system independent)
**Web server:**
Apache2, PHP5 (most likely web server independent)
**Database:**
MySQL 5.3 and 5.6 (probably anything below 5.6 and maybe even 5.7)
**PHP version:**
5.3, 5.6, 7.0 (most likely independent)
**phpMyAdmin version:**
4.5.3.1 (I have this issue for few versions now). In older versions PMA created SQL files similar to MySQL native export (indexes in table creation queries)

**Comment by devenbansod** [comment]
The link [0] states that :
"The ARCHIVE engine supports the AUTO_INCREMENT column attribute. The AUTO_INCREMENT column can have either a unique or nonunique index. Attempting to create an index on any other column results in an error."

The problem is that we export Primary keys before Auto increments in the footer so it tries to add a primary key to a column which is not an auto increment one (until then) and fails.
 
[0] : http://dev.mysql.com/doc/refman/5.7/en/archive-storage-engine.html
