### ISSUE TITLE
Multiple server doesn't work?

### ISSUE THREAD

**Issue by dotku** [phpmyadmin/phpmyadmin#12089]
0
down vote
favorite
I have several servers, I setup the configuration like this, for examples:

```
$hosts = array(
    '1'=>array(
        'verbose'  => 'server1',
        'host'     => 'localhost',
        'user'     => 'root',
        'password' => 'password1'
    ),
    '2'=>array(
        'verbose'  => 'server2',
        'host'     => 'host2',
        'user'     => 'root',
        'password' => 'password2'
    )
);
```
then I use loop to duplicate the settings

```
for ($i=1; $i<=count($hosts); $i++) {
    /* Authentication type */
    $cfg['Servers'][$i]['auth_type']       = 'cookie';
    $cfg['Servers'][$i]['user']            = $hosts[$i]['user'];  
    $cfg['Servers'][$i]['password']        = $hosts[$i]['password']; 
    $cfg['Servers'][$i]['host']            = $hosts[$i]['host']; 
    $cfg['Servers'][$i]['connect_type']    = 'tcp';
    $cfg['Servers'][$i]['compress']        = false;
    /* Select mysql if your server does not have mysqli */
    $cfg['Servers'][$i]['extension']       = 'mysqli';
}
```
the page was successfully load on http://localhost/phpmyadmin with drop down select menu, but when I click "Go" for login, nothing happens. Is there any configuration I'm missing?

P.S., I did use manually input the login information, and it works successfully, but configuration list just doesn't work. There is no error message at all :(

**Comment by ibennetch** [comment]
This should work fine, since of course PHP is just using one variable to point to another, and in fact it works okay for me testing just now.

At first I thought there might be trouble because you're making the outer array a string instead of an integer (`'1'=>array` instead of `1=>array`), but in my tests this made no difference due to PHP's type conversion.

I wonder what `print_r($hosts);` and `print_r($cfg);` says if you put those at the end of your `config.inc.php`.

**Comment by nijel** [comment]
If you want phpMyAdmin to use stored credentials, you need to use auth_type ``config`` not ``cookie`` as you're using.
