### ISSUE TITLE
phpMyAdmin 4.5.5 not worked with CentOS 7 64 bit, PHP 5.6

### ISSUE THREAD

**Issue by AlexL777** [phpmyadmin/phpmyadmin#12096]
### Steps to reproduce
1. install CentOS 7 64bit
2. install phpmyAdmin 4.4 and update to 4.5
3. configure phpMyAdmin.conf file
4. go in the Browser to /phpMyAdmin

### Expected behaviour
hello Developers,

Unfortunately, I have a problem with the phpmyadmin at Centos 7 and PHP 5.6. I use mySQL latest version and have done everything according to instructions. I installed phpmyadmin and then the mySQL Community Server to the terminal and configured to phpmyadmin in phpMyAdmin.conf file.

In it looks like this:

    Alias /phpMyAdmin /usr/share/phpMyAdmin
    Alias /phpmyadmin /usr/share/phpMyAdmin

    ## Comment below section to allow everyone
    <Directory /usr/share/phpMyAdmin/>
    <IfModule !mod_authz_core.c>
     Order Deny,Allow
     Deny from All
     Allow from 95.91.226.11
     Allow from ::1
    </IfModule>
    </Directory>

    <Directory /usr/share/phpMyAdmin/libraries/>
    Order Deny,Allow
    Deny from All
    Allow from None
    </Directory>

    <Directory /usr/share/phpMyAdmin/setup/lib/>
    Order Deny,Allow
    Deny from All
    Allow from None
    </Directory>

    <Directory /usr/share/phpMyAdmin/setup/frames/>
    Order Deny,Allow
    Deny from All
    Allow from None
    </Directory>

Then I call in the browser http://projekte.alexl.eu/phpMyAdmin and get a "Forbidden Error Message" appears.

I have already searched dozens forums and read some instructions, but it did not.

Can you possibly help me?

Thanks in advance.

### Actual behaviour
Tell us what happens instead

### Server configuration
**CentoOS 7 64 bit**

**Linux**

**Database**

**PHP 5.6**

**phpMyAdmin 4.5.5**

### Client configuration
**Firefox and Google Chrome**

Or is it a CentOs Issue and should I go to the support forum ??

**Comment by ibennetch** [comment]
Did you install from the rpm package or by downloading and uncompressing the file from phpmyadmin.net?

This sounds like a server configuration issue, perhaps your file permissions on the phpMyAdmin directory are too restrictive or the directory isn't `+x` or some such.

**Comment by AlexL777** [comment]
I have tried both and ultimately I decided for PHP 5.4 and 4.4 PHPMyAdmin. PhpMyAdmin 4.4 I installed with "YUM".

This worked so equal, once I configure phpmyadmin means phpmyadmin.conf. I do not know if it is CentOs to PHP 5.6.

At some it must have been lying and I think I can work as the first time.

**Comment by ibennetch** [comment]
Unfortunately, we don't have control over the CentOS package, and this appears to be a configuration issue with how their package is operating. Aside from changing permissions on your own, the next best thing would be to ask the CentOS folks for assistance. Good luck.

**Comment by nijel** [comment]
Maybe @robert-scheck could comment on this...

**Comment by robert-scheck** [comment]
The initial report still leaves a bunch of questions, because CentOS 7 ships PHP 5.4 and I have to assume that phpMyAdmin 4.4.x from EPEL is used. This combination is known to work in general. So, PHP 5.6 and phpMyAdmin 4.5.x could be from various sources. It could be even a SELinux issue due to some user misconfiguration. 

From my point of view, based on wild guessing, the cause is your `/etc/httpd/conf.d/phpMyAdmin.conf` file. Apache 2.4 provides and enables `mod_authz_core` by default, thus your condition `<IfModule !mod_authz_core.c>` evaluates to false. Default file is http://pkgs.fedoraproject.org/cgit/rpms/phpMyAdmin.git/tree/phpMyAdmin.htaccess, slightly different compared to the posted one. Based on this shipped file, the first `Require ip 127.0.0.1` and `Require ip ::1` need to be replaced by one `Require all granted` if phpMyAdmin shall be publically reachable. Don't forget the reload of Apache.

**Comment by ibennetch** [comment]
Thanks @robert-scheck.
