### ISSUE TITLE
Row_format = fixed not visible

### ISSUE THREAD

**Issue by kaalis** [phpmyadmin/phpmyadmin#12195]
I was comparing mysql table structure dump with specific Operations tab in phpmyadmin interface, that listed row_format=compact, although "show create table xxx" lists table as row_format=fixed.

No big deal, but still a bug, as I'm moving to mysql 5.7.12 - it doesn't have fixed format anymore.

![capture1](https://cloud.githubusercontent.com/assets/787507/14604084/63bd9438-057a-11e6-90e8-590ce162afea.png)

![capture2](https://cloud.githubusercontent.com/assets/787507/14604097/747fd0b0-057a-11e6-9337-abf5b7146b5b.png)

```
Macosx 10.5.8 PPC (yeah, old dinosaur)
Mysql 5.0.92
Apache/2.2.17 (Unix) PHP/5.2.15
Database client version: libmysql - 5.0.92
PHP extension: mysqli
Phpmyadmin: 4.0.10.15 (latest)
```

**Comment by devenbansod** [comment]
This would be a problem only for imports which are being done on newer MySQL versions (5.7.7+) but have been exported on older versions.

Excerpt from [ref] (http://dev.mysql.com/doc/refman/5.7/en/create-table.html)
> ROW_FORMAT=FIXED is not supported. If ROW_FORMAT=FIXED is specified while innodb_strict_mode is disabled, InnoDB issues a warning and assumes ROW_FORMAT=COMPACT. If ROW_FORMAT=FIXED is specified while innodb_strict_mode is enabled, which is the default as of MySQL 5.7.7, InnoDB returns an error.

In Older MySQL versions (5.7.6 and before) used to accept the `ROW_FORMAT=FIXED` even with InnoDB tables (since default for innodb_strict_mode was OFF [ref](http://dev.mysql.com/doc/refman/5.5/en/innodb-parameters.html#sysvar_innodb_strict_mode)). But the newer MySQL versions (5.7.7+) don't accept it (since default for innodb_strict_mode is ON [ref](http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_strict_mode)). 

I think we can help such users who are migrating from older MySQL versions to the newer ones by issuing a FAQ in the docs on turning the value of `innodb_strict_mode` to OFF from the 'Variables' page before running such imports.
