### ISSUE TITLE
Can't log in with MySQL username containing "á"

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12232]
### Steps to reproduce
1. Create a user containing the `á` character (mine is simply called `á` without any other characters)
2. Log out and attempt to log in as that user

### Expected behaviour
I should be logged in successfully

### Actual behaviour
I am shown the error message
> mysqli_real_connect(): (28000/1045): Access denied for user 'á'@'localhost' (using password: YES)

### Server configuration
**Operating system**:
Debian Linux
**Web server:**
Apache 2.4.10
**Database:**
MySQL 5.5.49
**PHP version:**
5.6.20
**phpMyAdmin version:**
4.7.0-dev; git revision 5a4af02
**Client library**
libmysql - 5.5.49
### Client configuration
**Browser:**
Firefox 46.0.2
**Operating system:**
Mac OS X

**Comment by ibennetch** [comment]
By the way, `mysql -u á -p` works correctly.

**Comment by nijel** [comment]
This is caused by client charset being set to something else that utf-8. The problem is that there is no way in PHP to set charset before authenticating. So PHP is sending utf-8 encoded string, while MySQL parses it as iso-8859-1 (what is usually the default).

Also see http://php.net/manual/en/mysqli.real-connect.php#refsect1-mysqli.real-connect-notes

So I think the only way to allow authentication with non ascii usernames (or passwords) is to change server default charset to utf-8.

**Comment by ibennetch** [comment]
Thanks for figuring that out.

So this is really a MySQL configuration issue and there's nothing we can do about it.I'm not even sure that this is worth adding a  FAQ entry about at this point. What do you think?

**Comment by nijel** [comment]
I'm not sure either. I assume you have found this while solving question of some user, right?

**Comment by ibennetch** [comment]
Correct, although I believe discovering this was a side-effect of their actual problem, rather than the problem itself.

If there's nothing to be done in the code, I think it's best to write a FAQ about it and move on.

**Comment by ibennetch** [comment]
Do you mind reviewing https://github.com/phpmyadmin/phpmyadmin/pull/12284 for accuracy?

**Comment by Aboelfotoh83** [comment]
Did you find a solution for this problem? I am facing it right now. I don't know if phpmyadmin is considering this letter [English Language](https://e3raph.com/) or not.
