### ISSUE TITLE
127.0.0.1:8888/phpmyadmin/ returns Unable to connect from browser

### ISSUE THREAD

**Issue by millionwaldeab** [phpmyadmin/phpmyadmin#12266]
### Steps to reproduce
1. My xampp server is deployed to Google compute engine. Launch puTTy from windows to access remote server like [this tutorial](https://www.apachefriends.org/docs/hosting-xampp-on-google.html).  Access to phpmyadmin is working as 127.0.0.1/phpmyadmin in my local machine
2. While PuTTy running enter 127.0.0.1:8888/phpmyadmin to connect to the login page of phpmyadmin
 

### Expected behaviour
Display the phpmyadmin login page
### Actual behaviour
Unable to connect is displayed upon entering the url on my browser

### Server configuration
**Operating system**:
Windows 7
**Web server:**
xampp
**Database:**
MySQL
**PHP version:**
5.6.19
**phpMyAdmin version:**
Version 4.2.11

### Client configuration
**Browser:**

**Operating system:**
Windows 7

**Comment by ibennetch** [comment]
I'm a little confused here; since phpMyAdmin works from http://127.0.0.1/phpmyadmin why do you also expect it to work as http://127.0.0.1:8888/phpmyadmin ? In the tutorial, it appears as if they're tunneling local port 80 to remote port 8888, but I don't see anywhere that they are tunneling local port 8888.

This is functioning how I'd expect it to.

**Comment by nijel** [comment]
I think this is rather wrong configuration of port forwarding in putty rather than problem in phpmyadmin.
