### ISSUE TITLE
ChangeLog discrepancy for 4.4.15.6

### ISSUE THREAD

**Issue by cwittmer** [phpmyadmin/phpmyadmin#12280]
### Steps to reproduce
1. Check changes here:
https://www.phpmyadmin.net/news/2016/5/26/phpmyadmin-security-notifications-and-44156-released/
fixes for PMASA-2016-14, -15 and -16

2. Check ChangeLog her:
https://github.com/phpmyadmin/phpmyadmin/blob/MAINT_4_4_15/ChangeLog
fix only for PMASA-2016-16

which of both is correct and which not ?

**Comment by ibennetch** [comment]
I can see how this is a bit confusing, but in the end both are correct.

The news posting you reference has all three security notifications, for [-14](https://www.phpmyadmin.net/security/PMASA-2016-14/), [-15](https://www.phpmyadmin.net/security/PMASA-2016-15/), and [-16](https://www.phpmyadmin.net/security/PMASA-2016-16/). These are a broad series of notifications that happen to have been grouped in with the release announcement so as to not send extra mail to the list, not because each of them apply to 4.4.15.

The only one of those three that was fixed in 4.4.15, is PMASA-2016-16, so the ChangeLog is also accurate. You can find more information in the details of each related PMASA.

Hope that helps.

**Comment by cwittmer** [comment]
Yes, it does.
Thank you for clarifying :)
