### ISSUE TITLE
Reverse Proxy without PmaAbsoluteUri?

### ISSUE THREAD

**Issue by cracker0dks** [phpmyadmin/phpmyadmin#12374]
According to to wiki: https://wiki.phpmyadmin.net/pma/Config/PmaAbsoluteUri I should implement $cfg['PmaAbsoluteUri'] to use my reverse nginx proxy.

According to: https://docs.phpmyadmin.net/en/latest/config.html?highlight=pmaabsoluteuri#cfg_PmaAbsoluteUri its Deprecated (removed 4.6.0) and I should config my webserver.

I tried by changing the http header and stuff but without success.
Can someone please update the wiki and give a hint how to to "adjust your webserver instead"?

That would be nice :)

PS: if not, pls give me PmaAbsoluteUri back :D

**Comment by ibennetch** [comment]
Indeed, I missed that page when I removed the Config section of the wiki as part of https://wiki.phpmyadmin.net/wiki/index.php?title=Config&diff=8293&oldid=8113

The wiki database is currently locked from editing due to being in the middle of a wiki migration, so that part will get fixed sometime in the future as we complete the migration. As for the rest, a guide to configuring a reverse proxy, we'll have to discuss to see whether that's something better explained by the phpMyAdmin documentation or by referring to generic webserver configuration guides. I've added it to the agenda for discussion at the next developer meeting.

**Comment by nijel** [comment]
I think we need PmaAbsoluteUri for this case as the server has no clue what the original URL was (at least in the usually used setups).

**Comment by poppahorse** [comment]
Definitely needed, at the moment phpmyadmin just doesn't function if loaded via reverse proxy

**Comment by alexweissman** [comment]
This bit me when following DigitalOcean's tutorial on [installing phpmyadmin with nginx](https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-with-nginx-on-an-ubuntu-14-04-server).

**Comment by nijel** [comment]
Related commits:

* ae1ccf3e6a6311c90550942755cd33c1b7ca869b
* a569eeca93aadcd8c80480ce23675d97522140ed

**Comment by nijel** [comment]
Okay now it's back. It's way less fault tolerant than it used to be as the original checkPmaAbsoluteUri() code was main motivation to get rid of this setting as it tend to break in various circumstances.

**Comment by sul4bh** [comment]
@nijel checkPmaAbsoluteUri() is not in 4.6.4 (version used by docker image).

```
ENV VERSION 4.6.4
ENV URL https://files.phpmyadmin.net/phpMyAdmin/${VERSION}/phpMyAdmin-${VERSION}-all-languages.tar.gz
```

I could clone the official phpmyadmin docker image and modify the download URL to point to master branch. But I am not sure if files.phpmyadmin.net has a tar.gz of the master branch. Can it be added?

**Comment by nijel** [comment]
It will be in 4.6.5 . You can get tarball from github. And you don't want master, but rather 4.6 maintenance branch: https://github.com/phpmyadmin/phpmyadmin/archive/QA_4_6.tar.gz
