### ISSUE TITLE
request to remove mbstring dependency

### ISSUE THREAD

**Issue by pilavdzic** [phpmyadmin/phpmyadmin#12386]
Background:

I know I am not the only one that works in an environment that is running old versions of everything and has security folks that do not allows installation of any packages (because a quick search for redhat and mbstring yields many people with issues installing mbstring). Most of us only need mbstring to run phpmyadmin. 

PhpMyAdmin is such a critical tool that eliminating dependencies would be beneficial to all.

Suggestion:

Could we have a version of phpmyadmin that has a shim for mbstring built in like: https://github.com/tchwork/utf8/blob/master/src/Patchwork/PHP/Shim/Mbstring.php
so that it can operate without this dependency?

I think this would benefit many people.  If the developers of phpmyadmin are amenable to this, I can take a crack at implementing this? Yes I know how ridiculous it is and will probably have worse performance (obviously it would detect if mbstring exists and if so would use that), but some of us badly need this (for v4.0).

Thoughts?

**Comment by nijel** [comment]
I'm not sure if iconv dependency is better than mbstring dependency (this is what referenced code uses).

However we still do have code to make this dependency optional (by simply ignoring all possible issues this can bring), see https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/stringNative.lib.php. It's disabled because it's incomplete for what we require and nobody bothered to fix it (see also f0232c3c).

So generally I'm not opposed to make mbstring optional, however it will either introduce another dependency (such as iconv or recode), or will break random things with UTF-8 input.

PS: Looking at the code now, I've realized that ``mb_strlen`` is used way more than it should, filed #12397 for that.
