### ISSUE TITLE
$cfg['ThemeDefault'] appears broken

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12390]
As first noticed [here](http://stackoverflow.com/questions/38412969/phpmyadmin-change-default-theme) (and tested by me), it appears as if `$cfg['ThemeDefault']` doesn't work anymore.

The reporter is using 4.4, I'm using master.

**Comment by nijel** [comment]
Not sure it it's related, but theme fallback doesn't seem to work properly if chosen theme is not existing.

**Comment by devenbansod** [comment]
It works for me on master as well as QA_4_6, but only if I go **incognito** or remove 'pma_theme' cookie. 
But I am not sure if this is the expected behavior or not.

Consider the scenario:
`$cfg['ThemeDefault']` is set as 'metro'. User goes to login page (assume for the first time). The Metro theme (as set by ThemeDefault) is rendered. Now after logging in User selects 'Original' theme. (i.e. now pma_theme cookie has now been updated to 'original')

When the user logs out of this session, what should be the theme rendered on login page and next time he/she logs on from same computer ? 

Option 1 (we are currently using):
The last selected theme by the user is loaded (original in the above scenario).

Option 2:
The theme set in `$cfg['ThemeDefault']` is always loaded at the start (login page) (metro in the above scenario) and can be changed by the user only after he/she logs in ( assuming `$cfg['ThemeManager']` is not set to false) and that too is set only for current login session.

What do you think should be the expected behavior ?

**Comment by devenbansod** [comment]
@nijel any comment on/inclination towards any of the above mentioned options for expected behavior ?

**Comment by nijel** [comment]
I think option 1 makes more sense - keep the user choice.

**Comment by devenbansod** [comment]
I agree that keeping the user preference makes more sense. 

Also then if we agree that this is the expected behavior, then the feature seems to be working as expected for me. 
* Any new user (I mean a user from browser without `pma_theme` cookie already present, may be incognito/private mode) opens phpMyAdmin, the default theme (set by `$cfg['ThemeDefault']` ) is rendered on the login page. 
* He/she can obviously change the Theme from the theme selection drop-down on index page. Once it is set from here, the `pma_theme` cookie is set and this theme would automatically rendered next time he/she logs in from this browser (obviously without clearing the cookies).
* If the user does not change it from the drop-down, then every time the theme set by `$cfg['ThemeDefault']` would be rendered.

**Comment by nijel** [comment]
You're right, it really seems to work fine. @ibennetch can you please confirm this?

**Comment by ibennetch** [comment]
Indeed, this appears to be working correctly.

I agree that the user preference should take priority over the default value.

Thanks for your effort.
