### ISSUE TITLE
Store composer.lock in git for releases

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12408]
We should store composer.lock for 4.7.0 and newer releases. This would allow to reproduce build in future and it would also provide us information which composer package versions were shipped in the release.

There seems to be some hints here:
https://laracasts.com/discuss/channels/general-discussion/composer-freeze-versions

**Comment by ibennetch** [comment]
As a partial alternative/enhancement to this, we might consider adding git version information to the phpMyAdmin libraries (shapefile, sql-parser, and motranslator) which could be displayed as part of the version information on the main page. The downside is that this area is already busy enough and doesn't need more git commit hashes cluttering up the area.

**Comment by nijel** [comment]
The release will have composer.lock listing the versions, so we might display libraries versions from it.

This is more about storing this information on git tag, so that we know what we've released. This will also allow us to test exactly released mix of libraries by just running composer update in the checkouted tag.

**Comment by ibennetch** [comment]
I understand better now. This is definitely a good idea.

**Comment by fliespl** [comment]
Can we also store composer.lock in STABLE branch like you do in zip files? 

I am using git to automatically update pma on all servers. That requires me to run `composer update` almost everytime since `composer.lock` is .gitignored.

If it weren't I could just use composer install to install packages that are known to be stable versions (while composer update might easily break things).
