### ISSUE TITLE
phpMA v4.6.3: Can't Execute SQL With Sub-Query Due To "LIMIT 0,25" Inserted At Wrong Place

### ISSUE THREAD

**Issue by fanatixgithub** [phpmyadmin/phpmyadmin#12461]
SQL I'm using is one to pull out a [Nested Set](http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/) data structure for a hierarchical tree of stuff:

```sql
SELECT
	node.id, node.name, (COUNT(parent.name) - (sub_tree.depth + 1)) AS depth ,node.active_season,node.visible,node.likeable,node.has_logo,node.sort,node.mongo_id,node.tag
FROM
	eventgroups AS node,
	eventgroups AS parent,
	eventgroups AS sub_parent,
	(
		SELECT
			node.id, (COUNT(parent.id) - 1) AS depth
		FROM
			eventgroups AS node,
			eventgroups AS parent
		WHERE
			node.ns_left BETWEEN parent.ns_left AND parent.ns_right
			AND node.id = 4
		GROUP BY
			node.id
		ORDER BY
			node.ns_left
	) AS sub_tree
WHERE
	node.ns_left BETWEEN parent.ns_left AND parent.ns_right
	AND node.ns_left BETWEEN sub_parent.ns_left AND sub_parent.ns_right
	AND sub_parent.id = sub_tree.id
GROUP BY
	node.id
ORDER BY
	node.ns_left
```

In phpMyAdmin's output it first moans about something it shouldn't:

```
Static analysis:

2 errors were found during analysis.

    An expression was expected. (near "(" at position 261)
    Unexpected token. (near "(" at position 261)
```

And then it causes an actual SQL error by inserting its pagination "LIMIT" statement in the wrong place:

```
SELECT node.id, node.name, (COUNT(parent.name) - (sub_tree.depth + 1)) AS depth ,node.active_season,node.visible,node.likeable,node.has_logo,node.sort,node.mongo_id,node.tag FROM eventgroups AS node, eventgroups AS parent, eventgroups AS sub_parent, ( LIMIT 0, 25

MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0, 25' at line 7
```

This is on 4.6.3 so long after https://github.com/phpmyadmin/phpmyadmin/issues/11558 was supposedly fixed, but it appears to be the same problem.

**Comment by devenbansod** [comment]
I believe this is fixed now (since https://github.com/phpmyadmin/phpmyadmin/commit/f4877a782639202770e71771d927129ff8fa2085) i.e. the query gets executed without an SQL error (though phpMyAdmin's linter shows some syntax errors). 

You can confirm if it is fixed by using the patch https://github.com/phpmyadmin/phpmyadmin/commit/f4877a782639202770e71771d927129ff8fa2085.patch and re-open if it is not.

The error relating to parsing of sub-query in the FROM clause is being tracked at : https://github.com/phpmyadmin/sql-parser/issues/52
