### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#12474]
As reported by Emanuel Bronshtein, 
currently when visiting:
    https://demo.phpmyadmin.net/master-config/setup/
all links in menu return 404.

**Comment by nijel** [comment]
Caused by removing token from GET requests...

**Comment by devenbansod** [comment]
I think the links' 404 errors have been fixed in https://github.com/phpmyadmin/phpmyadmin/commit/44760aca0b8c818a839b3a8edc0e0b01b981d467, but don't seem to work on. They are not working (showing any changes) because of the reason I mentioned in https://github.com/phpmyadmin/phpmyadmin/issues/12494#issuecomment-242277697
