### ISSUE TITLE
Error creating foreign key on field_id (check data types)

### ISSUE THREAD

**Issue by nujuna** [phpmyadmin/phpmyadmin#12489]
### Expected behaviour

Show the real errors like on Storage Engine Status display.
### Actual behaviour

I get error "Error creating foreign key on `customer_id` (check data types)".
But when i check in Storage Engine Status, I get error "A foreign key constraint of name `dbname`.`fk_w_customer_id` already exists."
### Server configuration

**Operating system**: Ubuntu 14.04.5 LTS

**Web server**: Apache/2.4.7

**Database**: MariaDB

**PHP version**: 5.5.9

**phpMyAdmin version**: 4.6.2
### Client configuration

**Browser**: Mozilla Firefox

**Operating system**: Windows 10

**Comment by Braindea7** [comment]
I want to refresh this. It's still a "bug" in the newest version of phpmyadmin. 
If a foreign key name is already in use, you get the Error 
"Error creating foreign key on [table] (check data types)". It should be something like "Error creating foreign key on [table] (name is already in use)".

**Comment by msvamp** [comment]
**This bug is now fixed.**
Just tested the above behaviour on the latest PHPMyAdmin release (v5.0.1 at the time of writing) - it reports the error correctly. The test was performed by creating 2 different foreign key constraints with the same name in the same and in different tables in the same database.

![(Screenshot) PHPMyAdmin Demo RELEASE_5_0_1-1077-g27d631e164](https://user-images.githubusercontent.com/51392775/75092614-9ff4c100-559f-11ea-9d71-b2fefb9cde45.png)


*Database server:* phpMyAdmin demo - MySQL (192.168.30.23 via TCP/IP)
*Server version:* 8.0.18 - MySQL Community Server - GPL
*Server charset:* UTF-8 Unicode (utf8mb4)

*Web server:* nginx/1.10.3
*Database client version:* libmysql - mysqlnd 7.4.2
*PHP version:* 7.4.2

*phpMyAdmin:* RELEASE_5_0_1-1077-g27d631e164

**Comment by williamdes** [comment]
Thank you @msvamp !
