### ISSUE TITLE
Can't add new user

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12494]
### Steps to reproduce
1. Go to the "User accounts" tab
2. Scroll down and press "Add new user"

### Expected behaviour
I should get the dialog page to add a new user

### Actual behaviour
Nothing happens; the page appears to reload and remains on the user overview display.

Git says:
The first bad commit could be any of:
7f43348e6b77f12fc4669f7e5defb582bde49911
ea73fded7138038aa5a415c7081d838fc094eff7
599effd165623bcdd8624092cace4556bd2655fa
dae3390a02ca6687fd31ca784474d56240c6c538
238713b452ccb8a419ab13d8604d5576b9e81bcc

**Comment by devenbansod** [comment]
This is mainly because of removal of `token` from the GET Request URLs. The code [here] (https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/common.inc.php#L371-L428) checks if the `token` is available in the request, which after the change mentioned above, is not available in GET ones.

So, it removes all other request variables except the ones mentioned in the `$whitelist`. For confirmation, if you just add `adduser` to the `$whitelist` array, it would start working. I guess we should check for the token mismatch only if the `REQUEST_METHOD` is `POST`.

Also, this affects other dialog boxes as hide/unhide dialogs for items in Navigation panel etc.
