### ISSUE TITLE
Absence of scrolling makes it impossible to read longer text values in grid editing

### ISSUE THREAD

**Issue by qpurypaHT** [phpmyadmin/phpmyadmin#12554]
Hi! You speak Russian?
I found a `bug` in Styles CSS for your panel v.4.5.4.1.
My crazy hosting it was installed

**Comment by devenbansod** [comment]
I am afraid I don't know if any one from the team speaks Russian, but I am sure someone from the community or even some Google Translate usage can assist this discussion.

Please let us know the exact bug details and we would surely try to fix it. You can include a Filename and Line number may be to help us locate the bug.

Exact translation of above text from Google Translate (if you could not understand):
Боюсь, что я не знаю, если кто-нибудь из команды говорит на русском языке , но я уверен, что кто-то из сообщества или даже некоторые Google Translate использование может помочь этой дискуссии .

Пожалуйста, дайте нам знать точные подробности об ошибках , и мы бы , конечно, попытаться исправить это . Вы можете включить имя файла и номер строки, может быть, чтобы помочь нам найти ошибку .

**Comment by qpurypaHT** [comment]
Ok!
when editing the fields in the table - scrolling does not work:
```
.cEdit .edit_box {
    overflow: hidden;
    padding: 0;
    margin: 0;
}
```

When recording a lot of text, I can not read the end...

My Screens (files uploaded in my social page, Vkontakte):
https://pp.vk.me/c630331/v630331118/48400/XCMt8gEyvxM.jpg
https://pp.vk.me/c630331/v630331118/48409/26pbmtqUv1A.jpg
https://pp.vk.me/c630331/v630331118/48413/KxMALyq-fSs.jpg
https://pp.vk.me/c630331/v630331118/4841d/nvYnzg0WiE0.jpg

**Comment by devenbansod** [comment]
I think if you select 'Full texts' (instead of 'Partial Texts') from 'Options' slider just above the results table, and then you double click a value to edit it, it would not require you to scroll.

![options_slider](https://cloud.githubusercontent.com/assets/5762808/18521765/0dcf2e30-7acb-11e6-85d7-99dbc249de32.png)

![new_table](https://cloud.githubusercontent.com/assets/5762808/18521772/121eed9a-7acb-11e6-8eac-a95ddd0971ae.png)

![edititing_table](https://cloud.githubusercontent.com/assets/5762808/18521777/18796896-7acb-11e6-9ffc-c3f157e2484c.png)

**Comment by qpurypaHT** [comment]
Wow! I did not know it! I only teach MySQL,
I can not find in their Russian-speaking panel of the item

**Comment by qpurypaHT** [comment]
found! Thank you!)

**Comment by qpurypaHT** [comment]
This is so bad!
If I want that was not the full text, then why can not I use the scroll?
I am inclined to think that this is a bug
