### ISSUE TITLE
new option for exporting table data

### ISSUE THREAD

**Issue by domnulnopcea** [phpmyadmin/phpmyadmin#12570]
introduce a new option that would allow skipping export of primary keys

**Comment by devenbansod** [comment]
I am not sure if it would find a use-case with many users. I don't remember (please correct me if I am wrong) if even mysqldump provides that option.
It might be possible to implement in phpMyAdmin since we produce the create table definition first without the indexes and keys, which we append later in alter statements while mysqldump includes them in the create definition itself.

Also, you mean to say not to export *all* the indexes and keys on a table right ? It does make much sense to say primary keys as there can be only one primary key on a table.

**Comment by nijel** [comment]
@domnulnopcea Can you please provide use case for this?

**Comment by nijel** [comment]
Closing due to no feedback.
