### ISSUE TITLE
Creating Table with Decimal only honors first value

### ISSUE THREAD

**Issue by startailcoon** [phpmyadmin/phpmyadmin#12623]
### Steps to reproduce
1. Create a new column with decimal as the type.
2. Set the type to anything that isn't ending with a 0. Ex. 10,2 or 18,4 etc.
3. The query still only inserts a decimal with 10,0 or 18,0.
4. Editing the query by hand to 10,2 will make the table set the correct decimal size of the column.

### Expected behaviour
The query should insert with the correct decimal value.

### Actual behaviour
It did not.

### Server configuration
**Operating system**: Linux, Ubuntu 4.7.0-x86_64-linode72

**Web server:**  Apache/2.4.18 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper

**PHP version:** PHP 7.0.8-0ubuntu0.16.04.2

**phpMyAdmin version:** phpmyadmin/xenial-updates,xenial-updates 4:4.5.4.1-2ubuntu2 all

### Client configuration
**Browser:** Edge

**Operating system:** Windows 10

**Comment by devenbansod** [comment]
Hi @startailcoon , thanks for the report but it seems this has already been reported and fixed at #12480. The fix would be a part of the next bug-fix release i.e. 4.6.5

I am surprised though this is happening on the version mentioned, because all other reports we recieved were for 4.6.4 only. Anyway, you can test that this is indeed fixed by testing at https://demo.phpmyadmin.net/QA_4_6/?pma_username=root .

**Comment by startailcoon** [comment]
Thanks for the quick respons devenbansod.
It is indeed working on the demo server.

My bad on the PHP Versionen. I was using a custom installed installation from source and not the one installed on the server by apt. The apt version is to outdated for me :)
