### ISSUE TITLE
LIMIT 1 gets appended to commands, when I click on delete or create row and error 1064 pops up

### ISSUE THREAD

**Issue by GrafPedro** [phpmyadmin/phpmyadmin#12627]
### Steps to reproduce
1. I had "LIMIT 1" at the end of a query in one of my PHP files.
2. The query failed and I deleted LIMIT 1
3. Whenever I click delete row LIMIT 1 gets attached and error 1064 in line 1 gets shown.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:
Mac OS 10.12.1 Beta (16B2338c)
**Web server:**
5.6.28 - MySQL Community Server (GPL)
**Database:**
 libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 241ae00989d1995ffcbbf63d579943635faf9972 $
**PHP version:**
PHP 7.0.10
**phpMyAdmin version:**
4.6.4
### Client configuration

**Browser:**
Safari 10.0.1 (12602.2.14.0.1)
**Operating system:**
Mac OS 10.12.1 Beta (16B2338c)

**Comment by devenbansod** [comment]
In MySQL only if the Delete query is multi-table then LIMIT clause is not allowed. Otherwise Delete statements like 
```
DELETE FROM `table1` WHERE `col1` = '1' LIMIT 10
``` 
should work as expected. 

Are you trying to delete the rows from Browse tab of a table or from somewhere else ? Also, what is the exact query that is being run and is giving an error?

**Comment by nijel** [comment]
Closing due to no response.
