### ISSUE TITLE
Refactor PMA_setGlobalVariablesForEngine

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#12703]
Currently `PMA_setGlobalVariablesForEngine` returns long list of variables which are then passed around the code. This is really bad design patter, it should be made more transparent to the users. One of possibilities is to move the code to the Table class and use it from there (with caching).

See also #12567

**Comment by arimourao** [comment]
How do I assign this issue to me? I will give it a try!

**Comment by nijel** [comment]
You can give it a try :-). AFAIK nobody is working on this.

**Comment by arimourao** [comment]
I was looking through the code and I think that this can be simplified a lot. There is no need to have several boolean variables in the Table class just to tell if it is a kind of storage engine or not. For instance, I will add a variable in the Table class that will hold the string value of the select storage engine (ie "InnoDb") and instead of

`if($is_innoDb){
   //Do this
}`

I can simply have:
`if($tableInstance->tbl_storage_engine == 'InnoDb'){
   //Do this   
};
`
right?

**Comment by nijel** [comment]
I think motivation for this was to avoid doing string comparison too many times as this is something what is used quite often. But maybe in the end this is just overoptimized and  string comparison would work fine.

In either case this is used quite often, so I'd prefer some nicer interface to this, for example having ``Table::isEngine`` method, which would take string or array (to match against multiple engines) and return boolean.
