### ISSUE TITLE
Grouping in navigation panel works not well

### ISSUE THREAD

**Issue by WileC** [phpmyadmin/phpmyadmin#12714]
### Steps to reproduce
1. mysql-user with rule to access % databases (root, special-admin-user)
2. phpmyadmin 6.4.6
3. normal user account with access to it's own databases

### Expected behaviour
Databases with seperator "_" should group, tables with seperator "__" should group with all users

### Actual behaviour
Database-grouping works only with normal user accounts (not "%"), table-grouping works with no user

### Server configuration
**Operating system**: Windows Server 2012 R2

**Web server:** IIS7.5

**Database:** mysql 5.7.16

**PHP version:** 5.6.25

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Firefox 50

**Operating system:** Win 7 Prof. 64bit
![phpmyadmin_screenshot](https://cloud.githubusercontent.com/assets/15234774/20436447/9644d888-adb0-11e6-8820-5cd2de774838.jpg)

**Comment by devenbansod** [comment]
If you are looking to have all the `pma__` tables to be grouped, it was removed after implementation of #6326 since version 4.5.0. The feature request says "Don't group tables in tree if the result has only one group" which I believe makes sense. 

Could you try to reproduce the database grouping problem on [our demo server] (https://demo.phpmyadmin.net/QA_4_6/?pma_username=root) ?

**Comment by WileC** [comment]
On the demo-server there works all fine... but there is no user-login :/

**Comment by nijel** [comment]
As said before - this is intentional if there would be only one group in the database.
