### ISSUE TITLE
Change package guzzle/guzzle for guzzlehttp/guzzle

### ISSUE THREAD

**Issue by arimourao** [phpmyadmin/phpmyadmin#12716]
### Steps to reproduce
1. clone the repo
2. run composer install
3. message alerts at the end that guzzle/guzzle package is abandoned. Suggests to use guzzlehttp/guzzle instead

### Expected behaviour
Composer should install everything without warnings

**Comment by devenbansod** [comment]
I think we don't have a direct dependency on guzzle, but I think it is php-coveralls (on which we have a `require-dev` dependency).

I believe since [their composer.json](https://github.com/satooshi/php-coveralls/blob/master/composer.json)  has already got the change, the next major release of php-coveralls (i.e. 2.0) (and we shifting our dependency to the newer version, which is based on the compatibility of the minimum PHP version that it requires and the one that we require) would remove that warning in future.

**Comment by nijel** [comment]
This is not really our bug, see https://github.com/satooshi/php-coveralls/issues/152

**Comment by nijel** [comment]
This has been fixed in https://github.com/satooshi/php-coveralls/commit/07473e6edef50aa9c2b284b8c8c0d45974a2a4dd, but it still is not part of released version.

**Comment by ibennetch** [comment]
Based on the age of the discussion there (it's from 2015), I don't expect a
quick release of the corrected version. I've been thinking about this for
some time and they don't seem motivated to fix this problem (which would
only require performing a release; the fix has already been committed).

Is it worth us creating a fork (at least for now, until they release a
proper fix) just to avoid the warning? That might become the optimal
solution.

**Comment by nijel** [comment]
Another way to fix this for us is to stop using coveralls, would anybody mind?

**Comment by mauriciofauth** [comment]
Is there any alternative to satooshi/php-coveralls?
Is there any benefit in continuing to use Coveralls?

**Comment by ibennetch** [comment]
Unless I am mistaken, the only benefit from Coveralls is seeing the percentage of our code which is covered by tests. Since it's not nearly 100%, referring to that number is not very meaningful for me so I am fine dropping that aspect.

**Comment by nijel** [comment]
We have codecov as well, so I don't think we will miss it much...
