### ISSUE TITLE
Clickable User Names in User accounts overview

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12726]
Could user names in Users overview be made clickable with a link to editing that user?

I know there's a tiny edit button but having the name be clickable would be far easier..

**Comment by OlafvdSpek** [comment]
The same applies when editing Database-specific privileges for a user.
Also, when editing Database-specific privileges for a user, there doesn't appear to be a link / button back to the previous page.. and browser-Back doesn't work properly.

**Comment by devenbansod** [comment]
It does seem that it might it easier to go the edit privileges page, but a check would have to be added that the usernames are clickable only when the current user has the adequate privileges to edit them.

Also, the second enhancement about adding a back button sounds good. You can open a separate issue so that it does not get missed out on and is also properly discussed.

**Comment by amarjitsingh52922** [comment]
@OlafvdSpek going to work on clickable username to go to edit privileges page

**Comment by thesmallstar** [comment]
@devenbansod can I work on this?

**Comment by williamdes** [comment]
@thesmallstar Yes, please use QA_5_0 as base and feel-free to ask questions ;)
