### ISSUE TITLE
Provide regular (daily?) dev builds

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12821]
For non-dev people that still want to try the dev build it'd be nice to have automatic, daily builds available ready for download.

**Comment by ibennetch** [comment]
It's always available from https://github.com/phpmyadmin/phpmyadmin/archive/master.zip — which is sort of mentioned on the Downloads page, but I think we can change the link to point directly to the zipfile rather than the Github repository page.

**Comment by ibennetch** [comment]
Pull request at https://github.com/phpmyadmin/website/pull/50

**Comment by OlafvdSpek** [comment]
Isn't this just an export of the repo?
Thus, like the repo, it's missing the vendor directory and requires composer etc?

**Comment by ibennetch** [comment]
Oh, I see what you mean. Yeah, that's a good point.

**Comment by ibennetch** [comment]
@nijel What do you think about this? We'd have to do some work to change the infrastructure for this, but I think it would be somewhat useful to have a development snapshot available with all libraries bundled. With 4.7.0-alpha on the horizon, I'm not sure how much time we want to put in to this right now, though.

**Comment by nijel** [comment]
I'm not sure how much useful this would be, isn't better to more promote installation using composer?

**Comment by ibennetch** [comment]
The more I think about this, the more I like the idea. With the switch to using Composer for managing our library dependencies, it's much harder for people who don't have an interest in running composer to try the development version. They might want to try a new feature, pre-alpha testing the new version, or to resolve a bug that was fixed in master but not yet released. (not to mention that some days I could download and uncompress a developer build in less time than it takes Composer to update, but I digress).

We're probably all too focused on getting 4.7.0 in to beta release later this month to take care of this very soon, but if we can make the infrastructure play nicely with the idea then I'd like to see this happen.

**Comment by nijel** [comment]
I think this would be quite easy to achieve, actually we already have most of the needed bits in place.

However I'd prefer to first merge #12836 and then work on this as otherwise the daily snapshots structure will change later and there will be probably also some code changes needed to create release script which would need to be merged later.

**Comment by nijel** [comment]
Snapshots are now at https://www.phpmyadmin.net/downloads/#devel

**Comment by OlafvdSpek** [comment]
> https://github.com/phpmyadmin/REPONAME.git 

https://github.com/phpmyadmin/phpmyadmin might be a better link.

**Comment by nijel** [comment]
Thanks for suggestion, I've adjusted the paragraph a bit.

**Comment by emanuelb** [comment]
related 2 suggestions:
1. Add git commit used to create the build (thus it's possible to know where the build came from + help to reproducible-builds)
2. show date for daily snapshots (in case some build fails) & provide only functional builds (that pass tests) otherwise they not helpful for not-dev people (as author ask...)

**Comment by nijel** [comment]
Thanks for suggestions, I've implemented all of them:

![page-shot-2017-5-9 downloads](https://cloud.githubusercontent.com/assets/212189/25850819/126dcd76-34c4-11e7-9757-69c49d7918bd.png)
