### ISSUE TITLE
phpmyadmin returns more rows than exist in table

### ISSUE THREAD

**Issue by kolkov** [phpmyadmin/phpmyadmin#12880]
Hi! What I do wrong?

![image](https://cloud.githubusercontent.com/assets/3740898/21753014/28143b76-d5f4-11e6-923e-7b1d563b938c.png)

![image](https://cloud.githubusercontent.com/assets/3740898/21753020/44ca53ae-d5f4-11e6-8458-3bc9285a49dc.png)

![image](https://cloud.githubusercontent.com/assets/3740898/21753025/58196bb6-d5f4-11e6-82b6-d34d74d002b9.png)

![image](https://cloud.githubusercontent.com/assets/3740898/21753101/486c74b8-d5f6-11e6-829e-1e11cdeedc22.png)

**Comment by ibennetch** [comment]
I believe this is because phpMyAdmin uses a method to compute the total count that is very quick but not completely accurate. The count of which row is shown is precise, so it's giving a combination of exact count and approximate count (which is usually quite close, though I don't remember the margin of error). This information comes from MySQL itself and as far as I know it's rather intensive to compute the exact count each time, so I'm not aware of a good way to improve this display. I'll leave this open for a bit to collect some other opinions, though.

**Comment by nijel** [comment]
Yes, see our FAQ: [The number of rows for InnoDB tables is not correct.](https://docs.phpmyadmin.net/en/latest/faq.html#faq3-11)

**Comment by markus-ksg** [comment]
This is still a bug, even if the unexpected behavior is mentioned somewhere in an FAQ.

PhpMyAdmin's Tables pages correctly fixed the bug by showing a (?) with more info near the "Rows" column, and by prefixing approximated counts with a "~".

But in the given example, nothing tells the user that the count may be inexact. The message should at least also use a "~", e.g. "(~934171 total, Query took ... seconds.)"
