### ISSUE TITLE
Variables table unreadable

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12899]
Matching the values on the left to the values on the right is next to impossible..

I don't think this table should be full-width.

![pma](https://cloud.githubusercontent.com/assets/2218936/21990097/c868d446-dc0d-11e6-9f18-7f906a688f2d.PNG)

**Comment by ibennetch** [comment]
I tend to agree.

If we make the following change, it collapses a little bit, but because some of the variable names or values are really long, it still doesn't look great (see screenshot).

```
diff --git a/themes/pmahomme/css/common.css.php b/themes/pmahomme/css/common.css.php
index 6bde034..4919193 100644
--- a/themes/pmahomme/css/common.css.php
+++ b/themes/pmahomme/css/common.css.php
@@ -1425,7 +1425,6 @@ div#queryAnalyzerDialog table.queryNums {
 /* server variables */
 #serverVariables {
     table-layout: fixed;
-    width: 100%;
 }
 #serverVariables .var-row > td {
     white-space: nowrap;
```
![screen shot 2017-01-17 at 10 20 58 pm](https://cloud.githubusercontent.com/assets/1443710/22049728/5a96567c-dd03-11e6-80dc-d71c37150c6f.png)

**Comment by poush** [comment]
@ibennetch @OlafvdSpek tried making text center-aligned, see how it looks #12940

**Comment by Fenn-CS** [comment]
Hello @ibennetch and @OlafvdSpek what about adding lines to table to ease tracing since reducing the length does not really look good.

**Comment by OlafvdSpek** [comment]
See my suggestions @ https://github.com/phpmyadmin/phpmyadmin/issues/12899#issuecomment-273412896
