### ISSUE TITLE
quick search box from the top left corner does not work

### ISSUE THREAD

**Issue by domnulnopcea** [phpmyadmin/phpmyadmin#12923]
quick search box from the top left corner does not work

put only 2-3 letter and press enter => it does not show the results that match the criteria

**Comment by ibennetch** [comment]
Hello, could you please tell us which phpMyAdmin version and which browser you are using?

**Comment by domnulnopcea** [comment]
It is not working in your demo account

**Comment by ibennetch** [comment]
Okay, it looks like the problem is actually the pressing of Enter. I'm actually not sure what is meant by "Enter to search all" in the tool tip hint here, so it's not clear to me what the intended behavior is when Enter is pressed. Probably in the end we should catch the press of Enter.

Present in 4.6.6 and current master and tested with Firefox and Chrome.

**Comment by devenbansod** [comment]
Hi @ibennetch, as we know, the navigation can be paged like maybe 30 items on the each page and so on. 
The expected behavior is that If you enter any text in the filter-box, it automatically searches for the items on the page currently displayed in the navigation.
The hint 'Enter to search all' is suggesting that for searching all such nav-pages, user has to explicitly press Enter (which I guess involves an AJAX request to the server to get the results).

**Comment by ibennetch** [comment]
Deven, thanks for that helpful explanation. Guess I should change my testing setup to need more than one page :-)

Certainly something isn't right here, but I wonder whether there's some improvement we might also make to how we notify the user about this feature. Anyway, I'm just kind of thinking out loud.

Thanks.

**Comment by nijel** [comment]
I thought I've fixed that for 4.6.6, see https://github.com/phpmyadmin/phpmyadmin/issues/12786

**Comment by nijel** [comment]
Okay, it does work at 1ae6275, but not in the release, something has to break that again. Somehow I'm unable to discover problematic commit with bisect.

**Comment by nijel** [comment]
Okay, the problematic commit is 7bf85fe817114460de0ad51cf436d1921aef2924.

**Comment by nijel** [comment]
As a workaround you can set
```
$cfg['Servers'][$i]['DisableIS'] = true;
```

**Comment by domnulnopcea** [comment]
are we going to wait weeks for this to come into a new release? 
I stress that this bug is present for a few months now...

**Comment by nijel** [comment]
Unfortunately this problem appeared again due to different bug, I'm sorry about that, but bugs do happen. Unfortunately we don't have manpower to do rigorous QA tests prior to release or to write automated tests for all the features, but certainly any help in this area is welcome. 

BTW: 4.7.0-beta1 with this fix will be probably out today. By using and testing the beta, you can provide us valuable feedback to avoid bugs appearing in the final release.

**Comment by ibennetch** [comment]
As a workaround, it's possible to change the number of databases shown so that they're all on one page. Then don't press Enter when typing the filter. It's not ideal if you have a substantial number of databases, but should work in many scenarios.

I do plan on creating the next release later today, as Michal said, which should fix this.

**Comment by domnulnopcea** [comment]
when should we expect a stable release with this fix?


--
Flavius Nopcea,
CEO, Ubirimi
http://www.ubirimi.com - Fast, most affordable productivity tools

**Comment by ibennetch** [comment]
@domnulnopcea The release of version 4.7.0 is currently scheduled to occur towards the end of March.

**Comment by ibennetch** [comment]
@domnulnopcea The release of version 4.7.0 is currently scheduled to occur towards the end of March.

**Comment by domnulnopcea** [comment]
Hi,

This is just unnaceptable!!!

This bug is present for more than 2 months now and you tell me I have to
wait for one more month now?


What release process is this??? Come on!!!

**Comment by OlafvdSpek** [comment]
> The expected behavior is that If you enter any text in the filter-box, it automatically searches for the items on the page currently displayed in the navigation.

Why is that expected? I don't think it's what users expect.. it's simply what's easy to implement.

**Comment by nijel** [comment]
And what do you think does user expect?

**Comment by domnulnopcea** [comment]
the user expects to search through all the available pages. this is a common pattern in all web applications
