### ISSUE TITLE
TIME columns doesn't allow hour value > 23

### ISSUE THREAD

**Issue by gaaf** [phpmyadmin/phpmyadmin#12948]
### Steps to reproduce
1. Create table with time column
2. Click Insert
3. Enter 24:00:00 for the time
4. 24 is directly turned into 23

### Expected behaviour
The value should be kept and stored as entered. The value is supported by MySQL (and has always been).

### Actual behaviour
Some javascript(?) is changing 24 into 23 without any possibility to prevent this

There is a tooltip near the cursor saying:
> MySQL accepts additional values not selectable by the slider; key in those values directly if desired

But its suggestion is not possible as any entry is directly changed after key release.

This bug makes it impossible to enter or edit records with a time column. It might even cause data loss as it can easily be overlooked that the existing or entered value has been mutilated.

### Server configuration
**Operating system**:
Debian Sid

**Web server:**
Nginx

**Database:**
MariaDB 10.1.21

**PHP version:**
7.0.15

**phpMyAdmin version:**
4.6.6deb1

### Client configuration
**Browser:**
Any, tried:
Chromium 55.0.2883.75
Firefox ESR 45.7.0
Konqueror 4.14.25

**Operating system:**
Debian Sid

**Comment by ibennetch** [comment]
I've looked in to this a bit, and it looks like the timepicker function we use doesn't like an hour value of 24. That's pretty much expected, because an hour value of 24 doesn't make much sense aside from the TIME column type.

However, as you point out, the problem is that the phpMyAdmin validation function doesn't like hour values of 24 through 99 and automatically converts them to 23.

This seems to be checked by isTime() in js/tbl_change.js:L137, but we might instead modify the function call itself at L378.
