### ISSUE TITLE
Field names in Excel exporter

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12951]
Could "Put columns names in the first row" be enabled by default?

**Comment by ibennetch** [comment]
I believe the configuration directive `$cfg['Export']['excel_columns'] = true;` will accomplish what you'd like.

I'm not sure about changing the default in `libraries/config.default.php` though, mostly because I hesitate to change existing behavior. Let's see what the other @phpmyadmin/developers think.

**Comment by nijel** [comment]
I would not mind to change the defaults, on the other side I don't see strong reason to do that...

**Comment by ibennetch** [comment]
This change will be part of 4.7 in a few weeks.
