### ISSUE TITLE
Relation view button: second- or first-level navigation?

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12962]
The Relation view button is currently a level below the main navigation, wouldn't it be simpler to display it in the main navigation bar?

**Comment by jublo** [comment]
There is only so much space on the main navigation, and with narrow browser windows or low resolutions, there are already many items hidden in the overflow. Question being if moving the table relation view up there would be justified. IMO it technically belongs to the table structure, which is why it’s thereunder.

**Comment by nijel** [comment]
I also believe it is correctly placed right now. We really can not put everything to top level navigation.
