### ISSUE TITLE
Version info wrong spacing

### ISSUE THREAD

**Issue by jublo** [phpmyadmin/phpmyadmin#12981]
### Steps to reproduce
1. Open the main page.
2. Take a look at the version info section.

### Expected behaviour
The version info should read like this:

    Version information: 4.8.0-dev, latest stable version: 4.6.6

### Actual behaviour
There are two spacing issues; the version info reads like this:

    Version information: 4.8.0-dev , latest stable version:4.6.6

### Server configuration
**Operating system**: 
macOS 10.12
**Web server:** 
Apache/2.4.25
**Database:**
10.1.21-MariaDB
**PHP version:**
7.0.14
**phpMyAdmin version:**
4.8.0-dev (master)
### Client configuration
**Browser:**
Safari 10.1
**Operating system:**
macOS 10.12

**Comment by ibennetch** [comment]
Good catch.

The missing space is an easy fix, but the extra space before the comma is a bit difficult because there are two `<span>` elements, one is generated at [index.php:387](https://github.com/phpmyadmin/phpmyadmin/blob/QA_4_7/index.php#L387) and the other comes from PMA_current_version() in [js/functions.js:518](https://github.com/phpmyadmin/phpmyadmin/blob/QA_4_7/js/functions.js#L518). 

I don't see anywhere obvious where the spaces are coming from; in particular PMA_current_version() just calls document.createElement() to generate the second \<span\>. One alternative that comes to mind is to change the leading comma to an &mdash;. We'll see what the other @phpmyadmin/developers think about this since I'm not very familiar with this part of the code.

**Comment by jublo** [comment]
I wondered why this function was refactored to use raw document nodes instead of jQuery – while in the first line of the function a reference to $(...) is made (and jQuery is thus present).

**Comment by nijel** [comment]
The same issue was present even before refactoring :-). The reason for that is here: https://github.com/phpmyadmin/phpmyadmin/issues/12764
