### ISSUE TITLE
Show default collation when creating new DB

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12984]
When creating a database:
The Collation dropdown shows a placeholder currently, I think it'd be more useful if it showed the actual default collation that'd be used if you didn't pick one manually.

**Comment by nimeshmora** [comment]
i am a newbie here who is interested in open source development. Can i try one of these issues? (Already forked your master branch & trying to get familiar with the code)

**Comment by ibennetch** [comment]
@nimeshmora Sure, you can work on this issue. It's currently not assigned and no one else has requested to work on it here in the comments, so you're welcome to do so.

**Comment by nimeshmora** [comment]
in index page it shows default server collation. So when creating new DB, you need to  show the default server collation as it shows in index page?

**Comment by devenbansod** [comment]
Hi @nimeshmora the collation dropdown in the create new database form does not have a pre-selected value (it has 'Collation' pre-selected, whose value is '').

The issue requests to show the default server collation pre-selected (which is anyway going to be used by MySQL/MariaDB under the hood, if none is specified) so that user might change it accordingly if he/she wants to.

**Comment by manishbisht** [comment]
I want to work on this issue. I think no one is right now working on this.

**Comment by Fenn-CS** [comment]
I have solved this issue, I will like my code to be merged thank you.
