### ISSUE TITLE
quick search box from the top left corner does not work

### ISSUE THREAD

**Issue by domnulnopcea** [phpmyadmin/phpmyadmin#12992]
quick search box from the top left corner does not work

put only 2-3 letter and press enter => it does not show the results that match the criteria

check my last comment from #12923

**Comment by OlafvdSpek** [comment]
Why have you opened a second issue for this one?

**Comment by domnulnopcea** [comment]
because you closed #12923 by just saying we have to wait for more than a month for an incremental small release...

this bug is present for 2 months now...

**Comment by OlafvdSpek** [comment]
Note I'm not a pMA developer..
I agree having to wait so long isn't good. One option is to install from git but that might also cause more frequent breakage.

**Comment by nijel** [comment]
There was workaround mentioned in that issue: https://github.com/phpmyadmin/phpmyadmin/issues/12923#issuecomment-275052145

And yes, you will have to wait for 4.7.0 to have this fix.

**Comment by domnulnopcea** [comment]
nice approach to fixing issues!!

**Comment by nijel** [comment]
@domnulnopcea sorry, but we can not release every fix immediately. And this definitely is not something severe as security issue or data corruption, which would need extra release on its own.

* The issue is fixed in git, you are free to apply the patch yourself: https://github.com/phpmyadmin/phpmyadmin/commit/20a5e25fe0e4657c19c092209012d186b33c9d10
* There is existing workaround mentioned in https://github.com/phpmyadmin/phpmyadmin/issues/12923#issuecomment-275052145
* As @OlafvdSpek mentioned you can use Git version meanwhile as well which does fixes this and many other bugs.
* If none of the above works for you, you will have to wait for next release or hire somebody who will prepare patched release for you using patch mentioned above.
