### ISSUE TITLE
designer not working (kaspersky, CSP)

### ISSUE THREAD

**Issue by rogerqiluo** [phpmyadmin/phpmyadmin#13018]
### Steps to reproduce
1. select a database with multiple tables
2. open "Designer" view
3. the tables are locked at left panel and cannot be moved

### Expected behavior
they should be able moved 

### Actual behaviour
not able to move the tables and there is a gif file running on the left top corner near the recent.

### Server configuration
**Operating system**:
AWS EC2 ubuntu virtual server
**Web server:**
ubuntu instance
**Database:**
MySQL
**PHP version:**
PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )

**phpMyAdmin version:**
(4:4.5.4.1-2ubuntu2)
### Client configuration
**Browser:**
firefox
**Operating system:**
windows 10 64bit

**Comment by nijel** [comment]
phpMyAdmin 4.5 is no longer supported, can you please reproduce your issue with some recent version?

**Comment by rogerqiluo** [comment]
Thank you so much for the reply. I upgrade phpmyadmin to 4.6 but same issues exist:

Tables cannot be moved in designer windows

The running clock sign always there on the left top corner.

The following is a screenshot for these two issues. Please help. Thanks a lot.

[cid:image001.jpg@01D28B70.DD847850]

**Comment by ibennetch** [comment]
Unfortunately, Github strips attachments from email replies. If you'd like to post a screenshot, you can do so from the web interface at https://github.com/phpmyadmin/phpmyadmin/issues/13018.

**Comment by rogerqiluo** [comment]
Thank you so much for the prompt reply. 
The running clock sign on the top left corner is running all the time from start to close.
The tables in the designer view are not able to move.

Thanks a lot for the help.
![designer view](https://cloud.githubusercontent.com/assets/25885266/23137107/c649ea7e-f765-11e6-8d29-81a068340fc3.jpg)
![designer view](https://cloud.githubusercontent.com/assets/25885266/23137124/e2952e32-f765-11e6-921e-29193fec04fd.jpg)

**Comment by rogerqiluo** [comment]
HIt the wrong button. not meant to close the issue.

**Comment by rogerqiluo** [comment]
Please  help. Thanks.

**Comment by rogerqiluo** [comment]
Thank you for the prompt reply. I resubmitted the screenshot via web and hope it works. Otherwise, please let me know.

I tried to purge and reinstall phpmyadmin but no vail. Please help.

Thanks a lot.

Best,

Roger

**Comment by nijel** [comment]
Do you get any javascript errors? You can find them in developer tools, AFAIR it can be activated by F12 in Edge...

**Comment by rogerqiluo** [comment]
No. I checked the debugger from developer tools but no error reported.

**Comment by udan11** [comment]
@rogerqiluo Can you still reproduce this bug?

I have been trying using Microsoft Edge as you were in the screenshots provided, but everything works fine for me. Do you have any extensions installed?

**Comment by dazzyt** [comment]
I encountered this problem and spent ages reinstalling/reconfiguring thinking it was a problem after upgrade of ubuntu. However it turns out to be with Kaspersky Internet Protection, specifically its Content Security Policy handling ("content_security_policy": "default-src 'self' style-src 'self' 'unsafe-inline';" ).

The browser dev console list numerous lines like this:
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'nonce-F13E78C13597C541A0870BE98CC0B750' http://gc.kis.v2.scr.kaspersky-labs.com ws://gc.kis.v2.scr.kaspersky-labs.com". Either the 'unsafe-inline' keyword, a hash ('sha256-Znx9+G9zA+tuD8Jhp366cVvHMKX3f6akSB6VwBQDw0o='), or a nonce ('nonce-...') is required to enable inline execution.....

I had to disable it via (Kaspersky Settings > Additional > Network > Traffic Processing > Inject Script) to get the designer page working as intended but doing so also disables a number of browser security components within Kaspersky!

At the moment I have to disable the KIS setting when needing to use the designer and then enable it after!

**Comment by nijel** [comment]
It will break more things than just designer, we even have a FAQ for this: https://docs.phpmyadmin.net/en/latest/faq.html#i-get-errors-about-violating-content-security-policy

**Comment by williamdes** [comment]
@dazzyt @rogerqiluo Can you still reproduce this issue using 4.9.2 ?

**Comment by williamdes** [comment]
Could not reproduce, if you can please post here.
