### ISSUE TITLE
There is no Arabic locales

### ISSUE THREAD

**Issue by saidbakr** [phpmyadmin/phpmyadmin#13034]
### Steps to reproduce
1. Download phpMyAdmin-4.6.6-all-languages.zip from the official website
2. Install it on web accessible folder on the Web server.
3. Access the installation via http://localhost/pma
4. Login form languages list does not contain Arabic or "عربي". Also on the home page at the language list Arabic is not found.

### Expected behaviour
I expect the Arabic language to be available in the languages list.

### Actual behaviour
There is no Arabic in the language list, also there is no `ar` folder in locale folder of the phpmyadmin.

### Server configuration
**Operating system**: Windows10 64bit

**Web server:** Nginx 1.10.13

**Database:** MySQL

**PHP version:** 7.1.2

**phpMyAdmin version:** 4.6.6

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10.

**Comment by ibennetch** [comment]
This is intentional; the current translation status is only about 34%, so it's excluded from the download file.

Languages that have a low percentage of translated phrases are not included in the download package to avoid introducing confusion over messages that are not translated.

Your contribution would be welcome; there's still time to translate strings for inclusion in 4.7 which is scheduled for release in approximately one month.

You can learn more about our translations at https://www.phpmyadmin.net/translate/
