### ISSUE TITLE
Replacing Google reCAPTCHA with Invisible reCAPTCHA

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#13086]
Google have recently announced their Invisible reCAPTCHA that automatically verify the user is human or bot.

Official Link: https://www.google.com/recaptcha/intro/invisible.html
Implementation Guide: https://developers.google.com/recaptcha/docs/invisible

**Comment by nijel** [comment]
Certainly patches are welcome to upgrade. I don't think it makes sense to provide both options.

**Comment by KashyapCKotak** [comment]
I am facing a issue with recaptcha v2 and invisible recaptcha that entered captcha is always wrong. Can anyone please help me over this?

**Comment by chrcoluk** [comment]
This seems to enforce invisible recaptcha now, and using the I am not a robot button no longer works. 

Instead this is displayed.

"This site key is not enabled for the invisible captcha."

Since invisible is weaker, I would like the normal I am not a robot still able to work so please add an option for this thanks.
