### ISSUE TITLE
phpMyAdmin show phpsyntax in Db and  User field

### ISSUE THREAD

**Issue by hbfl** [phpmyadmin/phpmyadmin#13230]
### Steps to reproduce
1.  
![phpmyadmin1](https://cloud.githubusercontent.com/assets/17593122/25567524/ccc02ad8-2def-11e7-85bb-39780805ceff.png)

  please show the picture 
this problem comes with version 4.0.10.17 up to 4.0.10.20

in 4.0.10.16 it shows correct

I maintend this version on 'eisfair' for MySQL 5.1 series 

OS Linux
Apache2.4
php 2.6.29

firefox

**Comment by devenbansod** [comment]
Hi @hbfl the phpMyAdmin version you are using is not supported anymore (though I understand that you are stuck with it because of your MySQL version).
This is a duplicate of #12483, and the fix has been released as a part of phpMyAdmin version 4.6.5. 

You may want to update to the latest version to utilize the fix.

**Comment by hbfl** [comment]
so sorry, 4.0.10.20 is a actual stable release and labled as active branch.

**Comment by hbfl** [comment]
OK, I roll back   6cbbcdb  from  12 Jul 2016 and it works for me. Thanks for the point.
