### ISSUE TITLE
Can't create fulltext index on multiple columns

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13303]
![pma](https://cloud.githubusercontent.com/assets/2218936/26488637/7ccfd144-4204-11e7-9a03-38c7aee5e707.PNG)

The FullText icon is missing..

**Comment by made2591** [comment]
@OlafvdSpek can you explain the problem? Maybe I can handle this but I'm not sure I correctly understood!

**Comment by OlafvdSpek** [comment]
What part do you not understand?

**Comment by made2591** [comment]
What is FullText icon? XD I know it sounds stupid but I mean: where are you in the screen? what do you expect? Are you talking about a ui-only bug or something else?

**Comment by OlafvdSpek** [comment]
On the Structure tab, you can select multiple columns and then create an index on them by clicking the Primary Key, Unique Key or Index buttons. The FullText button isn't in the line after "With selected:" though.

**Comment by made2591** [comment]
thank you! I will try to solve the problem in the day, but I am a newbiew XD as you should have already understood

**Comment by made2591** [comment]
Ok, understood. FullText is missing, lol. I'll go throught it.

**Comment by cs-m3rlin** [comment]
Hi @made2591, 
are you still working on this issue? If no, I would take it.

**Comment by made2591** [comment]
I worked on it a little bit, but I'm far from finding a sol...I think it is more difficult than you expected. If you want to re-assign, please go ahead! I will go in States tomorrow, and for 2 weeks I will not work of any open projects. Sorry for delay in feedback!

**Comment by cs-m3rlin** [comment]
Hi @OlafvdSpek 
I think @made2591 is right by saying, this is a bigger issue.
FullText Indices can only be created within a table configured with the storage engine MyISAM. InnoDB does not support this feature, thus the icon is not displayed. If you change the engine, the icon will be displayed.

I think, the real bug is that the FullText feature is being displayed within the columns (see screen) also if the storage engine does not support it, e.g. InnoDB.
![fulltext-column](https://user-images.githubusercontent.com/30618202/29124074-1bf0b84e-7d18-11e7-900d-c63eaef01160.PNG)

Do you agree?

**Comment by OlafvdSpek** [comment]
https://dev.mysql.com/doc/refman/5.6/en/innodb-fulltext-index.html

**Comment by cs-m3rlin** [comment]
Okay, my source was obviously outdated. 
I will have a look

**Comment by ankitjain28may** [comment]
@nijel I would like to work on this issue if anyone isn't active on this, can you please assign this to me ?

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/13716
