### ISSUE TITLE
No quotes when field type is int

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13326]
https://demo.phpmyadmin.net/QA_4_9/tbl_select.php?db=sakila&table=actor

    SELECT * FROM `actor` WHERE `actor_id` = test LIMIT 0, 25 :(

I think it should put quotes around test..

**Comment by OlafvdSpek** [comment]
Because otherwise it's interpreted as a column name.

**Comment by OlafvdSpek** [comment]
Why was this closed?

**Comment by williamdes** [comment]
Okay, now a screenshot is a minimum, I found a way to reproduce this.
And the real issue is that you should no allow the user to enter a string, like it is done on the Insert page
## Search
![Search](https://user-images.githubusercontent.com/7784660/55295290-ab7d4d80-540b-11e9-9ad6-86f178f54ff9.png)
## Insert
![Insert](https://user-images.githubusercontent.com/7784660/55295298-b506b580-540b-11e9-8e30-03198ae6f063.png)

**Comment by OlafvdSpek** [comment]
I think this isn't just an UI issue. Backend should also validate / quote.

**Comment by gurrrung** [comment]
Can someone help me reproduce this error?

**Comment by williamdes** [comment]
@gurrrung 

## First create a table with a int type
```sql
CREATE TABLE `test-13326` (
  `abc` int(11) NOT NULL
) ENGINE=InnoDB;
```

## Go to "Search"

Fill the field with a string and submit

>  it's interpreted as a column name.


## Expected behavior

Add quotes or forbid using non integer values
