### ISSUE TITLE
mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given

### ISSUE THREAD

**Issue by thomasmeeus** [phpmyadmin/phpmyadmin#13399]
### Steps to reproduce
1. install latest phpmyadmin release (4.7.1)
2. open phpmyadmin and login to a database

### Expected behaviour
Phpmyadmin opens the correct database

### Actual behaviour
PHP error:
```
Warning in ./libraries/dbi/DBIMysqli.php#556
 mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given

Backtrace

./libraries/dbi/DBIMysqli.php#556: mysqli_real_escape_string(
boolean false,
string '_',
)
./libraries/DatabaseInterface.php#2735: PMA\libraries\dbi\DBIMysqli->escapeString(
boolean false,
string '_',
)
./libraries/navigation/nodes/Node.php#437: PMA\libraries\DatabaseInterface->escapeString(string '_')
./libraries/navigation/NavigationTree.php#289: PMA\libraries\navigation\nodes\Node->getData(
string 'databases',
integer 0,
string '',
)
./libraries/navigation/NavigationTree.php#847: PMA\libraries\navigation\NavigationTree->_buildPath()
./libraries/navigation/Navigation.php#45: PMA\libraries\navigation\NavigationTree->renderState()
./libraries/Header.php#433: PMA\libraries\navigation\Navigation->getDisplay()
./libraries/Response.php#260: PMA\libraries\Header->getDisplay()
./libraries/Response.php#273: PMA\libraries\Response->_getDisplay()
./libraries/Response.php#432: PMA\libraries\Response->_htmlResponse()
PMA\libraries\Response->response()
```

libraries/DatabaseInterface.php#2735 appears to return false instead of the database connection link. 

Perhaps this is related to the fact that the remote mysql service I'm connecting to is version 5.1?

### Server configuration
**Operating system**:
RHEL7.3
**Web server:**
httpd-2.4.6
**Database:**
mariadb-10.1
**PHP version:**
PHP 5.6.30
**phpMyAdmin version:**
4.7.1
### Client configuration
**Browser:**
All browsers
**Operating system:**
All OS.

**Comment by ard1998** [comment]
> PHP error:

if its an php error, it isn't a phpmyadmin error, please check around line 556 in DBIMysqli.php of functions that use this function for programming errors.

i think this one can be closed.

**Comment by ibennetch** [comment]
It probably is because of your remote version being 5.1 — phpMyAdmin 4.7.1 requires MySQL version 5.5 or newer, regardless of whether it's for a local or remote connection.

You can download phpMyAdmin 4.0 from https://www.phpmyadmin.net/downloads/, except that won't work with PHP version 5.5 or greater. Although it's not officially supported any longer, it's still available. Because you've got a relatively current PHP version but the MySQL server is rather outdated, I don't have any good suggestion for what solution would work best for you. Upgrading your MySQL server seems best, but you might be able to run an older phpMyAdmin on that (or a similarly-old) system, then connect to phpMyAdmin via the network.

Unfortunately, I don't think there's much we can do about this.
