### ISSUE TITLE
LIMIT not working when using JOIN

### ISSUE THREAD

**Issue by manawk** [phpmyadmin/phpmyadmin#13401]
### Steps to reproduce
I want to do a join between tables with a limit
ex: SELECT * FROM orders JOIN orders_item USING (orders_id) LIMIT 0,10

### Expected behaviour
I was expecting to get only the result within the limit, so 10 results max

### Actual behaviour
The limit is not considered, all the results are listed.
It works normal when the request is  not run in phpmyadmin

Note: The LIMIT is taken in count in phpmyadmin when I am NOT using a JOIN

### Server configuration
**Operating system**: Ubuntu
**Web server:** Apache/2.4.18 (Ubuntu)
**Database:** MySQL
**PHP version:** 7.0.18
**phpMyAdmin version:** 4.5.4.1deb2ubuntu2

### Client configuration
**Browser:** Chrome
**Operating system:** Windows 7.0

**Comment by KeerthanaRatna** [comment]
Hi manawk,
It seems that it is not the problem with the JOIN clause. When I tried LIMIT with JOIN clause in another way like  
SELECT *  FROM orders JOIN orders_item  ON orders.orders_id = orders_item.orders_id LIMIT 10,
It's working properly. I think the problem is with USING clause. The only different in the output when using ON clause is that it returns the orders_id column twice, but the USING clause usually returns the order_id column only once in the output, not twice.

**Comment by williamdes** [comment]
@manawk Try version ```4.8.1```
Your query works fine on ```5.0.0-dev```

**Comment by williamdes** [comment]
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

Using demo servers.
Query:
```sql
SELECT * FROM City JOIN CountryLanguage USING (CountryCode) LIMIT 0,10
```

https://demo.phpmyadmin.net/QA_4_8/db_sql.php?db=world
https://demo.phpmyadmin.net/master-config/db_sql.php?db=world

**Comment by williamdes** [comment]
@manawk @KeerthanaRatna I can not reproduce this issue.
Please comment or re-open if you can reproduce on last versions.
