### ISSUE TITLE
$_COOKIE variable has been set to empty when 'pmaCookieVer' empty

### ISSUE THREAD

**Issue by marginchan** [phpmyadmin/phpmyadmin#13480]
### Steps to reproduce
1、FILE and LINE
https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/common.inc.php
line: 253

2、hole $_COOKIE variable was set to empty,  very coarse behaviour!
when develop by twice， I need $_COOKIE, I have some variables in it!

can be this:

```
if (isset($_COOKIE)) {
    if (! isset($_COOKIE['pmaCookieVer'])
        || $_COOKIE['pmaCookieVer'] != $pma_cookie_version
    ) {
        // delete all cookies
        foreach ($_COOKIE as $cookie_name => $tmp) {
            // We ignore cookies not with pma prefix
            if (strncmp('pma', $cookie_name, 3) != 0) {
                continue;
            }
            unset($_COOKIE[$cookie_name]);
            $GLOBALS['PMA_Config']->removeCookie($cookie_name);
        }
        $GLOBALS['PMA_Config']->setCookie('pmaCookieVer', $pma_cookie_version);
    }
}
```

**Comment by nijel** [comment]
Can you please clarify why you think this is a problem? This code is used when cookies from older phpMyAdmin version are detected and in such case our code should not use them as they are incompatible.

**Comment by marginchan** [comment]
I  developed third code and inject into phpMyAdmin
my code will setcookie for some perpose,  but the code above will delete my cookie that I set.

so I  hope phpMyAdmin just delete $_COOKIE['pma****']

**Comment by nijel** [comment]
This code will delete it only in case there are cookies from older phpMyAdmin version. So this can happen at most once after upgrade...

**Comment by charlesmulder** [comment]
Hi Nijel.

We are making use of [Signon Authentication](https://docs.phpmyadmin.net/en/latest/setup.html#signon-authentication-mode). Since upgrading to phpMyAdmin 4.7.5 we have been experiencing an issue where phpMyAdmin considers authenticated users to be not authenticated on [the first signon authentication redirect](https://github.com/phpmyadmin/phpmyadmin/blob/STABLE/examples/signon.php#L38). Subsequent redirects work fine. 

I have been looking at the code and the problem seems to be that [all cookies are cleared in common.inc.php](https://github.com/phpmyadmin/phpmyadmin/blob/STABLE/libraries/common.inc.php#L251), whilst later in the process [AuthenticationSignon.php](https://github.com/phpmyadmin/phpmyadmin/blob/STABLE/libraries/plugins/auth/AuthenticationSignon.php#L95) checks to see that the _SignonSession_ cookie is set, which of course it isn't, cause the cookies have been cleared.

My current workaround is to set a pmaCookieVer cookie to 5 in [signon.php](https://github.com/phpmyadmin/phpmyadmin/blob/STABLE/examples/signon.php) before the redirect. 

Feels like a bit of a hack. Thoughts?

Thanks,
C

**Comment by nils-van-zuijlen** [comment]
@charlesmulder Seems like you notified the bad person 😁

**Comment by charlesmulder** [comment]
Apologies. Thanks for letting me know. Rectified.

**Comment by charlesmulder** [comment]
@nijel 

Could I take a stab at fixing it?

**Comment by nijel** [comment]
@charlesmulder Feel free to look at this.
