### ISSUE TITLE
Edit index Column alignment issue

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13513]
The Column column is right-aligned but the header is left-aligned.

![pma](https://user-images.githubusercontent.com/2218936/28457882-0c48c9e6-6e08-11e7-9ed1-b930635f596e.PNG)

**Comment by KeerthanaRatna** [comment]
Hi Olaf van der Spek,
Can you tell me the phpMyAdmin version in which you got this behavior, because it's working properly in 4.8.0-dev. In 4.8.0 version the Column column is left-aligned and the header is  also lift-aligned.
![image](https://user-images.githubusercontent.com/23234786/28520592-c793e23a-708d-11e7-893c-b61aaae7cb2e.png)

Is that the behavior you expect?

**Comment by OlafvdSpek** [comment]
Resize the window (horizontally)

**Comment by KeerthanaRatna** [comment]
Thank you. You are right.

**Comment by OlafvdSpek** [comment]
So the issue is in both Add index and Edit Index.

**Comment by Timmarus** [comment]
Is this still open?

**Comment by KeerthanaRatna** [comment]
My commit is working fine for both Add index and Edit Index. Can anyone check it? I attached the screen shot of the working module here.
![image](https://user-images.githubusercontent.com/23234786/30278514-26600724-9728-11e7-8e5f-881708e78986.png)

**Comment by Morerice** [comment]
Both **Add** and **Edit** fixed. This is the result of applying @KeerthanaRatna changes.
![selection_024](https://user-images.githubusercontent.com/11156828/30520721-145de7a4-9bb4-11e7-8628-1f10202aebd1.png)

**Comment by mauriciofauth** [comment]
Hi, @KeerthanaRatna.
Create a branch containing your changes and open a pull request.
See [CONTRIBUTING.md](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md).
