### ISSUE TITLE
Error syntax highlight with this query

### ISSUE THREAD

**Issue by bulletxt** [phpmyadmin/phpmyadmin#13541]
Doing this query in attachment makes   syntax check go mad and it's also unable to execute query.

[test.txt](https://github.com/phpmyadmin/phpmyadmin/files/1187169/test.txt)

**Comment by nijel** [comment]
The problem is that SQL parser doesn't handle aliases without AS keyword. According to MySQL docs this is possible, but discouraged: https://dev.mysql.com/doc/refman/5.7/en/select.html#idm139723195268992

The parser also doesn't seem to handle aliases on case expression at all.

Reproducer on SQL parser:

```
$ ./bin/lint-query --query 'select 1 name'
#1: Unrecognized keyword. (near "name" at position 9)
$ ./bin/lint-query --query 'select case  when 1 > 0 then "x" else "y" end AS name'
#1: Unrecognized keyword. (near "AS" at position 46)
#2: Unrecognized keyword. (near "name" at position 49)
$ ./bin/lint-query --query 'select case  when 1 > 0 then "x" else "y" end name'
#1: Unrecognized keyword. (near "name" at position 46)
```

I've created following issues to track these problems:

* https://github.com/phpmyadmin/sql-parser/issues/162
* https://github.com/phpmyadmin/sql-parser/issues/161
