### ISSUE TITLE
Feature suggestion: server alias

### ISSUE THREAD

**Issue by leggiero** [phpmyadmin/phpmyadmin#13558]
Would be really nice to allow optionally the use of alias for server in the `phpmyadmin.config.inc.php` file, like:

```
$cfg['Servers'][$i]['auth_type'] = 'config';
/* Server parameters */
$cfg['Servers'][$i]['alias'] = 'Dev Server';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['user'] = 'root';
```

That way, only if specified, the alias will be displayed in the Current Server dropdown instead of `host:port (user)` label.

### Steps to reproduce
1. Set multiple servers in the configuration
2. Open the homepage of phpMyAdmin
3. Look at the Current Server dropdown in the Navigation Panel

### Expected behaviour
See the server label in the dropdown, like: `Dev Server`

### Actual behaviour
The text for each server is `host:port (user)` like: `localhost:3306 (root)`

**Comment by nijel** [comment]
It's already there, just called [$cfg['Servers'][$i]['verbose']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_verbose).

**Comment by slim16165** [comment]
> It's already there, just called [$cfg['Servers'][$i]['verbose']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_verbose).

Hi Nijel,
Thanks in advance for your help. I'm going to try if this solve my problem.

I also apologize in advance because I'm a [diagnosed OCD] so please don't hate me because being perfectionist is in my personality.

If PHPMyAdmin offer a feature which is a label / an alias for a server name. Which is visible from the UI and it calls if "verbose". We **should** consider it a bug. At least if the software engineer is not an opinion, as developers, we should not accept such a violation of the [software readability good practice](https://www.google.it/search?q=software+engineer+speaking+name+variable). 

What do you think? Is it so terrible to change that name for the PHPMyAdmin dev?


(https://en.wikipedia.org/wiki/Obsessive%E2%80%93compulsive_disorder)
