### ISSUE TITLE
Allow custom number of rows to be inserted

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13578]
### Steps to reproduce
1. Login with username password
2. Select any database
3. Select any table
4. From top navigation select "Insert"

### Expected behaviour
We can add custom number of rows

### Actual behaviour
Bound to insert specific number of rows
![enhs](https://user-images.githubusercontent.com/22341750/29076652-c68f2376-7c73-11e7-9d14-b39d88e37b8c.png)

**Comment by codehimanshu** [comment]
What if we add an Input field of Number Type? Seems to work fine with minor changes on my local.
@ibennetch any suggestions? If it seems good, please assign this to me.

![screenshot from 2017-08-09 22-52-58](https://user-images.githubusercontent.com/14791631/29134788-862057fa-7d55-11e7-858e-8bfe6b9c0b75.png)

**Comment by ibennetch** [comment]
@codehimanshu Sure, that seems like a good solution to me. Go right ahead.

**Comment by ibennetch** [comment]
Due to how the Github interface is, I can't directly assign the issue to you, but for our workflow, commenting here is enough.

**Comment by OlafvdSpek** [comment]
I think this is a bad interface, you shouldn't have to think of the number of rows you want to insert at that moment.
The Insert Row form should have an interface (button / link) to add an additional row.

**Comment by codehimanshu** [comment]
@OlafvdSpek That would be far better approach. Shall I go ahead for it by adding a "Add Row" button in the end or the numeric input button is okay for now?

**Comment by OlafvdSpek** [comment]
We should go for far better shouldn't we?

**Comment by ibennetch** [comment]
I think the best solution here would be to change the text to add __ additional rows where the blank is a number input field. I'm not sure what the exact text should be, because if we say "Add __ additional rows" that might confuse people in to thinking they're adding that _to the database_ instead of to the insert form.

Maybe "Add __ rows to this form"?

This would be a slight change from the current behavior where one can add or remove rows; under the new functionality a user can only add rows (and not take them away). I think that should satisfy the point Olaf is making about now having to know in advance or count how many you actually need.

To be clear, though, the current interface doesn't really require you to know in advance; you just have to make the number bigger than the current number (if it's set to 5, you wouldn't want to change it to 1 because anything entered in those fields disappears). So i don't think it's a bad interface, but it could stand to be improved a bit to help prevent data loss.

**Comment by OlafvdSpek** [comment]
Ah, I misunderstood the feature. I'm still not sure it's the right solution though.
Wouldn't it be far simpler to ditch the entire current interface and to have a form to insert a single row, that returns to the same page to you can insert another row, one at a time, if you want?

**Comment by codehimanshu** [comment]
That would be very disgusting when it comes to adding 5-6 rows. User will
have to submit and wait after each row. Instead the numeric input field is
better approach. It will also facilitate the user to remove any extra rows
if he wants by entering a smaller value in input field.

Changing the current select drop-down to input field seems to do the work.
Else we can have a "add row" button at end, and a delete row button along
every row form. This will allow user to delete specific form as well as add
as many he wishes to add.


Thanks and Regards

Himanshu Agrawal
+91-9654379609
himanshuagrawal1998@gmail.com

******************************
Please do not print this mail until necessary and save paper.

**Comment by OlafvdSpek** [comment]
>  User will
have to submit and wait after each row.
