### ISSUE TITLE
Copied table data add "1" after column name which had order by parameter

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13727]
### Steps to reproduce
1. Select any table 
2. order by any column
3. from menu/option in bottom on table select "copy to clipboard"

### Expected behaviour
"1" do not depict the why it is used for
Maybe we can add [Asc] [Desc] or anything else or  nothing

### Actual behaviour
"1" is added after column name which had order by parameter
![copy](https://user-images.githubusercontent.com/22341750/31399951-93aa39c2-ae0b-11e7-9219-265f1907470d.png)

### Server configuration
Online demo

**phpMyAdmin version:** 4.7.4

### Client configuration
**Browser:** 61.0.3163.100 (Official Build) (64-bit)

**Operating system:** Ubuntu 16.0.4 LTS

**Comment by guilherme-gmonteiro** [comment]
I Will work on this!

**Comment by acekyd** [comment]
I think there's been a misunderstanding and the fix on #13736 might not be right as well. 

The `1` that is added is used to represent which columns that are being ordered. so in a case of `ORDER BY column1, column2 ASC`, these columns are numbered to know which, removing them or changing to whether ASC or DESC might not work for that. Looking forward to hearing your thoughts on this @nijel @anantjain6

**Comment by anantjain6** [comment]
@acekyd I'm also not sure that what can be best way
above table we can add line of text like "order by column1, coulmn2 desc"

**Comment by akritianand** [comment]
Hello. I've just submitted a pull request. The column which is sorted shows [Asc/Desc] next to it. The ORDER BY column name does show in the pasted text already.

**Comment by shucon** [comment]
@akritianand I was already working on this issue , and have already submitted a PR as mentioned above :)

**Comment by ibennetch** [comment]
i think that, because of the triangle icon, we don't need ASC and DESC.

I believe the 1 originally was there as a hint that there's a tool tip there, so the user can hover over for help. The question mark help icon may be a better fit here, and doesn't have to be in a particular column header, either, though I don't have a better idea other than hanging off the side of the table header to the far right of the existing columns.

**Comment by acekyd** [comment]
I agree with @ibennetch. We don't need ASC and DESC because of the triangle icon. 

But I still think we are overlooking the role the "1" is playing there. Once again, the 1 shows the ORDER BY status. So if you are ordering by 2 different columns, it numbers them.

I think the best solution here is to hide the "1" whenever you are ordering by less than 2 columns. Otherwise, it shows the numbering across.

**Comment by ibennetch** [comment]
Oh, right, I had forgotten for a moment that it shows the number of ordered by columns. I agree with @acekyd about the desired behavior.

**Comment by shucon** [comment]
@nijel this issue is pending from a long time.
Your views on the same?

**Comment by scarletphoenix** [comment]
This issue still up for fixing?
