### ISSUE TITLE
$cfg['AllowUserDropDatabase'] does not work at all

### ISSUE THREAD

**Issue by COLABORATI** [phpmyadmin/phpmyadmin#13782]
I am setting in config.php:
```php
$cfg['AllowUserDropDatabase'] = false;
```
but db users are still able to drop databases or tables - this setting does not change anything in the frontend and seems to be broken.

**Comment by ibennetch** [comment]
Hi, I just tested this and can't reproduce it. I checked on the Operations tab for that specific database and also the Databases tab and wasn't able to see any drop option when logged in as a normal user.

What sort of permissions do your users have, both global and for their specific databases?

**Comment by williamdes** [comment]
For me this works perfectly when user is not considered "a super user".
@COLABORATI can you confirm that your user can not execute `SELECT 1 FROM mysql.user LIMIT 1`

If you execute `GRANT SELECT ON mysql.user to myuser@'%'` this will allow your user to DROP databases with `myuser` because PMA thinks that the account is a super-user.

https://github.com/phpmyadmin/phpmyadmin/blob/447f7ae3d123557b5e97bec84ab6cb44a567ebeb/libraries/classes/DatabaseInterface.php#L2292-L2294

**Comment by williamdes** [comment]
@COLABORATI ?

**Comment by williamdes** [comment]
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.
