### ISSUE TITLE
Unable to login to PhpMyAdmin without any error | Yahoo Small Business hosting Service

### ISSUE THREAD

**Issue by akshaybajpei92** [phpmyadmin/phpmyadmin#13872]
### Steps to reproduce
1. I have logged in to my Yahoo Small Business panel
2. Made a MySql database, and created a paasword
3. Then installed the PhpMyAdmin to a directory and tried to login to phpmyadmin, with the same credentials, it showed no error and redirected me to the same login page. Just this time the URL has tokenid also.. 

### Expected behaviour
I must have seen my MYSQL database, and phpmyadmin must have logged in properly

### Server configuration

**Web server**: Dont know!

**Database**: MySql

**PHP version**: 5.4

**phpMyAdmin version**: Don't know!

### Client configuration
**Browser**: Chrome

**Operating system**: Windows

**Comment by nijel** [comment]
Probably better ask your hosting support. As you're on PHP 5.4, you're certainly running some old phpMyAdmin version no longer supported by us.

AFAIK this can also happen if phpMyAdmin was accessed over https and then login using http fail.

**Comment by akshaybajpei92** [comment]
Ya nijel, I have asked hosting support but they said they don't provide any support for PhpMyAdmin, and for support related to it, so must contact PhpMyAdmin support, so I am here...

**Comment by nijel** [comment]
Where did you get phpMyAdmin from? What phpMyAdmin version do you use? Please note that we do not support any version supporting PHP 5.4.

**Comment by ibennetch** [comment]
Unfortunately, it's been my experience that many people have difficulty with using phpMyAdmin with Yahoo! hosting. I'm not sure whether that's because they modify the phpMyAdmin they provide somehow or some other quirk of their infrastructure.

I do remember that a few years ago they were including a version that had modifications that we didn't know anything about, so we couldn't fix the problem, but Yahoo! wasn't supporting it, either, even though their modifications were causing the problem. That could have changed as it's been a few years since I've looked in to it.

Anyway, if they're providing phpMyAdmin, you might try installing your own to a different folder of your web root to see if you get any better result.

**Comment by williamdes** [comment]
I bought one month of Yahoo small business hosting service.
Going to have serious testing soon !

**Comment by williamdes** [comment]
I tested and had no issues, everything works great (phpmyadmin & mysql) at `Yahoo Small Business hosting Service` (except some things that are not related to phpMyAdmin..).
@akshaybajpei92 Please try the latest version of phpMyAdmin and confirm before end of this week (I will cancel my hosting plan)

To find the phpMyAdmin version you are using browse `https://domain.xyz/phpmyadmin/changelog.php` (example URL)

**Comment by williamdes** [comment]
11$ for no error or issue :smile: 
Closing.
