### ISSUE TITLE
White Screen Of Death - PMA favicon appears but PMA itself forbidden

### ISSUE THREAD

**Issue by benqzq** [phpmyadmin/phpmyadmin#13953]
I'm experiencing a WSOD when trying to access PHPmyadmin on Ubuntu LEMP. Here's how to reproduce:

On a pure virtual machine with Ubuntu 16.04 xenial, I've installed LEMP:

    apt-get update -y
    apt-get upgrade nginx mysql-server php-fpm php-mysql php-mbstring php-mcrypt -y
    /etc/init.d/php*-fpm restart && systemctl restart nginx.service

All LEMP conf is default.

On the LEMP I've installed PHPmyadmin:

    wget -P /var/www/html https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.zip
    find  /var/www/html/ -type f -iname '*phpmyadmin*.zip' -exec unzip {} \;

I then added a conf: `nano /etc/nginx/sites-available/phpmyadmin.conf`:

    server {
    	root /var/www/html/phpmyadmin;
    	server_name 46.101.58.187 phpmyadmin;
    
    	location / {
    		index index.php index.html index.htm fastcgi_index;
    		try_files $uri $uri/ /index.php?$args;
    	}
    
    	location ~ \.php$ {
    		fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
    		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    		include fastcgi_params;
    	}
    
    	listen 80;
        listen [::]:80;
    }

I then enabled the conf:

    ln -s /etc/nginx/sites-available/phpmyadmin.conf /etc/nginx/sites-enabled/

I then changed permissions as usual:

    chown -R www-data:www-data /var/www/html/
    chmod -R a-x,a=rX,u+w /var/www/html/

I then restarted the server:

    /etc/init.d/php*-fpm restart && systemctl restart nginx.service

Yet, when navigating to `MY_IP_ADDRESS/phpmyadmin`, I have a WSOD. The PMA favicon is there, but the HTML source contains almost nothing.

That's the main error I have in the Nginx error log:

> directory index of "/var/www/html/phpmyadmin/" is forbidden

I also had this when I did some tries:

> FastCGI sent in stderr: "Primary script unknown" while reading
> response header from upstream

The first error appears 90% of the time. I found no good solutions for both.

---

What might cause the WSOD situation and error? I just fail miserably to find the problem.

**Comment by OlafvdSpek** [comment]
How is this a pMA bug? Sounds like a nginx conf error..
Tried /phpmyadmin/index.php?

**Comment by benqzq** [comment]
Didn't know this option. I can indeed access PMA from `MY_IP/index.php` but not from `MY_IP/index.php`.

**Comment by ibennetch** [comment]
I agree with OlafvdSpek that this sounds like an nginx configuration problem.

If you've put the phpMyAdmin directory inside the nginx web root (it looks to me like you have), you don't need to create the configuration file in sites-available. That likely will lead to some type of conflict where the webserver gets confused; either move phpMyAdmin outside the web root or remove the second configuration file you've made (that's what I would do and just leave the phpMyadmin files in the web root directory).

The message about not being permitted to show the directory index makes sense because when you enter the full file name it works, so you should furthermore either configure your webserver to use index.php as a default document or use the full filename when loading phpMyAdmin.
