### ISSUE TITLE
Bug sorting rows

### ISSUE THREAD

**Issue by zezettepglc** [phpmyadmin/phpmyadmin#13955]
### Steps to reproduce
1. click on table name
2. click on the col name (to sort rows)

### Expected behaviour
Tell us what should happen
rows sort

### Actual behaviour
Tell us what happens instead
rows not sort, show insert tab

### Server configuration
**Operating system**: Linux 2.6.32

**Web server:** apache 2.2.15

**Database:** mysql 5.0.11

**PHP version:** 5.6.24

**phpMyAdmin version:** 4.7.7

### Client configuration
**Browser:** Chrome 64.0.3282.119

**Operating system:** Windows 8.1

**Comment by shucon** [comment]
I can't reproduce the issue , can you attach the screenshots?

**Comment by zezettepglc** [comment]
https://www.youtube.com/watch?v=ohsfZgFzLLo

**Comment by shucon** [comment]
I still can't reproduce the issue , can you try to reproduce it on https://demo.phpmyadmin.net/master-config/

**Comment by devenbansod** [comment]
Hi @shucon thanks for trying to reproduce but the issue seems to be affecting in version 4.7.7; it seems to have been fixed in master. So, it won't be possible to reproduce it on master-config on the demo server.

Thanks for reporting this @zezettepglc but this has been already reported and tracked at #13931 . Closing this as duplicate.
