### ISSUE TITLE
Horizontal page overflow when javascript is disabled.

### ISSUE THREAD

**Issue by nulll-pointer** [phpmyadmin/phpmyadmin#13954]
### Steps to reproduce
1.Disable the javascript.

### Expected behaviour
div#serverinfo overflows leading to horizontal scroll.

### Server configuration
Ubuntu 17.04 zesty

**Web server:**
apache

**Database:**

**PHP version:**

**phpMyAdmin version:**
4.7.7
### Client configuration
Chromium 60.0.3112.78

**Operating system:**

**Comment by nulll-pointer** [comment]
I fixed this issue in the libraries, but the master branch doesn't have the files. how do i pr the fix.

**Comment by ibennetch** [comment]
Which library file is affected? Probably we have another repository for that (to make the code more modular and able to be widely used). For instance, the parser library is now maintained through the separate repository at https://github.com/phpmyadmin/sql-parser

If you can identify the file we can pretty easily point you to the right repository.

**Comment by nulll-pointer** [comment]
Its in the Header.php in the Libraries folder of my phpmyadmin which came with xampp.

**Comment by ibennetch** [comment]
Ah, okay; in the master branch that file is now in libraries/classes/Header.php as we move to a more class-oriented architecture.

However, phpMyAdmin isn't designed to operate without JavaScript enabled; there are a lot of things that will break aside from the display. I'm not sure whether such a change is likely to get merged. Perhaps some other developer would care to comment on that, and it probably depends on what the fix is...but having JavaScript enabled is a requirement so I think any problems that occur from disabling it shouldn't be considered a bug.
