### ISSUE TITLE
Missing query time in German

### ISSUE THREAD

**Issue by benjaminfunk** [phpmyadmin/phpmyadmin#13975]
The query execution time in above the query box is alway 0.0000 seconds when i activate the german language.

Version 4.7+

**Comment by nijel** [comment]
I can't reproduce this:

![screenshot-2018-3-1 localhost localhost iframe onload ale2 fdsafsa phpmyadmin 4 7 9-dev](https://user-images.githubusercontent.com/212189/36849160-8e9569d0-1d63-11e8-973d-49e15d70c594.png)

What version do you use?

**Comment by benjaminfunk** [comment]
Version 4.7.9 for WampServer (local environment)

Maybe its a WampServer related bug if u cant reproduce it

**Comment by nijel** [comment]
Does it happen for every query or only in some specific cases?

**Comment by benjaminfunk** [comment]
Looks like every query

**Comment by williamdes** [comment]
@benjaminfunk Can you try on version `4.8.1` ?

Can you send more informations on OS, web server if `4.8.1` has the issue ?

I think that I had the same issue with French on a Windows running `IIS` and MySQL `~5.7`.

**Comment by benjaminfunk** [comment]
@williamdes The problem still exists with phpMyAdmin 4.8.1 in my environment

Windows 10
Apache 2.4.33
PHP 7.2.6
MySQL 5.7.22

**Comment by williamdes** [comment]
Successfully reproduced on Windows 10 ( 10.0.10586 ) and VirtualBox with :
- Apache 2.4.33
- PHP 7.2.7
- MySQL 8.0.11

Investigating...

**Comment by williamdes** [comment]
This issues does not exist anymore on 5.0.0-dev

**Comment by williamdes** [comment]
[-] = Non tested
- [ ] = Does not work
- [x] = Works (Has SQL time)

## Results 
- [-] العربية - Arabic
- [-] Հայերէն - Armenian
- [-] Azərbaycanca - Azerbaijani
- [-] বাংলা - Bangla
- [-] Беларуская - Belarusian
- [-] Български - Bulgarian
- [-] Català - Catalan
- [x] 中文 - Chinese simplified
- [x] 中文 - Chinese traditional
- [ ] Čeština - Czech
- [-] Dansk - Danish
- [-] Nederlands - Dutch
- [x] English
- [x] English (United Kingdom)
- [-] Eesti - Estonian
- [x] Suomi - Finnish
- [ ] Français - French
- [-] Galego - Galician
- [ ] Deutsch - German
- [-] Ελληνικά - Greek
- [-] Magyar - Hungarian
- [-] Bahasa Indonesia - Indonesian
- [-] Interlingua
- [-] Italiano - Italian
- [-] 日本語 - Japanese
- [-] 한국어 - Korean
- [-] Lietuvių - Lithuanian
- [-] Norsk - Norwegian
- [-] Polski - Polish
- [-] Português - Portuguese
- [-] Português (Brasil) - Portuguese (Brazil)
- [-] Română - Romanian
- [ ] Русский - Russian
- [-] Srpski - Serbian (latin)
- [-] සිංහල - Sinhala
- [-] Shqip - Slbanian
- [-] Slovenčina - Slovak
- [-] Slovenščina - Slovenian
- [-] Español - Spanish
- [-] Svenska - Swedish
- [-] Türkçe - Turkish
- [x] Українська - Ukrainian
- [-] Tiếng Việt - Vietnamese

**Comment by williamdes** [comment]
- When copying french .mo file in pt_BR folder It works (conclusion mo file is not where this issue is)
- Copy the fr folder to fr_FR and It works !
- Or rename es folder to ES_ES or es@es

I found where is the error, remove this line (some codes work perfectly) :
https://github.com/phpmyadmin/phpmyadmin/blob/b9c0463d960494cbfe0f04b3159c5ff4a467c446/libraries/classes/Language.php#L180

https://stackoverflow.com/a/29522488/5155484

https://stackoverflow.com/questions/32339621/php-setlocale-not-working-correctly-on-windows-10-machine


@mauriciofauth do you think we can skip this line for windows platform or remove it completely ?

**Comment by williamdes** [comment]
@nijel Can you please have a look when you have some time ?

**Comment by benjaminfunk** [comment]
> AFAIK without this the numbers and dates won't be localized at all (that should be easy to verify).
> 
> Anyway this really boils down to broken sprintf after calling setlocale? Can you try following snippet?
> 
> ```
> <?php
> $value = 0.001;
> echo sprintf("original = %01.4f\n");
> setlocale(0, 'de');
> echo sprintf("localized = %01.4f\n");
> ```
> 
> What's result of setlocale in this case? Maybe handling failure and using some other locale instead could be a workaround (apparently some of them seem to work).

I had a similar issue with floating numbers. Try to uppercase the "f" in the sprintf function.

Look here: http://php.net/manual/de/function.sprintf.php#49254

**Comment by nijel** [comment]
But that will ruin the localization for everybody, not just for the broken systems...

**Comment by plaki** [comment]
I find solution to fix this problem.
I want to pull request, but I don't know which branch I can pull request. Do I pull request to `master` branch?

Problem is conversion of number from int/float to string (when adding parameter to Message class) and then using `sprintf` funciton to format string. Some locales use comma as decimal separator and it is problem, when we want use this number (as string) in `sprintf` function. PHP can't convert number from string to float when decimal separator is comma (with dot working fine), so it converts it to integer number, because comma is invalid character to convert to number. I think that if we want format number by `sprintf` function, number parameter must have right number format (numeric variable or string with dot decimal separator), if it's string, it's convert string to number and then format it. I hope that I describe it understandably.

@nijel I think I know why you couldn't reproduce it. It's because some servers (computers) not have installed support for different locales, so it's not use comma as decimal separator but use dot as decimal separator as fallback. With dot separator everything is working fine.

**Comment by ibennetch** [comment]
@plaki I won't comment on the solution you've found (it makes sense, though), but a fix should preferably target the QA_4_8 branch.
