### ISSUE TITLE
Missing padding

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14053]
![pma](https://user-images.githubusercontent.com/2218936/36943728-48ae8c08-1f8e-11e8-83f5-3e96b68b747a.PNG)

**Comment by akshil4444** [comment]
Hi, can you send the more details? like which system, browser, phpmyadmin version.

**Comment by OlafvdSpek** [comment]
Chrome, pMA git

**Comment by williamdes** [comment]
@OlafvdSpek Can you send more detailed information to reproduce ?

**Comment by OlafvdSpek** [comment]
What info is missing?

**Comment by williamdes** [comment]
@OlafvdSpek The query ?

**Comment by OlafvdSpek** [comment]
I doubt it's query-specific.

**Comment by williamdes** [comment]
This issue exists !
Run the following query:

```sql
SELECT `Host`, `User`, `Select_priv`, `Insert_priv`, `Update_priv`, `Delete_priv`, `Create_priv`, `Drop_priv`, `Reload_priv`, `Shutdown_priv`, `Process_priv`, `File_priv`, `Grant_priv`, `References_priv`, `Index_priv`, `Alter_priv`, `Show_db_priv`, `Super_priv`, `Create_tmp_table_priv`, `Lock_tables_priv`, `Execute_priv`, `Repl_slave_priv`, `Repl_client_priv`, `Create_view_priv`, `Show_view_priv`, `Create_routine_priv`, `Alter_routine_priv`, `Create_user_priv`, `Event_priv`, `Trigger_priv`, `Create_tablespace_priv`, `ssl_type`, `ssl_cipher`, `x509_issuer`, `x509_subject`, `max_questions`, `max_updates`, `max_connections`, `max_user_connections`, `plugin`, `authentication_string`, `password_expired`, `password_last_changed`, `password_lifetime`, `account_locked`, `Create_role_priv`, `Drop_role_priv`, `Password_reuse_history`, `Password_reuse_time`, `Password_reuse_time` a, `Password_reuse_time` b, `Password_reuse_time` c, `Password_reuse_time` d, `Password_reuse_time` e, `Password_reuse_time` f, `Password_reuse_time` g FROM `user` WHERE 1
```
This issue affects very long queries.

**Comment by beekalam** [comment]
@williamdes 
In
[import.php](https://github.com/phpmyadmin/phpmyadmin/blob/master/import.php)

there's
```php
// (but if the query is too large, in case of an imported file, the parser
//  can choke on it so avoid parsing)
$sqlLength = mb_strlen($sql_query);
if ($sqlLength <= $GLOBALS['cfg']['MaxCharactersInDisplayedSQL']) {
   .........
}
```
if the query is bigger than 1000 characters long then it won't be parsed(or beautified). 
is the issue about the query not being beautified or that it is not completely shown.
I am not sure what the issue is exactly?

**Comment by williamdes** [comment]
@beekalam Thank you for the research, can you create a pull-request if you know how to fix this issue ?
The issue is not having the beautifier and the padding is missing.
PS: I updated the query to have a better test sample.
### Screenshot
![44667330-cec5-4e7b-ad54-0dd087aa5ab1](https://user-images.githubusercontent.com/7784660/48660779-a83e8200-ea67-11e8-9f51-d6766a8af0a8.jpg)

**Comment by williamdes** [comment]
Still on `4.8.5`

**Comment by khaydarov** [comment]
@williamdes 
I wanted to start with this issue, but for it is ok. Using 4.8.5

![image](https://user-images.githubusercontent.com/6507765/53502131-87ea7e80-3abe-11e9-853d-6bc5320705ed.png)
