### ISSUE TITLE
CDN Support for phpMyAdmin

### ISSUE THREAD

**Issue by stevenzhu25** [phpmyadmin/phpmyadmin#14069]
Hi,

I'm just wondering if there could be a chance PHPMYADMIN can offer cdn support?

(I see that the website generator have cdn.py) Might this code provide me the ability to use CDN77, MAXCDN etc?

Thank you

**Comment by ibennetch** [comment]
Sorry but I'm not understanding your intention here. Where exactly would you like to use a CDN?

I don't think you'd want to use a CDN to publish your phpMyAdmin installation, because it wouldn't be caching your database information and would be making a new query to your backend anyway on each action, right? Also, since phpMyAdmin isn't meant as a front end for end users, I'm having trouble imagining how you could have enough users to benefit from a CDN there.

**Comment by stevenzhu25** [comment]
Hi,

I'm just interested in serving all static file through cdns. (Just to reduce time)

**Comment by meteorlxy** [comment]
Well, phpmyadmin may also be used when the internet is unavaliable.

**Comment by ibennetch** [comment]
Wouldn't your CDN cache all the static files (such as images and some JavaScript files) automatically, and of course fetch dynamic content as needed? I'm not sure I see how phpMyAdmin can be improved in this way, but maybe I'm just not familiar with how your CDN works.
