### ISSUE TITLE
More Dropdown not fully visible

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14102]
![pma](https://user-images.githubusercontent.com/2218936/37657846-61b98048-2c4c-11e8-96c3-d08b8854dd11.png)

**Comment by shucon** [comment]
@ibennetch what do you think?

**Comment by uok** [comment]
I also came here because of this bug. I'm glad I found the configuration option [$cfg['HideStructureActions']](https://docs.phpmyadmin.net/en/latest/config.html#cfg_HideStructureActions) since I'm on a widescreen monitor and phpMyAdmin only used half of the screen space. I personally would prefer default=false.
