### ISSUE TITLE
Feature Request: Move columns preview SQL

### ISSUE THREAD

**Issue by ChrisHSandN** [phpmyadmin/phpmyadmin#14155]
### Steps to reproduce
1. On any table
2. Structure Tab
3. Move Columns

### Expected behaviour
Move Columns modal should have a "Preview SQL" button which shows the SQL which will be run.

This would make is consistent with the structure change, relationship view, edit index, insert etc. which all have a Preview SQL option.

### Actual behaviour
Only "OK" and "Cancel" is available.

**Comment by Piyush3079** [comment]
I also think that this feature should be implemented in the coming releases as PMA is also a source for learning sql queries to be used for various functions for beginners. Therefore there should be as much preview sql options as possible so that user can see what query is exactly being generated by using a particular function of PMA so that he can learn as many sql queries as possible.
PMA helped me too in learning many sql queries by using preview sql feature @mauriciofauth @ibennetch .
Although I have started working on this.
