### ISSUE TITLE
CREATE USER after delete

### ISSUE THREAD

**Issue by willowcommand** [phpmyadmin/phpmyadmin#14157]
### Steps to reproduce
1. CREATE USER 'dave'@'localhost' IDENTIFIED BY 'somepassword';
2. browse users and DELETE dave
3. CREATE USER 'dave'@'localhost' IDENTIFIED BY 'somepassword';

### Expected behaviour
Second create should work

### Actual behaviour
Second create returns #1396 - Operation CREATE USER failed for 'dave'@'localhost'

### Server configuration
**Operating system**:
Windows 10
**Web server:**
Apache/2.4.29 (Win32) OpenSSL/1.1.0g 
**Database:**
10.1.31-MariaDB
**PHP version:**
7.2.3
**phpMyAdmin version:**
 4.7.9
### Client configuration
**Browser:**
Firefox 59.0.2 (64-bit)
**Operating system:**
Windows 10

**Comment by willowcommand** [comment]
The problem can be overcome by either 'FLUSH PRIVILEGES' or stopping/starting the server - which does the same thing :)

**Comment by ibennetch** [comment]
Are you running these SQL commands manually or using the graphical interface to add and remove the users?

**Comment by ibennetch** [comment]
This works okay for me using the GUI interface under the "User accounts" tab.

Using GRANT statements should cause MariaDB to reload the cached user account information on its own (see https://dbahire.com/stop-using-flush-privileges/ for instance); I'm not really certain if this is a regression in MariaDB itself or just some unintended artifact of the caching. My best guess is that since you're still connected on the same session and since MySQL claims the cache for global privileges persists through a connected session, that you're still seeing the old cached user and would have to either log out of phpMyAdmin or manually run the FLUSH PRIVILEGES for the change to reflect.

Regardless, since it's SQL you're running and not a problem with the phpMyAdmin interface, I think it's really a MariaDB problem and there's not much we can do about it.

**Comment by willowcommand** [comment]
That all makes sense

Thanks for the feedback

Dave
