### ISSUE TITLE
Export table structure shows rows fields

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14334]
Rows doesn't make sense if you only export structure..

![pma](https://user-images.githubusercontent.com/2218936/40602251-3aaeba76-6258-11e8-8b83-56d259469d0a.PNG)

**Comment by furuno** [comment]
Hi, I would like to help with this issue. Could you please let me know the URL of the page that have this issue?

**Comment by OlafvdSpek** [comment]
https://demo.phpmyadmin.net/master-config-nopmadb/tbl_export.php?db=Restaurante&table=Horarios&single_table=true

**Comment by furuno** [comment]
Ah I see. Sorry about that. Working on it.

**Comment by ibennetch** [comment]
You're not wrong, but since the row selector comes first this is a bit more difficult than just showing or hiding it (simply hiding the row selector when the user toggles to structure is pointless since it will make the whole UI slide up and the user has already made a decision about this).

I think the best solution is to move the row selector down, perhaps as the next thing after the data/structure/both selector.

**Comment by williamdes** [comment]
@Ganofins That doesn't matter because this issue is on all table exports.

**Comment by williamdes** [comment]
@Ganofins 
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

Steps
- Navigate to a database
- Navigate to a table
- Go to "Export"
- Choose the radio "Structure" in "Format-specific options:"

"Rows: " should be hidden when structure is checked.

@Ganofins

**Comment by abhishekvirat0** [comment]
Is the problem solved or you need help ??

**Comment by Ganofins** [comment]
![error](https://user-images.githubusercontent.com/11516116/48903414-8424db80-ee81-11e8-8668-fce95cb5ed53.png)


hey @williamdes that's what I am getting on following the steps

**Comment by williamdes** [comment]
@abhikandoi2000 You can find another issue if you want to contribute :)
This one already has a pull-request to fix this issue.
