### ISSUE TITLE
Error in PHPMYADMIN UBUNTU 16.04

### ISSUE THREAD

**Issue by patidarkishor777** [phpmyadmin/phpmyadmin#14410]
### Steps to reproduce
1. I installed phpmyadmin 
2. PHP 7.2

### Actual behaviour
Showing following error message
Warning in ./libraries/plugin_interface.lib.php#532
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/display_import.lib.php#368: PMA_pluginGetOptions(
string 'Import',
array,
)
./libraries/display_import.lib.php#453: PMA_getHtmlForImportOptionsFormat(array)
./libraries/display_import.lib.php#684: PMA_getHtmlForImport(
string '5b2a3f184267a',
string 'database',
string 'GPH_PORTAL',
string '',
integer 134217728,
array,
NULL,
NULL,
string '',
)
./db_import.php#40: PMA_getImportDisplay(
string 'database',
string 'GPH_PORTAL',
string '',
integer 134217728,
)

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7.2

**phpMyAdmin version:**  4.5.4.1deb2ubuntu2

### Client configuration
**Browser:** Chrome, Firefox

**Comment by williamdes** [comment]
This issue does not exist anymore, please upgrade phpMyAdmin to last version.

`/libraries/plugin_interface.lib.php` removed by commit : https://github.com/phpmyadmin/phpmyadmin/commit/700e081833dd7cd1b1669412ddf1c2e135ade0a1#diff-e4fb76d6e64dbbed120e6f1c178e44e5

`/libraries/display_import.lib.php` removed by commit : 
https://github.com/phpmyadmin/phpmyadmin/commit/f0f8c3e68f222b5673ff29d156591d32c004413c#diff-9b8280f66655e973e85e9a7063c7a2b1


@devenbansod Issue closed ?

**Comment by lem9** [comment]
@patidarkishor777 Indeed you should upgrade your phpMyAdmin. Your old version 4.5.4.1 was compatible with PHP 5.5 to 7.0.

**Comment by praggmatica** [comment]
Related to this - when will apt packages be updated? They are currently still installing the version @patidarkishor777 is referencing. I had to update manually.

**Comment by ibennetch** [comment]
Unfortunately, we don't control the packages for individual distributions. You would have to ask your distribution's package manager for information about updates.

I do know that with some LTS Linux distributions, since they're providing older PHP and/or MySQL versions, they can't upgrade the phpMyAdmin because of the version incompatibilities, so for instance in a distribution that maintains PHP 5.4 they won't also distribute phpMyAdmin 4.8, which requires PHP 5.5. So if you're installing your own PHP but using their included phpMyAdmin, you can get incompatibility trouble.

**Comment by ibennetch** [comment]
I'll close this since it seems to be fixed in more recent phpMyAdmin releases.

**Comment by gmanon** [comment]
I got this error today:
-------------------------------------------------------
    Server: Localhost via UNIX socket
    Server type: MySQL
    Server version: 5.7.25-0ubuntu0.18.04.2 - (Ubuntu)
    Protocol version: 10

Web server

    Apache/2.4.29 (Ubuntu)
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 -
    PHP version: 7.2.15-0
   ubuntu0.18.04.1
-------------------------------------------------------------------------------------------------------------------------
Warning in ./libraries/plugin_interface.lib.php#551
count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/display_import.lib.php#371: PMA_pluginGetOptions(
string 'Import',
array,
)
./libraries/display_import.lib.php#456: PMA_getHtmlForImportOptionsFormat(array)
./libraries/display_import.lib.php#691: PMA_getHtmlForImport(
string '5c87ee9144338',
string 'server',
string '',
string '',
integer 2097152,
array,
NULL,
NULL,
string '',
)
./server_import.php#34: PMA_getImportDisplay(
string 'server',
string '',
string '',
integer 2097152,
)

**Comment by ibennetch** [comment]
@gmanon Unfortunately, the version of phpMyAdmin that's packaged with Ubuntu 18.04 (phpMyAdmin 4.6.6) is no longer maintained by us. I believe that version of Ubuntu has MySQL 5.7 or MariaDB 10.1 and PHP 7.2, both of which meet the requirements for the current phpMyAdmin release.

The Ubuntu package folks are unlikely to backport this fix, so I suggest removing the Ubuntu package and [installing your own phpMyAdmin](https://docs.phpmyadmin.net/en/latest/setup.html). This problem was fixed in our code some time ago.

**Comment by gmanon** [comment]
Thanks for letting me know.  If was an open parenthesis.

**Comment by williamdes** [comment]
@gmanon see my comments on #15515
