### ISSUE TITLE
withdraw question in faq

### ISSUE THREAD

**Issue by johnlow95** [phpmyadmin/phpmyadmin#14537]
i saw that there is question that have been withdrawn in the faq.md file, should i go and arrange the number and remove the withdrawn part?

**Comment by ibennetch** [comment]
Hello and thanks for your interest and also for taking the time to ask first. Because we have a lot of old links (from other forums, mailing lists, etc) to the documentation, it would cause some confusion to renumber them.

An argument could be made for just removing them entirely and just skipping that number, but at the time it was decided that doing so could cause confusion about why we skipped a number, so the decision was made to use the “withdrawn” label.

**Comment by lem9** [comment]
Indeed; this issue can be closed IMO.
