### ISSUE TITLE
PMA version from command line

### ISSUE THREAD

**Issue by QROkes** [phpmyadmin/phpmyadmin#14562]
I just have a question.
Is there a way to check the PMA current installed version from command line?

PMA is included in my Open Source Project "Webinoly" and I need to show the version of all the installed packages (Ubuntu - bash script).

**Comment by lem9** [comment]
No way currently.

**Comment by ibennetch** [comment]
You could grep it from the source yourself, though; for instance from where we set PMA_VERSION (see as an example commit https://github.com/phpmyadmin/phpmyadmin/commit/42f36cce395eade401155e51cd15900b86bcec70).

**Comment by williamdes** [comment]
@ibennetch From `composer.json` ?

**Comment by ibennetch** [comment]
@williamdes I don’t think current version information is reliably available there, is it?

**Comment by williamdes** [comment]
@ibennetch I did not see that nobody indicated it...
https://github.com/phpmyadmin/phpmyadmin/blob/master/package.json is maybe a better idea

**Comment by ibennetch** [comment]
Reopened because we need to document or automate updating `packages.json`.

@mauriciofauth introduced this file in 83df3be3295325a42a487afcf4b88e8b84de7a52 "Add ESLint JavaScript linter" but I don't think we have documented the need to increment the version in packages.json when creating a new release.

I think we need to document this in the "Todo now" section of scripts/create_release.sh. After we make that change, the packages.json file should always reflect the correct version number.

Assigning this to myself for now.

**Comment by ibennetch** [comment]
On second thought, because this is rather a different request than the documentation, I am closing this again in favor of opening #14567.
