### ISSUE TITLE
Missing dependency on PHP iconv extension?

### ISSUE THREAD

**Issue by dsieborger** [phpmyadmin/phpmyadmin#14642]
Functions supplied by the PHP iconv extension are used (e.g. in vendor/symfony/polyfill-mbstring/Mbstring.php) but the iconv extension is not listed in composer.json.

Should iconv be added to the "require" list in composer.json?

**Comment by ibennetch** [comment]
By memory, the last time we brought up this (or a similar PHP issue), it wasn’t clear what benefit this has, since on most systems the PHP extensions are maintained as part of a distrivution’s package manager or built at compile time by the user. Putting the requirement in Composer seemed to have no benefit.

**Comment by ibennetch** [comment]
Ah, that discussion was about php-gd in #14171, although the result should be the same. I don’t think this is the way to fix this issue.

**Comment by OlafvdSpek** [comment]
Isn't it symfony/polyfill-mbstring that should have the dependency?

**Comment by mauriciofauth** [comment]
I don't know what is the benefit of explicitly requiring the iconv extension, since this extension is enabled by default in PHP.

**Comment by ibennetch** [comment]
I'm still confused about this, if a package such as polyfill-mbstring requires iconv, that should depend on it, rather than the base phpMyAdmin package. The main code within phpMyAdmin itself should be able to handle a missing iconv, since`$cfg['RecodingEngine']` will fall back to recode_string or mbstring when iconv is missing. I still think we should handle this upstream.

Further, even with a disabled iconv, I'm able to do many table operations and can't find a specific problem in phpMyAdmin.

Does this report come from a specific way you're able to get an error? Can you paste steps to reproduce it or tell me what part of the code causes an error for you?
