### ISSUE TITLE
Status -> Processes doesn't show full query

### ISSUE THREAD

**Issue by spacepille** [phpmyadmin/phpmyadmin#14800]
### Describe the bug

A click on the <-T-> on SQL query in Status -> Processes is without function. It doesn't show the full query.

### To Reproduce

1. Go to Status -> Processes
2. Click on <-T-> behind SQL query
3. And see that nothing happens

### Expected behavior

It should show the full SQL query.

### Screenshots

![grafik](https://user-images.githubusercontent.com/11977563/50302634-efff6180-048a-11e9-8a7c-a444700bfa66.png)

### Server configuration

- Operating system: Ubuntu 14.04.1 LTS
- Web server: nginx/1.4.6
- Database version: 10.0.27-MariaDB-1~xenial-wsrep - mariadb.org binary distribution, wsrep_25.16.rc3fc46e 
- PHP version: 5.6.34-1+ubuntu14.04.1+deb.sury.org+1 
- phpMyAdmin version: 4.8.4 (up to date)

### Client configuration

- Browser: Firefox Devloper Edition 65.0b4 (64-Bit)
- Operating system: Windows 10 Pro

**Comment by williamdes** [comment]
Git bisect found that 0fe1a3bea88a553407930f83380b88d7591d2bdd is the first bad commit

Successfully reproduced on demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by ibennetch** [comment]
@williamdes @mauriciofauth Has there been any more progress on fixing this bug?

**Comment by williamdes** [comment]
@ibennetch I did not have any time to fix this issue and #14833 is maybe related to this issue ;)

**Comment by still-dreaming-1** [comment]
The problem in the stable version is it is using the POST value instead of the GET value. I peeped at the latest code and it seems that may have been fixed. However, I also feel the logic should be fully reversed to use FULL by default rather than after explicitly requesting this, otherwise it is basically setup to be annoyingly almost useful by default and only actually useful upon request. Or at the very least there should be a configuration option to make FULL the default. Occasionally people send me screenshots of partial long running queries from this page, which is almost helpful.
