### ISSUE TITLE
Missing whitespace in User accounts overview

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14807]
Whitespace is missing between icons and text like `Remove selected user accounts`.

![pma](https://user-images.githubusercontent.com/2218936/50373804-3b795300-05e4-11e9-9956-27b28fad6812.PNG)

pMA 5

**Comment by akkywadhwa** [comment]
@williamdes or @OlafvdSpek  Can you please provide version information clearly?

**Comment by OlafvdSpek** [comment]
pMA 5 (i.e. git master)?

**Comment by akkywadhwa** [comment]
Hey @OlafvdSpek! I cloned the master branch and followed the setup instructions. I wasn't able to reproduce this error. Can you please provide more information so that I can reproduce and fix it?

Preview of freshly cloned master branch
![untitled](https://user-images.githubusercontent.com/666752/51440274-65a95800-1ceb-11e9-8d51-f3c931a1d1ee.png)

Configuration
![config](https://user-images.githubusercontent.com/666752/51440307-b325c500-1ceb-11e9-91c6-551100376385.png)

@williamdes Can you please confirm if error is actually present or not?
