### ISSUE TITLE
PMA_messages is not defined

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#14826]
### Describe the bug

PMA_messages is not defined

### To Reproduce

No idea.

### Additional context

`PMA_messages is not defined` is reported many times on reporting server.

See: #11783

**Comment by williamdes** [comment]
@rapidmod Do you still have this issue ?

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |PMA_messages is not defined
 Exception Type |js
 phpMyAdmin version |4.8.2
 Incident count | 915
 Link | [Report#53433](https://reports.phpmyadmin.net/reports/view/53433)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by kartik1000** [comment]
Hey @williamdes I googled the issue and found (https://stackoverflow.com/questions/26036533/phpmyadmin-class-pma-message-not-found-in-usr-share-phpmyadmin-libraries-erro) that people have managed to fix this issue by restarting apache server. I think, then the issue might be then due to some apache service not being started sometimes 🤔

**Comment by williamdes** [comment]
@kartik1000 A lot of users still have this issue according to what I found on phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net)
Can you find a way to reproduce this issue ?
It would help me a lot !

**Comment by kartik1000** [comment]
@williamdes I am onto it..

**Comment by kartik1000** [comment]
Hey, @williamdes I found that the issue is related to permissions on session folder phpmyadmin is using and many people have fixed it by allowing sessions folder the required permissions and also in one of the cases it was related to space available for php to create sessions. See https://web.archive.org/web/20141102061301/http://gnuwhatimsaying.com/phpmyadmin-error-class-pma_message-not-found/ and https://web.archive.org/web/20160316021748/http://rakesh.sankar-b.com/2012/05/20/phpmyadmin-pma-message-class-not-found/. I have asked the respective people who faced those issue to tell me more about it to reproduce the issue. More so, I think we can reproduce this issue by simply disallowing the permissions to sessions folder and then load phpmyadmin on apache server as some of them faced problems in this way only. Hope it helps :)

**Comment by fivemru** [comment]
I solved the problem with the PMA_messages error as follows: 
before: http://localhost/phpmyadmin
after: https://localhost/phpmyadmin

**Comment by williamdes** [comment]
This Issue is no longer associated with [Report#53433](https://reports.phpmyadmin.net/reports/view/53433)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment]
Param | Value 
 -----------|--------------------
 Error Type | ReferenceError
 Error Message |PMA_messages is not defined
 Exception Type |js
 phpMyAdmin version |4.8.2
 Incident count | 1701
 Link | [Report#53433](https://reports.phpmyadmin.net/reports/view/53433)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by Titeflafla** [comment]
Hello same error on my server after upgrade on 4.8.5, ok after install php7.0-bz2 all is good :)
