### ISSUE TITLE
Error: Parse error: syntax error, unexpected '(' in /home/crimev5/public_html/wp-content/plugins/wp-phpmyadmin-extension/index.php on line 182

### ISSUE THREAD

**Issue by davidsizer** [phpmyadmin/phpmyadmin#14834]
### Describe the bug

When logging into our wordpress site - the following error appears:
Parse error: syntax error, unexpected '(' in /home/crimev5/public_html/wp-content/plugins/wp-phpmyadmin-extension/index.php on line 182

The website was operational on January 4th 2019, however, over the weekend wonder if there was an update? It is not working today Jan 7th 2019. As far as I am aware nobody has edited the site at all.

### To Reproduce

1. Navigate to : http://crimevictimscomp.ga.gov/

### Expected behavior

Website loads

### Server configuration

- Operating system:
- Web server: Wordpress
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by ibennetch** [comment]
Hello,

This is a bit difficult because there's a WordPress extension that we don't control involved here (in fact, I only just now learned that this extension even exists). phpMyAdmin itself doesn't have this problem, so it seems to be related to either the extension itself or something in your environment. 
In fact, you don't seem to be the only one with the problem: https://wordpress.org/support/topic/open-parens-caused-wp-phpmyadmin-problem/

I suggest making a comment in that forum to get help directly from the extension author; since it's downstream of us there isn't much we can do to fix a problem with his code or even help debug it.

Good luck
