### ISSUE TITLE
Display column details in navigation bar

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#14890]
It would be very nice to have more information about the columns in the navigation bar, just like SQL Server Management Studio does.

- Primary Key or Foreign Key
- Data Type (int, varchar, date, etc...)
- NULL or NOT NULL

![image](https://user-images.githubusercontent.com/487079/51554682-c2348080-1e6d-11e9-87a0-108ee4d01511.png)

**Comment by saurass** [comment]
@williamdes I would like to work on this : ) 
First I will begin by working on column view in navigation tree

**Comment by ibennetch** [comment]
I have two thoughts about this to share; first, we have shied away from this in the past because of wanting to avoid cluttering the interface. With larger screen resolutions now, that may not be a huge issue. Secondly, we can’t too closely emulate some other interface because we want to innovate our own interface and not steal someone else’s ideas.

Those concerns aside, this is an interesting idea.

**Comment by saurass** [comment]
So should we go for this @ibennetch ?

**Comment by nunoperalta** [comment]
@ibennetch - I'm not against taking other interface's ideas. If they are good and beneficial, then I don't see a problem. Databases themselves keep copying features from others. That only benefits the users.

Also, this could be very well a setting that allows those who want a simple interface to disable this.

I much more prefer this feature than the "Hide Table" button that I had to disable with AdBlock, because there is no setting to disable that "cluttering" (in my opinion) button :)

Thanks very much for considering this.

**Comment by nunoperalta** [comment]
@ibennetch Ok to implement this? :) Thanks very much!
