### ISSUE TITLE
Util.php does not use correct MySql version if version is 8.0 or above

### ISSUE THREAD

**Issue by tm8544** [phpmyadmin/phpmyadmin#14947]
If Mysql version is 8.0 or above, phpmyadmin/libraries/classes/Util.php still uses max version 5.7

See Util.php starting from line 358:
`           if ($serverVersion >= 50700) {`
`                $mysql = '5.7';`
`            } elseif ($serverVersion >= 50600) {`
`                $mysql = '5.6';`
`            } elseif ($serverVersion >= 50500) {`
`                $mysql = '5.5';`
`            }`

It should be
`            if ($serverVersion >= 80000) {`
`                $mysql = '8.0';`
`            } elseif ($serverVersion >= 50700) {`
`                $mysql = '5.7';`
`            } elseif ($serverVersion >= 50600) {`
`                $mysql = '5.6';`
`            } elseif ($serverVersion >= 50500) {`
`                $mysql = '5.5';`
`            }
`

**Comment by ibennetch** [comment]
This is a great suggestion and good job noticing this behavior.

A complete solution should probably also adjust for different MariaDB versions, as well. For instance, I'm on MariaDB 10.1.37 (getVersion returns 100137) but I'm still linked to the 5.7 documentation with this patch.

@williamdes I thought you had done some work to link to the appropriate documentation depending on if the user was running a MariaDB or MySQL instance, am I remembering incorrectly what the purpose was?

We'll probably need to end up with checks here for MySQL vs MariaDB, then decide the appropriate version number within that logic.

**Comment by ibennetch** [comment]
The proposed patch is a good improvement despite the other issue I pointed out.

**Comment by williamdes** [comment]
@ibennetch @tm8544 I think this can be implemented on https://github.com/williamdes/mariadb-mysql-kbs

**Comment by ibennetch** [comment]
Related to #14520

**Comment by victorphoenix3** [comment]
@williamdes  I have tested and found that we cannot directly implement this patch since then many of the links will break.
For example - when we call `show_mysql_docu('procedure_analyse')` in `display_structure.twig` we get redirected to https://dev.mysql.com/doc/refman/5.7/en/procedure-analyse.html .
But after applying the patch we will be redirected to https://dev.mysql.com/doc/refman/8.0/en/procedure-analyse.html which does not exist since
PROCEDURE ANALYSE() has been removed in `MySQL 8.0`. 

I am looking for a better fix for the issue.

**Comment by williamdes** [comment]
@victorphoenix3 this fix must be implemented on this repo https://github.com/williamdes/mariadb-mysql-kbs

**Comment by williamdes** [comment]
I would make sense

**Comment by victorphoenix3** [comment]
> @victorphoenix3 this fix must be implemented on this repo https://github.com/williamdes/mariadb-mysql-kbs

@williamdes  could u please explain why I need to use this repo? What is this repo is for?

**Comment by williamdes** [comment]
> > @victorphoenix3 this fix must be implemented on this repo https://github.com/williamdes/mariadb-mysql-kbs
> 
> @williamdes could u please explain why I need to use this repo? What is this repo is for?

I started to move out all the dynamic data in #14459

And would like to continue moving out the data, and URLs that are left.
Because it is not phpMyAdmin's job to keep up to date with the websites.
And also it would allow to have links for MariaDB :

> @williamdes could u please explain why I need to use this repo?

 #14459 is be an example and the first purpose of my repo
