### ISSUE TITLE
Simple trick to let phpMyAdmin work with MySQL 5.1

### ISSUE THREAD

**Issue by nsoggia** [phpmyadmin/phpmyadmin#14952]
I was curious if I could use the latest phpMyAdmin with MySQL 5.1.
It's indeed possible setting $cfg['MysqlMinVersion'] and **not** setting the lc_messages system variable on MySQL servers older than 5.5.
Here is my solution:

```
diff -Naubr phpMyAdmin-4.8.5-all-languages.old/libraries/classes/DatabaseInterface.php phpMyAdmin-4.8.5-all-languages.new/libraries/classes/DatabaseInterface.php
--- phpMyAdmin-4.8.5-all-languages.old/libraries/classes/DatabaseInterface.php	2019-01-26 04:04:50.000000000 +0100
+++ phpMyAdmin-4.8.5-all-languages.new/libraries/classes/DatabaseInterface.php	2019-02-13 09:48:06.000000000 +0100
@@ -1484,7 +1484,7 @@
 
         /* Locale for messages */
         $locale = LanguageManager::getInstance()->getCurrentLanguage()->getMySQLLocale();
-        if (! empty($locale)) {
+        if ((! empty($locale)) && ($this->_version_int >= 50500)) {
             $this->query(
                 "SET lc_messages = '" . $locale . "';",
                 DatabaseInterface::CONNECT_USER,
```
This error will disappear and most of the phpMyAdmin features will work
![lc_messages](https://user-images.githubusercontent.com/18053505/52697577-03521900-2f72-11e9-8476-c7d83a127f09.png)

Can you please make it official?
Thank you,
regards

**Comment by ibennetch** [comment]
This is a workaround for one aspect of the incompatibilities between MySQL 5.1 and 5.5, but there are other areas in the code where we've had trouble in the past. Since MySQL 5.1 ended official support over 5 years ago, we decided some time ago to deprecate and remove support for that version. There were multiple incompatibilities and using this workaround to get through the first error still leaves you vulnerable to inadvertently corrupting data.
