### ISSUE TITLE
Weird error for collation = ''

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14987]
https://demo.phpmyadmin.net/master-config/db_operations.php?db=Books

Select blank collation, click Go.

![pma](https://user-images.githubusercontent.com/2218936/53638944-25ad8d00-3c28-11e9-8721-2a23ed8a43b6.png)

**Comment by williamdes** [comment]
@kartik1000 Select the empty option in the collation list and execute "change all tables collations"

**Comment by sijie123** [comment]
This issue happens because users are not required to select any particular value within the dropdown list. When PMA sees that nothing has been selected, i.e. $_POST['db_collation'] is not set when the form is POSTed, then it's as good as if a user has just navigated to the page. Hence the response is a new form as shown in the screenshot by @OlafvdSpek.

I will work on a fix for this issue. I propose to simply add a "required" tag to the select field. This way, the form cannot be submitted without selecting a valid value.

**Comment by kartik1000** [comment]
LGTM 👍.Hey @sijie123 I would suggest you to wait for @williamdes 's opinion about this one

**Comment by williamdes** [comment]
> I will work on a fix for this issue. I propose to add a check for the select field. This way, the user will be presented with an error message if they ever selected the blank option.

I agree!
