### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by eric9930** [phpmyadmin/phpmyadmin#14981]
### Describe the bug

I currently have hired a developer to work on my website, as of today we are receiving a page not found error when loading phpmyadmin index. What steps do I need to take to resolve this issue so he can continue working on my website?

### To Reproduce

1. Go to my admin url
http://13.59.255.217/phpMyAdmin-R58JU23K74EJF/index.php
The website is podfever.com

### Expected behavior

I'm receiving Page Not Found

### Server configuration

ServerPilot and Amazon AWS

### Additional context

Because I've hired a developer and he asked me to submit a ticket I may need help explaining but willing to provide any additional information.

Thank you in advance.
![screenshot 2019-02-26 at 6 51 40 pm](https://user-images.githubusercontent.com/34785861/53457357-ba7d7400-39f7-11e9-8f82-a3534a4c03b8.png)

**Comment by ibennetch** [comment]
Since we maintain the phpMyAdmin software but don't host any user data, this is a question better suited for your hosting provider. It could be that you (or someone) has renamed or moved the phpMyAdmin subdirectory in your web root. Perhaps your installation uses a virtual host in your webserver which has been removed. It's possible your webserver error logs have more information, but we have no access to those logs or information about your specific system. Unfortunately, we don't have enough information about your installation to be helpful with troubleshooting this.

**Comment by eric9930** [comment]
Ok, thank you!
