### ISSUE TITLE
Login error, localised messages are badly encoded '�'

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15012]
### Reproduce
- `SET GLOBAL lc_messages = 'fr_FR';`
- Fail a login using bad username and password

Bad message:
```
mysqli_real_connect(): (HY000/1698): Acc�s refus� pour l'utilisateur: 'wdesportes'@'localhost'
```

Detected using: XAMP, WAMP, NGINX, PHP-FPM, MySQL, MariaDB, Windows7, Ubuntu
Using: Google Chrome

**Comment by Bournvita1998** [comment]
@williamdes can you please elaborate the procedure to reproduce it, as I am unable to locate the file where we need to make the required change to reproduce this error.

**Comment by williamdes** [comment]
@Bournvita1998 You need to execute the following sql query `SET GLOBAL lc_messages = 'fr_FR';` into the mysql console or into phpmyadmin and the fail a login on the login page

**Comment by AndikanAffiah** [comment]
I think the the issue is not from phpmyadmin but i think it is coming from your computer not being able to fully interpret the unicode character or does not support it.

I tried pasting this on my phpmyadmin console after logging in `🎀  🍓 ⋆` 
It showed `🎀  🍓 ⋆` then changed to this as shown in in the screenshot attached
![Screenshot (448)](https://user-images.githubusercontent.com/31145045/54089439-31582c80-4369-11e9-91ac-cf7ea8707de0.png)

**Comment by williamdes** [comment]
> I don't think it is a bug.

It is a bug, you did dot understand the issue, please follow the steps.

cc @Bournvita1998 @AndikanAffiah 

### 1, open a demo server link below
Demo servers (`root`, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

### 2, run the query
```sql
SET GLOBAL lc_messages = 'fr_FR';
```
### 3, Logout
Fail a login, the message is well encoded, no issue there.

### 4, Use my demo servers
- https://phpmyadmin-pr-6.wdes.eu.org/index.php
- https://phpmyadmin-pr-6.wdes.eu.org/index.php
User: `root` or `public`
Passwords: `public`

### Repeat 2 and 3
You will see that the issue is present on my demo servers, an not on the phpMyAdmin demo servers.


BUT: Do not start to tell me my servers are misconfigured because (quote my first message): "Detected using: XAMP, WAMP, NGINX, PHP-FPM, MySQL, MariaDB, Windows7, Ubuntu"

For me the is an issue in the code, somewhere, or in the transport, but not on the servers.

**Comment by williamdes** [comment]
![bad](https://user-images.githubusercontent.com/7784660/54090769-2a84e600-4378-11e9-8891-73e0a58dab3d.png)
![good](https://user-images.githubusercontent.com/7784660/54090776-4092a680-4378-11e9-9082-067fba4e255a.png)

**Comment by apoorvkhare07** [comment]
@williamdes Hey, I don't this in phpmyadmin. It is the issue of the system as it is not able to interpret the when in french. 
As after changing the language to french the error was coming fine when I tried a wrong password while logging in through the terminal and it gave the correct error message in french. 
![Screenshot from 2019-03-13 00-15-13](https://user-images.githubusercontent.com/26320019/54156855-14a51d00-446d-11e9-8fd7-207629f721b5.png)

But  when I did the same in phpmyadmin, it is giving the wrong error message. 
![Screenshot from 2019-03-13 00-15-03](https://user-images.githubusercontent.com/26320019/54156928-41f1cb00-446d-11e9-976c-ba7a2e18de28.png)

Also then when I saw the file containing the error messages in french, it had the message in wrong format (mostly because of system's inability to interpret it). 
![Screenshot from 2019-03-13 02-13-02](https://user-images.githubusercontent.com/26320019/54157128-b3317e00-446d-11e9-9501-20d526a185a3.png)
Changing this should work, but we can't make system level changes for most user. 

Do let me know if there's some other way to work around with this problem.

**Comment by apoorvkhare07** [comment]
@williamdes Hey, I don't this in phpmyadmin. It is the issue of the system as it is not able to interpret the when in french.
As after changing the language to french the error was coming fine when I tried a wrong password while logging in through the terminal and it gave the correct error message in french.
![Screenshot from 2019-03-13 00-15-13](https://user-images.githubusercontent.com/26320019/54158629-ec1f2200-4470-11e9-9661-c233cba6eb29.png)

But when I did the same in phpmyadmin, it is giving the wrong error message.
![Screenshot from 2019-03-13 00-15-03](https://user-images.githubusercontent.com/26320019/54158646-f93c1100-4470-11e9-8701-97458bf2ff76.png)


Also then when I saw the file containing the error messages in french, it had the message in wrong format (mostly because of system's inability to interpret it).
![Screenshot from 2019-03-13 02-13-02](https://user-images.githubusercontent.com/26320019/54158655-fd682e80-4470-11e9-8bd5-85b2c68160d9.png)


Do let me know if there's some other way to work around with this problem.

**Comment by williamdes** [comment]
@aphisitworachorch Please try using `SET GLOBAL lc_messages = 'ru_RU';`

**Comment by apoorvkhare07** [comment]
@williamdes I tried with `SET GLOBAL lc_messages = 'ru_RU';` 
Here are the results 
![Screenshot from 2019-03-13 04-07-11](https://user-images.githubusercontent.com/26320019/54163068-c3e9f000-447d-11e9-9c37-2a12b458e0c8.png)
![Screenshot from 2019-03-13 04-07-14](https://user-images.githubusercontent.com/26320019/54163076-c5b3b380-447d-11e9-8149-6f21411ad10b.png)

**Comment by williamdes** [comment]
@apoorvkhare07 So, we have the same results, do you agree now that this is a phpMyAdmin issue ?
If not why ? (code sample ?)
Thank you for helping !

**Comment by apoorvkhare07** [comment]
@williamdes It seems like a phpmyadmin issue. I would work on it and let you know when its done.
Thankyou.

**Comment by williamdes** [comment]
@apoorvkhare07 You can work on this one :)

**Comment by apoorvkhare07** [comment]
@williamdes I have checked the output of `$mysqli` variable just after it calls `mysqli_real_connect` which is the most initial point of contact with the sql database. And it has the value wrong then itself. 
![Screenshot from 2019-03-13 05-19-01](https://user-images.githubusercontent.com/26320019/54165728-f7317c80-4487-11e9-979f-1db4f7edaf21.png)

**Comment by apoorvkhare07** [comment]
@williamdes seems like the message is getting curropted before getting into phpmyadmin. 
So, I think either we correct/render the message explicitly when language is not English or you have some alternate way to correct it ?

**Comment by williamdes** [comment]
@apoorvkhare07 Can you please try another language than `php` to understand if they are corrupted by the php mysql driver ?

**Comment by apoorvkhare07** [comment]
Ya sure, will check that.

**Comment by apoorvkhare07** [comment]
Hey @williamdes, I tried the same in python and was getting the correct error message. 
I think, now we can conclude the issue is with the php mysql driver. 

![Screenshot from 2019-03-14 04-20-18](https://user-images.githubusercontent.com/26320019/54241950-c8c7a600-4548-11e9-92ee-60832825f956.png)

**Comment by williamdes** [comment]
@apoorvkhare07 Thank you for the investigation and your patience !
I will try to find the bug on the php reporting system and search for patches

I do not know is it is worth to have a fix for the php driver..

**Comment by williamdes** [comment]
This is an encoding issue, the server is in latin1 so it sends error messages encoded in latin1

```php
<?php
$host = 'williamdes.local';
$db   = 'test';
$user = 'root';
$pass = 'efef';
$charset = 'utf8mb4';
header('Content-type: text/plain');
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
try {
    $mysqli = mysqli_connect($host, $user, $pass, $db);
    mysqli_set_charset($mysqli, $charset);
    echo "OK";
} catch (\mysqli_sql_exception $e) {
    echo iconv('Windows-1252', 'UTF-8', $e->getMessage());
    echo PHP_EOL;
    echo $e->getMessage();
}
```
