### ISSUE TITLE
Console height allows negative number

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15038]
### Describe the bug
I have given a large negative number as a console height it has not given an error or warning but converted that number to some other number when I clicked the apply button.

### To Reproduce

1. Go to 'settings'
2. Click on 'features'
3. Click on  'console'
4. Give a negative large number as an input for console height
5. Click on the apply button.
6. You'll see the difference after that.

### Expected behavior
I was expecting that there would be some limit or range of the console height and that input field would not allow negative number, as console height cannot be negative.

### Screenshots
Before applying:

![image](https://user-images.githubusercontent.com/36513474/54479822-0d05bf80-4843-11e9-9905-0e8c55574149.png)

After applying:

![image](https://user-images.githubusercontent.com/36513474/54479842-3f172180-4843-11e9-9d0a-bcf112ce4d66.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by ibennetch** [comment]
Related to: #15035.

**Comment by apoorvkhare07** [comment]
@ibennetch @williamdes @AghaSaad04  The configuration for validating console height goes like `$cfg_db['Console']['Height'] = 'integer';` in `config.value.php`. Which defines it as a PHP integer value which can have value between  **-2,147,483,648** to **2,147,483,647** only. This is the reason for this issue as well as #15035 .

In order to fix this we can think of a different way of validating these field. Similar to other fields where we use form ids and field names/ids to define their validation scheme.

**Comment by apoorvkhare07** [comment]
@williamdes @ibennetch Can you please comment on in what way should I proceed with this ? 
Because trying some other way to validate this might be different from the convention used for other fields of same type.
So, please let me know what way is fine for you all.
