### ISSUE TITLE
Export button 

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15032]
### Is your feature request related to a problem? Please describe.
The problem is that the export button is not in the right place. I have attached the image.

![image](https://user-images.githubusercontent.com/36513474/54475179-2b9e9300-4810-11e9-81ad-ecdc0190bfae.png)

### Describe the solution you'd like
The Export button should be on the right side of the import button and I think this can be done using bootstrap.

### Additional context

- phpMyAdmin version: 4.8.5

**Comment by Bournvita1998** [comment]
Is this issue still there? I went to Setting --> Features (as shown in the given screenshot). For me, changing the size of the browser(zoom in/out) is working fine to get them(import and export buttons) on the same line.

Have a look at these images but with different browser sizes(different zoom in/out %ages).

1. At 90%(based on my screen)

![Selection_021](https://user-images.githubusercontent.com/26218090/54496246-2b3af080-4913-11e9-97de-65a6ff86df53.png)

2. At 80%(based on my screen)

![Selection_020](https://user-images.githubusercontent.com/26218090/54496236-fa5abb80-4912-11e9-87ae-3c4901067a7a.png)

**Comment by apoorvkhare07** [comment]
@williamdes I dont think this is an issue. This is because of the responsiveness of the website, when the screen width is not enough to accommodate all buttons in one line it keeps some of the buttons in next line. 

eg: 
<img width="1247" alt="Screen Shot 2019-03-18 at 6 12 28 PM" src="https://user-images.githubusercontent.com/26320019/54530773-ae0e8a80-49a9-11e9-873f-73b0de070e50.png">

In case we want all buttons to be in same line, We'll have to decrease/fix their width which anyways won't look good.

**Comment by murex971** [comment]
@AghaSaad04 @williamdes 
![image](https://user-images.githubusercontent.com/46920259/54586044-d77af500-4a41-11e9-8c20-44e94bc58004.png)
This ain't any issue. It's just the responsive behaviour of page which wraps the buttons to next line as the size of browser window decreases.
This feature provides user a better view of all the features(buttons) irrespective of window size.
So I don't think it requires any modifications/changes.

**Comment by AghaSaad04** [comment]
@apoorvkhare07  @murex971 that's what I am saying, as this website needs enhancement and needs to be in bootstrap for a better layout.

**Comment by AghaSaad04** [comment]
When I click on "manage your settings" all the tabs are in one line:

![image](https://user-images.githubusercontent.com/36513474/54599873-66e1d180-4a5d-11e9-9444-8ed14942f691.png)

When I click on "features" export button moves to the second line: Though there's not a single change in those tabs:

![image](https://user-images.githubusercontent.com/36513474/54599994-9d1f5100-4a5d-11e9-8b4c-079a64a497a4.png)

**Comment by murex971** [comment]
@AghaSaad04 
could you be more clear about the problem you want to convey.
Since I can't see any . The appearance of tabs in single or multiple lines totally depends upon size of browser window . If size is enough , and you click on 'features' then all tabs are displayed in a single line.
/home/nupur/Pictures/pic1.png
And if you decrease the size of browser window, and click on 'manage your settings' , some of the tabs will wrap to next line depending on the current browser window size.
/home/nupur/Pictures/pic2.png
As I earlier stated, it's just the responsiveness.

**Comment by murex971** [comment]
@AghaSaad04 
could you be more clear about the problem you want to convey.
Since I can't see any . The appearance of tabs in single or multiple lines totally depends upon size of browser window . If size is enough , and you click on 'features' then all tabs are displayed in a single line.
![pic1](https://user-images.githubusercontent.com/46920259/54626994-6286da00-4a98-11e9-8a99-38404d63286c.png)

And if you decrease the size of browser window, and click on 'manage your settings' , some of the tabs will wrap to next line depending on the current browser window size.
![pic2](https://user-images.githubusercontent.com/46920259/54627024-74687d00-4a98-11e9-98d8-3252ce433814.png)

As I earlier stated, it's just the responsiveness.

**Comment by AghaSaad04** [comment]
@murex971, I have not changed the browser size. When I click on features, the "export"  tab gets to the next line.

**Comment by lem9** [comment]
In my case, clicking on Features moves Export on the second menu line, only because the Features page is longer and requires a right vertical scrollbar, taking some screen space away from the menu.

**Comment by MrThanlon** [comment]
@AghaSaad04
Do you mean flex layout?

**Comment by lem9** [comment]
@AghaSaad04 Any reaction to my comment about the Features page being longer and requiring a vertical scrollbar?

**Comment by AghaSaad04** [comment]
Yes, Sir @lem9. You are right. If we change margins of the list, we can adjust all tabs in one line

**Comment by lem9** [comment]
@AghaSaad04 So I guess you can close the issue.

**Comment by lem9** [comment]
@AghaSaad04 Any feedback?

**Comment by AghaSaad04** [comment]
Yeah, I am going to close this issue. 
Thanks, everyone 👍
