### ISSUE TITLE
Logo Link URL 

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15041]
### Describe the bug
I changed the logo link URL to github.com and applied it. But when I clicked on the logo it redirected to index.php 

### To Reproduce

1. Go to 'settings'
2. Click on 'navigation panel'
3. Click on 'navigation panel'
4. Change the logo link URL to some other 
5. Click on logo.
6. It will redirect to index.php

### Expected behavior

It should have given some exceptions or warnings or should have redirected to the new URL. 

### Screenshots
Default index.php:

![image](https://user-images.githubusercontent.com/36513474/54491238-90c0ba00-48de-11e9-8164-c7ed6fbe6b6a.png)

Changes to github.com:

![image](https://user-images.githubusercontent.com/36513474/54491265-d1b8ce80-48de-11e9-9a7d-9bd04ce71307.png)

Still index.php:

![image](https://user-images.githubusercontent.com/36513474/54491276-f57c1480-48de-11e9-9c75-5fbcc29eb62a.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by sagarpandya1999** [comment]
I want to contribute in GSoC 2019 in your organization.
@williamdes, can you please assign me this bug?

**Comment by sagarpandya1999** [comment]
I want to contribute in GSoC 2019.
@williamdes, can you assign me this bug?

**Comment by williamdes** [comment]
> @williamdes, can you assign me this bug?

I can not assign you technically but you are the one to try to solve it now :)
Keep us updated on your progress

**Comment by MrThanlon** [comment]
It seems to must be full URL, just like that
> https://github.com

**Comment by sagarpandya1999** [comment]
@williamdes, i found the same as @MrThanlon.
If you provide any url without http protocol, it just redirect you at index.php (Home Page).
so, i think this is not a bug.
or you want any other change to do please tell me.

**Comment by ibennetch** [comment]
I agree with @sagarpandya1999, this seems to be working as expected for external sites. By providing a protocol, phpMyAdmin can know how to redirect to an external site, otherwise it seems you want a local file called github.com. phpMyAdmin can't know what you intend here, so this seems to be the correct behavior to me.

However, I can't get this to accept any local file. So for a web host who wishes to redirect to `/support/home.html` this is impossible. I think there's some problem here.

**Comment by ibennetch** [comment]
The checkLink function seems to be causing the problem here, I'd say it's being a bit overzealous in this particular instance. 

Currently accepted values for this, other than external URLs, are phpMyAdmin pages such as `./sql.php?` or `./db_events.php?`. I just wasn't trying the magic combination of characters around the filename.

I believe this was changed with 31f6d764051 as part of #12479. That was a year and a half ago and no one has complained, so I'm guessing anyone using this feature is using an external/absolute URL. The relative URL portion of this was always meant to direct to some phpMyAdmin page anyway, so any host using this to direct to their own site was meant to use the absolute URL in the first place.

It seems right now the best solution is to adjust the documentation to show that valid phpMyAdmin paths need to have the leading `./` and trailing `?` characters to pass through the filter, and that other URLs should be a full URL with protocol (http or https only here), and leave the code how it is.

**Comment by ravgeetdhillon** [comment]
Based on this suggestion of @ibennetch, I would love to update the documentation specified here:
[Documentation](https://docs.phpmyadmin.net/en/latest/config.html#cfg_NavigationLogoLink).
I am also a GSOC '19 aspirant and want to contribute to phpMyAdmin as much as possible.
