### ISSUE TITLE
Error trying to connect to mysql

### ISSUE THREAD

**Issue by patricknn** [phpmyadmin/phpmyadmin#15063]
### Describe the bug

I just installed the version phpMyAdmin.noarch 0:4.8.5-1.el7.remi using yum on my Centos 7 server and I'm trying to connect to my mysql server that is in another physical server/different IP

I use PHP 5.6.4 on my server

Error that I receive: mysqli_real_connect(): (HY000/2002): No such file or directory

My config.inc.php is just the line with my host IP

$cfg['Servers'][1]['host'] = 'xxx.xxx.xxx.xxx';

### Server configuration

- Operating system: Centos 7
- Web server: Nginx
- Database version: Mysql 8
- PHP version: 5.6.4
- phpMyAdmin version: phpMyAdmin.noarch 0:4.8.5-1.el7.remi

Does anyone know what should I do?

**Comment by AghaSaad04** [comment]
Hey @patricknn, Can you share some Screenshots to better understand the problem?

**Comment by patricknn** [comment]
Like this?

https://imgur.com/a/TYxJBEv

If you need anything else, let me know

**Comment by AghaSaad04** [comment]
@patricknn is there any config.sample.inc.php file in your local repository?

**Comment by patricknn** [comment]
No, those are the files inside my libraries folder

advisory_rules.txt             
config.default.php  
information_schema_relations.inc.php  
replication.inc.php           
tbl_columns_definition_form.inc.php  
vendor_config.php
check_user_privileges.inc.php  
config.inc.php      
db_table_exists.inc.php  
language_stats.inc.php                
tbl_common.inc.php
config.values.php   
error.inc.php            
mult_submits.inc.php                  
server_common.inc.php         
tbl_partition_definition.inc.php
common.inc.php                 
db_common.inc.php   
hash.lib.php             
mysql_relations.inc.php               
special_schema_links.inc.php  
user_preferences.inc.php

**Comment by AghaSaad04** [comment]
Okay.
Compare your 'authentication type' thing in config.inc.php with the below one. 

![image](https://user-images.githubusercontent.com/36513474/54852198-f2818980-4d0d-11e9-99d0-7cd2504e5a42.png)

**Comment by patricknn** [comment]
my mysql server is not in the same phpmyadmin server so I need to change the host parameter to my mysql server IP
also, my root username has a password, so, if I set AllowNoPassword to true will not work.

**Comment by chiragsharma111** [comment]
Hi @patricknn , @AghaSaad04.
Guys, the file 'config.sample.inc.php' is in 'phpMyAdmin' folder.
Try setting the host value = '127.0.0.1' (localhost ip)
Then set the 'AllowNoPassword' = 'false'
![Screenshot (1162)](https://user-images.githubusercontent.com/22794080/54862724-dceb7e80-4d64-11e9-8641-f1b698c3f2f2.png)
You can see the ip of your localhost using cmd> ' ipconfig/all ' (for windows) and ifconfig (for linux)

**Comment by patricknn** [comment]
@chiragsharma111 there is no config.sample.inc.php at the phpMyAdmin's folder and my host it is not in the same server where phpMyAdmin is installed, so I need to set host to my Mysql server IP.

The error persists.

**Comment by mohdluqman** [comment]
@patricknn You can connect to remote MySql connection in PhpMyAdmin in following two ways

1. Create an SSH tunnel to remote server MySql server & Then connect to local port. You have to periodically check the opening of the SSH tunnel.

- `ssh -NL 3307:localhost:3306 root@REMOTE_HOST` //pass this command to phpmyadmin server shell
- `#Edit following lines in config.inc.php`
- `$cfg['Servers'][$i]['host']          = '127.0.0.1';`
- `$cfg['Servers'][$i]['port']          = '3307';`
- `$cfg['Servers'][$i]['connect_type']  = 'tcp';`

2. Allow 3306 port (or whatever port number enabled on the remote mysql server) on remote server from firewall & then check remote mysql is listening remote connections or not on the enabled port. If not listening, change following line on **my.cnf**
`bind-address = 127.0.0.1`
to
` #bind-address = 127.0.0.1`
Then configure phpmyadmin config.php to listen on that server:port address. Root account are disabled by default for remote access. To enable it, connect to mysql with root access, then do following queries.

- `GRANT ALL PRIVILEGES ON *.* TO 'USERNAME'@'IP' IDENTIFIED BY 'PASSWORD';`
- `FLUSH PRIVILEGES;`
- `exit; or \q`
USERNAME can be any user account which now will have root like access & can be remotely accessed.

Sorry for any typo.

**Comment by patricknn** [comment]
@mohdluqman My Mysql Server is in the same datacenter of the phpMyAdmin server and all the configs are working to connect to this server.

The phpMyAdmin server is also my script server where there is a bunch os PHP scripts which connects to this mysql server. All of my scripts are connecting to my Mysql Server fine.
In my Mysql Server, my Firewall is already configured to accept connections from the 3306 port and I also can connect to the same server using mysql Workbench from my PC once PhpMyAdmin it is not working.
All these things that you said I already did and I have no connection, only the same error that makes no sense to me: mysqli_real_connect(): (HY000/2002): No such file or directory

**Comment by patricknn** [comment]
I created a PHP file in my server with the example of the mysql_real_connect located in this url: http://php.net/manual/pt_BR/mysqli.real-connect.php

I was able to connect to my mysql server fine.

> <?php

$link = mysqli_init();
if (!$link) {
    die('mysqli_init failed');
}

if (!mysqli_options($link, MYSQLI_INIT_COMMAND, 'SET AUTOCOMMIT = 0')) {
    die('Setting MYSQLI_INIT_COMMAND failed');
}

if (!mysqli_options($link, MYSQLI_OPT_CONNECT_TIMEOUT, 5)) {
    die('Setting MYSQLI_OPT_CONNECT_TIMEOUT failed');
}

if (!mysqli_real_connect($link, 'localhost', 'my_user', 'my_password', 'my_db')) {
    die('Connect Error (' . mysqli_connect_errno() . ') '
            . mysqli_connect_error());
}

echo 'Success... ' . mysqli_get_host_info($link) . "\n";

mysqli_close($link);
?>

**Comment by ibennetch** [comment]
Hello,

I wonder if your config.inc.php is being read; the first thing I suggest trying is adding another line like `die("config.inc.php is being read properly");` to `config.inc.php` and trying to load phpMyAdmin again; you'll see the message if everything is working correctly but the login page if your config.inc.php is being ignored (which could mean a permission problem, it's in the wrong directory, or some other similar problem).

Assuming that config.inc.php is being read correctly and you're still having the problem, here are some more thoughts:

The error message you're getting is consistent with a *socket* connection type, whereas you've defined a TCP/IP connection in `config.inc.php`. I'm not sure if the package manager might have put in some direct reference to the socket, overriding your changes. The I presume the package keeps config files in `/etc/phpmyadmin/` so you could try grepping for the word 'socket' (`grep -R socket /etc/phpmyadmin/*`) to see if there is some other change there.

The `$cfg['Servers'][$i]['connect_type']` configuration directive has been removed (starting with phpMyAdmin 4.7.0) and the connection type is determined by the hostname ('localhost' uses socket connections, any IP address or hostname will use TCP/IP networking). Since you've defined an IP address, the most likely explanation is that something else is changing this value.

You could try [installing your own phpMyAdmin](https://docs.phpmyadmin.net/en/latest/setup.html), just for testing purposes; since I'm not very familiar with what changes are done by Remi for those packages I'm afraid I don't have a good answer for where to look for any modifications about this.

I'm not really sure what the question about `config.sample.inc.php` was about; the configuration file is `config.inc.php` and since it's a package managed installation, it's likely that file is in `/etc/phpmyadmin/config.inc.php` rather than in the main phpMyAdmin folder.

**Comment by patricknn** [comment]
Hi @ibennetch you are correct at your first guess, the `config.inc.php` of the `phpMyAdmin/libraries` folder is not being read, so I went to the `/etc/phpMyAdmin` folder and I found another `config.inc.php`.

I changed the host parameter in this config and it did not work either, so I tried to add the `die` line to make sure that the `config.inc.php` is being read and it is not.

Now I don't now where should I put the config.inc.php or find inside the phpMyAdmin code where this config should be.

Any Idea?

**Comment by patricknn** [comment]
Well, I finally did it
The issue is that the `/etc/phpMyAdmin/config.inc.php` was not being read, so I did 2 things

first I changed the file ownership `chgrp -R nginx /etc/phpMyAdmin` and I restarted php-fpm
It now reading the file 

Thank you for your all messages

**Comment by ibennetch** [comment]
I'm so glad you sorted it out!

Thanks for the community coming together to try to help, too.
