### ISSUE TITLE
Add Export SQL option for a raw query

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15064]
### Describe the bug

Execute
```sql
select 1 a union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 union all 
select 1 
```
Go to export below results
No sql option on export page ..

Similar to #14775

**Comment by adityasanil** [comment]
I would like to work on this with you.

**Comment by williamdes** [comment]
@adityasanil Yes, go ahead, you can open a pull-request if you find how to solve the issue! 
I will help you if you need :)

**Comment by josemmo** [comment]
For anyone trying to fix this, the bug seems to be related to the "single_table" parameter.

`ExportSql.php` will only initialize itself if the following conditions are met:
https://github.com/phpmyadmin/phpmyadmin/blob/1303def5dfa336bf434de6eea1752472a5ef18c8/libraries/classes/Plugins/Export/ExportSql.php#L72-L81

But "single_table" is never set to true when executing the given query as [Query::getAll](https://github.com/phpmyadmin/sql-parser/blob/08bb9506b65bb361a78453aebd18669e324a4101/src/Utils/Query.php#L403) can't find any tables (see line 4940):
https://github.com/phpmyadmin/phpmyadmin/blob/4d9da964692b4fb647465073024a3f8475e5c7b3/libraries/classes/Display/Results.php#L4935-L4942

---

Anyway, the export neither works as expected when choosing other options (e.g. XML) as it incorrectly assumes we're working on the first table of the current database instead of the one from the query.

**Comment by amarjitsingh52922** [comment]
@williamdes is anyone working on this issue? if not i would like to work on it

**Comment by williamdes** [comment]
@amarjitsingh52922 You can work on this issue, would be great if you find a fix !

**Comment by saurass** [comment]
@williamdes @ibennetch  I have done some work related to this, I am opening a PR here.
