### ISSUE TITLE
Safe deletion of database and tables , or providing a recycle bin for databases so we can restore our dropped databases later when we required.

### ISSUE THREAD

**Issue by agasheaditya** [phpmyadmin/phpmyadmin#15082]
### Describe the solution you'd like

Safe deletion of database and tables, or providing a recycle bin for databases so we can restore our dropped databases later when we required.

### Additional context

- phpMyAdmin version:

**Comment by agasheaditya** [comment]
We can add database by default namely "trash" and then before deletion we can ask for move to trash of delete permanently.

**Comment by AghaSaad04** [comment]
Hey @agasheaditya. Can you please fill up the above thing for the better understanding of the problem you are facing or the feature you want.

**Comment by lem9** [comment]
I believe that the confirmation warnings we get when deleting tables or databases via the UI are sufficient. Moving everything to a recycle bin could be time-consuming and phpMyAdmin should not replace a backup solution.

**Comment by agasheaditya** [comment]
But we can add a option like 'move to trash' or 'delete/drop'. and also it will be helpful if we want to refer old databases which we have deleted already .

**Comment by ibennetch** [comment]
The problems of providing a trash can/recycling bin are numerous and the potential for us to get blamed if something goes wrong is high. I prefer not to add such a feature.

Specific problems that come to mind are:

* many users have shared hosting situations where they are only given access to one database,
* how would we handle garbage collection/clearing the trash,
* there are scenarios where such a copy/move operation would take a non-trivial amount of time, we would have to deal appropriately with the data in the event such an operation is interrupted

These are some concerns that come to my mind, but regardless I think it’s on the user to manage their data responsibly and also to ensure that proper backups are in place.

**Comment by sudoranger** [comment]
No need for a recycle bin. Just export your .sql and put it somewhere else as your own personalized recycle bin be it your local disk or cloud storage plus encryption.

Regarding the shared hosting it is possible that phpmyadmin can have a bin per user basis so they can manage those deleted databases individually without worrying about garbage collection. However, this will significantly consume more storage for the service provider not to mention add more filesize to the source not everyone needs.

Slight off-topic: I tend to reply this specific topic because few months ago someone requested for an undo feature in Telegram. The core developers added it and now the UX isnreally terrible in iOS. The 5 seconds notification hides the main navigation tab everytime I delete/clear a history. This wasted a lot of my time as I do cleaning frequently. I can’t report the issue because they are using their own report system and lazy to register. I made the decision to adapt but honestly this undo/bin or second thought stuff is terrible. A confirmation button is more than enough for accidentally deletion but a bin would be overkill.

/thanks
