### ISSUE TITLE
Problem in spatial queries in MariaDB 

### ISSUE THREAD

**Issue by kndol** [phpmyadmin/phpmyadmin#15109]
```sql
ST_GeomFromText('POINT(longitude latitude)', srid)
```
 is a correct query.
But phpmyadmin makes query with 
```sql
ST_GeomFromText('\'POINT(longitude latitude)\', srid')
```
, and the result is null.

- Operating system: UNIX
- Web server:
- Database version: 10.1.13-MariaDB
- PHP version: 7.0.0p1 
- phpMyAdmin version: 4.8.5

**Comment by williamdes** [comment]
@kndol Thanks for the report, totally explains why I could not make the UI work each time I tried !

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/71360114-fbe69d80-258e-11ea-98da-7866c3abfc26.png)

**Comment by ShailuJain** [comment]
Hey @williamdes 
I checked into the issue and found that typing `'POINT(1 2)',0` into the text field produces the error but if `POINT(1 2),0` is typed there is no error. So how should we proceed with the issue?

**Comment by williamdes** [comment]
@ShailuJain If all MySQL and MariaDB versions agree that `POINT(1 2),0` is a valid syntax then we can safely remove the quotes
If you find some documentation can you post it here ?

**Comment by ShailuJain** [comment]
In my opinion if `POINT(1 2),1` is given the executing query will be
 `INSERT INTO table_name (id, shape) VALUES (NULL, ST_GeomFromText('POINT(1 2),0'))` 
which is a valid query and if given `'POINT(1 2)',1`, 
 `INSERT INTO table_name (id, shape) VALUES (NULL, ST_GeomFromText('\'POINT(1 2)\',0'))` 
is produced which is why this error is produced. But then too if a find some documentation i will post it here.
