### ISSUE TITLE
phpMyAdmin unusable with user having WITH GRANT OPTION privileges and an existing Configuration Storage database

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15123]
### Describe the bug

All attempts to access tables, databases, anything is blocked.

### To Reproduce

- Create a user, GRANT him `GRANT` and select the option to create a database and give all privileges to the user.
- Login to the user, try to browse his database

NOTE: the user can see other databases witch is for me quite strange.

### Screenshots

![User](https://user-images.githubusercontent.com/7784660/55233804-f0498e80-5229-11e9-977a-33ea6faab617.png)

### Server configuration

- phpMyAdmin version: 4.8.6, 5.0.0-dev

**Comment by williamdes** [comment]
Loading forever when clicking an owned database
![image](https://user-images.githubusercontent.com/7784660/55233939-41598280-522a-11e9-8f7f-40d37550064d.png)

When clicking onto a non owned database
![image](https://user-images.githubusercontent.com/7784660/55233962-5504e900-522a-11e9-8afa-046e900abced.png)

The db structure page if you press <kbd>F5</kbd> after selecting a database
![image](https://user-images.githubusercontent.com/7784660/55234039-79f95c00-522a-11e9-8641-34eb1e47836a.png)

The export page
![image](https://user-images.githubusercontent.com/7784660/55234103-a44b1980-522a-11e9-9196-7f6848771dfc.png)

**Comment by williamdes** [comment]
And so much more, unusable.

**Comment by williamdes** [comment]
The storage analysis

![image](https://user-images.githubusercontent.com/7784660/55234268-14f23600-522b-11e9-9fc4-a20de59e41cd.png)

**Comment by ibennetch** [comment]
This is interesting because the ability to see all databases comes from MySQL directly, even when testing from the command-line client I can see all databases. The documentation doesn't seem to cover this scenario, so it's not clear whether it's a bug or the intended behavior.

As for the rest, I'm having trouble reproducing. Have you configured the phpMyAdmin Configuration Storage database in config.inc.php along with a controluser? I have all of this configured. The export error and non-owned database error both seem to be related to the behavior of MySQL — currently, I believe phpMyAdmin tests if it sees the pmadb database (and probably the individual tables), but doesn't try to read or write data until it actually needs to. If MySQL would behave as one would expect, this wouldn't be a problem, but MySQL shows us the database and table but won't let us use it. That causes the error.

I'm guessing a bit, but think a good solution would be to test if we're a user account that has `WITH GRANT OPTION` but not global or database-specific select/insert/update privileges for the pmadb, and bypass the Configuration Storage in that case. We can also add a bit to the documentation about how this won't work.

The combination of no control user with an existing pmadb that the user has no privileges to use but can see causes errors in many ways. This is an interesting edge case.

**Comment by williamdes** [comment]
> Have you configured the phpMyAdmin Configuration Storage database in config.inc.php along with a controluser?

I my config there is nothing more than simple multiple servers :)
```
<?php
declare(strict_types=1);
$i = 0;
$i++;
$cfg['Servers'][$i]['verbose'] = 'MariaDB 1 (cookie)';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'mariadb1.phpmyadmin.local';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = true;

// And more servers
```
