### ISSUE TITLE
[UI] Horrible white square

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15127]
### Describe the bug

![image](https://user-images.githubusercontent.com/7784660/55263039-185be080-5270-11e9-8cf6-0fe5272e391d.png)

This occurs for some reason a some time but is very annoying ...
Use designer and navigate between pages

**Comment by williamdes** [comment]
```js
$('#floating_menubar')
            .css('margin-' + left, $('#pma_navigation').width() + $('#pma_navigation_resizer').width())
```

**Comment by williamdes** [comment]
`./js/navigation.js`
```js
        $('#floating_menubar, #pma_console')
            .css('margin-' + this.left, (pos + resizer_width) + 'px');
```

**Comment by imdhruvgupta** [comment]
Hi @williamdes , I am not able to reproduce this bug. Could you please provide some steps to reproduce?

**Comment by williamdes** [comment]
@imdhruvgupta unfortunately no, I can not find a reliable way to reproduce this for now
You need to do some browsing and hope to find the issue, or best option: understand the code that generates the `margin-left`

**Comment by williamdes** [comment]
Demo servers (`root`, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)


@imdhruvgupta 
- Go to any database, do to designer, then **reload the page using <kbd>F5</kbd>** and chose reload in the designer left bar
OR
- Go to any database, do to designer, then **reload the page using <kbd>F5</kbd>** and navigate to structure

**Comment by msk4862** [comment]
I'm new here, So, can you please tell me how to test(see) my changes.
Thanks in advance.

**Comment by williamdes** [comment]
@msk4862 Follow https://github.com/phpmyadmin/phpmyadmin/issues/15127#issuecomment-487077595 to reproduce and make the fix then try to reproduce, if you can not reproduce then you fixed the bug and can create a pull-request.

**Comment by msk4862** [comment]
@williamdes That much I now, But what I wanted to know was will my fixes be visible on Demo servers ( as mentioned in [ #15127 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/15127#issuecomment-487077595) ) 

or Do I have to setup the phpmyadmin locally on my machine to check if that bug is fixed. (If yes how? because there is no setup instructions availbale)


( I know its a very silly question but I'm a beginner. So, a little help will help me a lot)

**Comment by williamdes** [comment]
@msk4862 You need to create a local phpmyadmin installation
Follow the steps:
- Fork the repository (fork button on this page)
- Clone your fork of the repository
- Create a new branch from `QA_4_9` for your fix
- Try to fix the issue
- Commit the changes (use the [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission)))
- Create a pull-request to the `QA_4_9` branch

**Comment by williamdes** [comment]
![Screenshot_20190821_084457_com android chrome](https://user-images.githubusercontent.com/7784660/63408893-4ba23600-c3f0-11e9-9b15-673c5ada43cd.jpg)

**Comment by williamdes** [comment]
The fix introduced this issue, know I understand why this line was here

**Comment by gurrrung** [comment]
Hmm, Sorry for the mistake, I will send a fix soon.

**Comment by gurrrung** [comment]
Can you help me replicate this error? I just used my Chrome Device toggle bar and visited home page, it's not there.

**Comment by gurrrung** [comment]
I found it, never mind.

**Comment by gurrrung** [comment]
I found a weird thing with `floating_menubar` when the page is alright and no white square is there it was an empty div element.
![Screenshot from 2019-08-22 15-39-40](https://user-images.githubusercontent.com/30543444/63506990-5514c680-c4f4-11e9-99a2-c807ed137944.png)
and after reloading it when that whitespace appears, it was not an empty div element but had child element which were earlier neighbours elements.
![Screenshot from 2019-08-22 15-39-20](https://user-images.githubusercontent.com/30543444/63507013-6231b580-c4f4-11e9-9a0d-455b9f5846d9.png)

**Comment by gurrrung** [comment]
Anyways my PR removes unwanted space from both the cases but we still need to give it a closer look. Actually, I guess the second one is the correct case as `floating_menubar` should contain `serverinfo`, `topmenucontainer` etc as it isn't meant to be empty all the time.
That unwanted space is also coming in this case, thus I am sure that we don't need any margin lefts here.

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/63507315-c1350180-c4d7-11e9-88e2-0b3719300eb8.png)

Okay I will test your PR
Thanks @gurrrung :)

**Comment by williamdes** [comment]
I reverted everything since this is too much of an issue to be kept as is

If you update your fix I will do a lot more testing so it does not happen again
Can you re-do the PR @gurrrung ?

**Comment by gurrrung** [comment]
Yeah sure. I will do it soon once I get time. In the meantime if someone wants to take this issue, feel free to.

**Comment by asprazz** [comment]
Hie @williamdes and @gurrrung, I noticed some strange behaviour too before reloading and after reloading the designer page. Attaching screenshots for more details about what I observed, in first screenshot (body) have padding-top to add some space for (floating-menubar) while (floating-menubar) is position fixed. In second screenshot that is after reloading it empties up the (floating-menubar). 

Coming to the point : my approach added padding body and positioning to floating navbar, the issue is solved (further tests needs to be done though) but don't know its correctness 

![Before Reloading](https://user-images.githubusercontent.com/19568165/66271094-b9f36880-e877-11e9-9c48-0d4c3e928a85.png)
![After reloading](https://user-images.githubusercontent.com/19568165/66271113-050d7b80-e878-11e9-8dff-eff72f2cf74a.png)
