### ISSUE TITLE
MySQL 8.0 password syntax error when creating a replication issue

### ISSUE THREAD

**Issue by scorobo** [phpmyadmin/phpmyadmin#15282]
### Describe the bug

I get error when change user password.

### To Reproduce

1. Go to Accounts
2. Choose an account
3. Click on Change password
4. Generate new password and click on Forward (Apply)
4. See error - on my Print Screen:

![image](https://user-images.githubusercontent.com/7784660/63976735-44df8700-cab2-11e9-9e5a-8716097ce667.png)

1. Go to Accounts
2. Choose an Account Information
3. Click on Change some information
4. Click forward (apply) om button in area "Create new user ...."
4. Generate new password and click on Forward (Apply)
4. See error - on my Print Screen:

![image](https://user-images.githubusercontent.com/7784660/63976742-49a43b00-cab2-11e9-9953-a4d1cb0dfd64.png)

### Server configuration

- Operating system: Ubuntu 18.04.1 LTS
- Web server: nginx/1.14.0 (Ubuntu)
- Database version: mysql 8.0.15-6
- PHP version: PHP 7.2.17-0ubuntu0.18.04.1
- phpMyAdmin version:    4.8.5 and  5.0.0-dev (tested on both)

### Client configuration

- Browser: Firefox latest
- Operating system: Ubuntu

###

I found only two errors, but I think, that it is incompatibility of phpmyadmin and mysql 8. 
How can I fix it?

**Comment by williamdes** [comment]
@scorobo can you paste the query here (without the password) ?

**Comment by scorobo** [comment]
> @scorobo can you paste the query here (without the password) ?

1)  SET PASSWORD FOR 'username'@'x.x.x.x' = PASSWORD('****************')
2)  GRANT USAGE ON *.* TO 'username'@'x.x.x.x'

**Comment by williamdes** [comment]
@scorobo Can you try with the next patch version (8.0.16) of MySQL ?

**Comment by scorobo** [comment]
> @scorobo Can you try with the next patch version (8.0.16) of MySQL ?

No, we can't, because it (8.0.15-6) is production server already.

**Comment by williamdes** [comment]
@scorobo Can you try the latest versions we have available on our [website](https://www.phpmyadmin.net/downloads/) ?

**Comment by d2inco** [comment]
This issue is still present with PMA 5.0.1 and Mysql 8.0.17

**Comment by williamdes** [comment]
@d2inco could you please give detailed instructions to reproduce this issue?

**Comment by d2inco** [comment]
* Build a new lab machine with CentOS 8.0, and upgrade to CentOS 8.1.
* `dnf install mysql-server`, enable it, start the server.
* run `mysql_secure_installation` to set root account password.
* Grant access to root on remote box so that I can access via phpmyadmin.
* Log into PhpMyAdmin v.5.0.1, on the remote box.
* Add User Account:  'david', '%', (password), all admin privileges, GO.
--> This does work.
* Go to replication menu, Add Slave User.   "slaveuser", any host, (password): 
--> #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'BY 'password'' at line 1
--> CREATE USER 'slaveuser'@'%' BY '***';GRANT REPLICATION SLAVE ON *.* TO 'slaveuser'@'%';

**Comment by williamdes** [comment]
Thank you so much I will try ASAP

**Comment by williamdes** [comment]
Thank you for your patience and help
This issue will be fixed in next 5.0 release
Patch: e671ee3ebb86d8ff3e9f84c37b51cfc5e98d0b31
