### ISSUE TITLE
4.9.0.1 does not comply with semantic versioning

### ISSUE THREAD

**Issue by c0m4r** [phpmyadmin/phpmyadmin#15306]
### Describe the bug

The package.json in PMA 4.9.0.1 has `"version": "4.9.0",`. This way it's not possible to distinguish version 4.9.0.1 from 4.9.0.

### Expected behavior

Either drop this way of versioning or at least add additional file like VERSION with the current version in full length.

**Comment by williamdes** [comment]
@ibennetch What should we do ?

**Comment by ibennetch** [comment]
I think you're reporting two different matters here,

1) A strict adherence to https://semver.org/ means we should have gone with 4.9.2 because a four-digit version number doesn't comply with the specification. The best response I can give is that we've been doing it that way a lot longer than the https://semver.org/ specification, and no one has brought this up, complained, or even thought about it before now. We can discuss adjusting our policies to comply with the semver specification moving forward.

2) Using "4.9.0" in `package.json` rather than "4.9.0.1". This was an oversight for which I apologize.

As for what we should do, I'm not certain that fixing the package.json file justifies releasing version 4.9.1, but I'm open to suggestions.

**Comment by williamdes** [comment]
From what I read at https://docs.npmjs.com/files/package.json#version we can use `4.9.0.1`

http://package-json-validator.com

**Comment by c0m4r** [comment]
Yeah, I assumed that it will be rather difficult for you to drop support for your long-time used versioning system. 

At first I was thinking about something like `4.9.0-1`, but the problem is that in semver `4.9.0-1` < `4.9.0`.

However, as semver documentation says:

```semver.valid(semver.coerce('42.6.7.9.3-alpha')) // '42.6.7'```

So it should be valid to use `4.9.0.1`, however it will be interpreted as 4.9.0 by semver interpreter. Still it will be helpful anyway for people who want to work around it.

**Comment by lem9** [comment]
Semantic versioning criticism (and lots of discussion) : https://gist.github.com/jashkenas/cbd2b088e20279ae2c8e

**Comment by williamdes** [comment]
We now are at 4.9.1 so I think this issue is over.
