### ISSUE TITLE
phpmyadmin API

### ISSUE THREAD

**Issue by enriquerene** [phpmyadmin/phpmyadmin#15303]
### Is your feature request related to a problem? Please describe.

The layout of phpmyadmin is good but there are some stuff I think no intuitive. I'd like to build some React App to interact with MySQL and I thought "why not use phpmyadmin as API and React consume that?". I didn't find any information about API.

### Describe the solution you'd like

I suggest implementation of API like a server. The phpmyadmin serves some routes which can be consumed from JS (or whatever).

### Describe alternatives you've considered

If API is not possible, is possible create something to allow usage of themes for phpmyadmin?

**Comment by williamdes** [comment]
cc @ibennetch @mauriciofauth

**Comment by ibennetch** [comment]
phpMyAdmin doesn't expose an API right now for many reasons, in part because that's not really what phpMyAdmin is meant to do. We historically have found that there are plenty of other libraries that allow clients to interact with MySQL directly and that exposing such a framework isn't something that many people would benefit from.

About theming, we do have quite a number of themes (https://www.phpmyadmin.net/themes/) and welcome new contributions. There's a theme generator tool that's really great (https://github.com/phpmyadmin/phpmyadmin/tree/gsoc-theme-generator) but currently works for the 4.x branch, whereas we're working towards the release of phpMyAdmin 5.0 which uses some different techniques.
