### ISSUE TITLE
Bump minimum version to PHP 7.4

### ISSUE THREAD

**Issue by MauricioFauth** [phpmyadmin/phpmyadmin#15607]
We should start to discuss when we want to drop the support for PHP 7.1, PHP 7.2 and PHP 7.3, because PHP 7.1 is no longer supported and PHP 7.2 is supported for critical security issues only.

PHP 7.4 will be the last 7.x release before the [PHP 8](https://news-web.php.net/php.internals/103862).

Another reason to chose PHP 7.4, besides the new features, is the fix for the MySQL authentication issue.

https://www.php.net/supported-versions.php

**Comment by williamdes** [comment]
For phpMyAdmin 5.1 why not, 7.x versions releases are quite close compared to 5.x versions (IMO)

**Comment by mauriciofauth** [comment]
I'm not sure about 5.1. I think we still require PHP 7.1 for 5.1 and require PHP 7.4 after the 5.1 release.

Another reason to chose PHP 7.4, besides the new features, is the fix for the MySQL authentication issue.

**Comment by ibennetch** [comment]
I think it depends on when 5.1 is released. Probably I'd want to target 5.1 for the fall of next year, so PHP 7.2 will probably still be in security support at that time. So it's likely that we'd want to drop PHP 7.2 support in 5.2.

Unless we do LTS support for 4.9 (or 5.0) and move ahead with dropping PHP older than 7.4 starting with phpMyAdmin 5.2. 

I was going to ask on the mailing list, currently we claim LTS support for 4.9, in order to support PHP versions 5.5 through 7.0. How long do we wish to maintain that LTS support, since those PHP versions are officially outdated at this point?

**Comment by ibennetch** [comment]
Note that distributions also maintain LTS versions with security fixes, such as Debian which has PHP 5.6 supported until June 2020. Theoretically, those distributions should backport their own security fixes for applications like phpMyAdmin, but sometimes it's helpful to those maintainers if we maintain an LTS release (for security fixes only) even after PHP has officially ended support.

**Comment by OlafvdSpek** [comment]
If you want to support Debian LTS:
Debian 9 with PHP 7.0 is supported until June 2022..

**Comment by mauriciofauth** [comment]
Debian | PHP | EOL | EOL LTS
------ | --- | --- | ---
8 _Jessie_  | 5.6 | June 2018 | June 2020
9 _Stretch_ | 7.0 | June 2020 | June 2022
10 _Buster_ | 7.3 | ~2022 |

**Comment by mauriciofauth** [comment]
Maybe we can sync our PHP versions and LTS dates with Debian. That way we will no longer have to discuss PHP upgrades and LTS dates.
What you think about this idea?

**Comment by williamdes** [comment]
Very very good idea, and the users will upgrade their distributions because everyone will stop supporting updates

**Comment by mauriciofauth** [comment]
> Maybe we can sync our PHP versions and LTS dates with Debian.

If we agree with this, phpMyAdmin 4.9 will be LTS until June 2022 (to support PHP 7.0) and we can require PHP 7.3 in phpMyAdmin 5.2 or even in 5.1 (current master branch).

**Comment by ibennetch** [comment]
@remicollet Would you like to comment here about what sort of LTS would be helpful from us?

**Comment by OlafvdSpek** [comment]
> Maybe we can sync our PHP versions and LTS dates with Debian. 

What about Ubuntu, CentOS, RHEL and others? ;)

> That way we will no longer have to discuss PHP upgrades and LTS dates.

That'd guide end-of-life dates,  but what'd be the rule for minimum supported versions?

> and we can require PHP 7.3 in phpMyAdmin 5.2 or even in 5.1 (current master branch).

7.3 is covered by pMA 5.0 so you could bump to 7.4 as well.

**Comment by mauriciofauth** [comment]
> That'd guide end-of-life dates, but what'd be the rule for minimum supported versions?

Since Debian 10 has PHP 7.3, we can require PHP 7.3 for new releases and future LTS when the time comes.

**Comment by OlafvdSpek** [comment]
It'd be nice if you could sync releases with Debian such that Debian 11 ships with a fresh pMA release.
This would require a release before (probably) March 2021.

**Comment by remicollet** [comment]
@OlafvdSpek why should a project take care specifically of Debian, when tons of other distro exist ?

* Fedora 30/31 have 7.3
* Fedora 32 will have 7.4
* RHEL / CentOS 7 have 5.4 (default version) and 7.2 and soon 7.3 (RHSLC 3.4)
* RHEL / CentOS 8.0 have 7.2
* RHEL 8.1 have 7.2 or 7.3 (CentOS 8.1 should be released soon)

IMHO **7.2** is a reasonable target, as the version is still maintained

**Comment by OlafvdSpek** [comment]
> @OlafvdSpek why should a project take care specifically of Debian, when tons of other distro exist ?

I already mentioned them in https://github.com/phpmyadmin/phpmyadmin/issues/15607#issuecomment-562823457

That said, which ones ship a phpmyadmin package?

> IMHO **7.2** is a reasonable target, as the version is still maintained

It's about the phpmyadmin version that might be released at the end of 2020. By that time 7.2 runs out of support.

**Comment by ibennetch** [comment]
To consolidate everyone's ideas and try to reach a conclusion, this is what I'm coming up with:

### phpMyAdmin 4.9
* Requires PHP 5.5 or newer
* We'll provide LTS (security fixes only) until June 2020 to support Debian Stretch (which has PHP 
7.0)
* Bugfix support will end when 5.0 is released, probably 4.9.3 will be the last release alongside 5.0.0

### phpMyAdmin 5.0
* Requires PHP 7.1
* No LTS and all support ends after 5.1 is released
* Release will probably occur this month (December 2019)

### phpMyAdmin 5.1
* Potentially require PHP 7.2, although I don't recall any clear advantage from moving from 7.1 to 7.2
* Possible release approximately December 2020 (after GSoC 2020, but before Debian freezes in March 2021)

## Discussion

1. I think we all accept that phpMyAdmin 5.0 will ship with the current requirement of 7.1.3, because changing the requirement after the release candidate was published is not ideal

2. Even though phpMyAdmin 4.9 LTS would cover Debian (and others) that use PHP 7.1, which could allow us to require PHP 7.4 for our release 5.1, but that would mean many users would be stuck on an older phpMyAdmin version. It's an interesting discussion about whether those users want the newest phpMyAdmin or care about new features. It could be a perfectly reasonable thing for us to maintain phpMyAdmin 4.9 for old PHP and bugfixes for another year or two — and phpMyAdmin 5.x for PHP 7.4 and new features, but the work of maintaining two diverging codebases makes that undesirable.

    I don't see an advantage for us moving phpMyAdmin 5.1 to PHP 7.2 from 7.1. If we're going to drop support for older PHP versions, it should be for a good reason (such as the drastic changes from PHP 5 to 7), and I don't recall there being a major change from PHP 7.1 to 7.2. What I'm trying to say is that I don't think it's worth changing our requirements from 7.1 to 7.2, and I think it's too soon to change to anything newer than that right now. I'd vote to keep future development locked to PHP 7.1 for now.

That's not much of a change for us, so perhaps everyone will be unhappy with the result. I invite you to tell me what I've gotten wrong :)

**Comment by OlafvdSpek** [comment]
> If we're going to drop support for older PHP versions, it should be for a good reason.

Such as those versions being without security support?

**Comment by williamdes** [comment]
@OlafvdSpek 
> That said, which ones ship a phpmyadmin package?

Now, us, #15236, as the "phpMyAdmin packaging team"

> Bugfix support will end when 5.0 is released, probably 4.9.3 will be the last release alongside 5.0.0

@ibennetch could we have one last version with the 5.0.0 one to close bug-fix support on 4.9 ?

**Comment by williamdes** [comment]
> I'd vote to keep future development locked to PHP 7.1 for now.

I would agree, @mauriciofauth except for LTS reasons what would be the benefits ?

**Comment by ibennetch** [comment]
>> If we're going to drop support for older PHP versions, it should be for a good reason.
>
> Such as those versions being without security support?

It's hard to define what that means, though — the PHP project has a date where security support ends, then each distribution also ends their LTS period at a different time. It's true that no one has shown an example here of a distribution that is currently maintaining 7.1, so I guess I can't make a strong argument for maintaining support for 7.1 over moving to 7.2.

**Comment by ibennetch** [comment]
> @ibennetch could we have one last version with the 5.0.0 one to close bug-fix support on 4.9 ?

Yes, I am currently planning to release 5.0.0 and 4.9.3 at the same time later this month.

**Comment by williamdes** [comment]
Here is a dependency diff for the packaging teams (little bit tweaked so it is readable)
https://www.diffchecker.com/rAftjfM6


```diff
<         "php": ">=5.5.0",
>         "php": "^7.1.3",
---
<         "ext-ctype": "*",
>         "ext-iconv": "*",
---
<         "phpmyadmin/sql-parser": "^4.3.2",
>         "phpmyadmin/sql-parser": "^5.0",
---
<         "psr/container": "^1.0",
---
>         "symfony/config": "^4.2.8",
>         "symfony/dependency-injection": "^4.2.8",
>         "symfony/polyfill-ctype": "^1.8",
>         "symfony/yaml": "^4.2.8",
>         "williamdes/mariadb-mysql-kbs": "^1.2",
---
<         "twig/twig": "^1.34 || ^2.0",
>         "twig/twig": "^2.4",
---
<         "symfony/expression-language": "^3.2 || ^2.8",
>         "symfony/expression-language": "^4.2",
```

**Comment by remicollet** [comment]
If phpMyAdmin 4.9 supports up to 7.0 and 5.1 7.4+, this will mean that 7.1 to 7.3 users won't have any officially supported version ?

**Comment by mauriciofauth** [comment]
> If phpMyAdmin 4.9 supports up to 7.0 and 5.1 7.4+, this will mean that 7.1 to 7.3 users won't have any officially supported version ?

@remicollet phpMyAdmin 4.9 supports PHP 5.5 to 7.4, but it will be an LTS to support PHP 5.5 to 7.0, since phpMyAdmin 5.0 requires PHP 7.1+.

**Comment by remicollet** [comment]
> phpMyAdmin 4.9 supports PHP 5.5 to 7.4, but it will be an LTS to support PHP 5.5 to 7.0

Really need to be clarified.
7.4 or 7.0 ?

> phpMyAdmin 5.0 requires PHP 7.1+.

But this is not a LTS version, thus if 7.1 support is dropped in 5.1, what will be the supported version ?

To be clear, I think all PHP versions should be supported by a phpMyAdmin LTS version.

**Comment by OlafvdSpek** [comment]
> > phpMyAdmin 4.9 supports PHP 5.5 to 7.4, but it will be an LTS to support PHP 5.5 to 7.0
> 
> Really need to be clarified.
> 7.4 or 7.0 ?

Both ;)
PHP 7.0 is supported by pMA 4.9 but not by 5.0
PHP 7.1 is supported by pMA 4.9 and 5.0

> But this is not a LTS version, thus if 7.1 support is dropped in 5.1, what will be the supported version ?

Presumably pMA 5.2
