### ISSUE TITLE
editing a date adds .00000 and breaks re-editing the date using the picker

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#15629]
I had some issues with the trailing `.00000` when inserting dates

Ref: #582
Ref: b495061cdf01a63d43f521a75ad184e9d8b82e2d

_Originally posted by @williamdes in https://github.com/phpmyadmin/phpmyadmin/issues/14986#issuecomment-486311712_

**Comment by AshwinGinoria** [comment]
@williamdes how can I reproduce this issue ??

**Comment by williamdes** [comment]
@AshwinGinoria in-line edit a row with a dare :)

**Comment by williamdes** [comment]
cc @kasunchathuranga

**Comment by williamdes** [comment]
```sql
CREATE TABLE `dateTimes`(
    `date` DATE NOT NULL,
    `datetime` DATETIME(6) NOT NULL,
    `ts` TIMESTAMP(6) NOT NULL,
    `time` TIME(6) NOT NULL,
    `year` YEAR(6) NOT NULL
) ENGINE = INNODB; ALTER TABLE
    `dateTimes` ADD UNIQUE(`date`, `datetime`, `ts`, `time`, `year`);
INSERT INTO `dateTimes`(`date`, `datetime`, `ts`, `time`, `year`)
VALUES(
    '2020-01-15',
    '2020-01-16 22:00:34.000396',
    '2020-01-01 22:00:34.000520',
    '22:00:34.000314',
    '2019'
);
```

**Comment by manusfreedom** [comment]
Please fix the UI part too, because when edit a line, it resize the column while keeping displaying additional `.00000`, if you refresh the page `.00000` disappear.
And if we past (CTRL-V) a date like `0000-00-00 00:00:00`, it's add `.00000`.

Why the picker is directly open when using this inline edit ? It must be close like using the full form.
(Indicate me if I must open another issue for that)

**Comment by williamdes** [comment]
> Why the picker is directly open when using this inline edit ? It must be close like using the full form.

I am not sure the behaviour should be changed, open or closed by default could be set by a setting and everyone would be happy.
If you implement such setting you can open a pull-request :)
