### ISSUE TITLE
Focus of active tab is lost by clicking refresh option provided by phpmyadmin.

### ISSUE THREAD

**Issue by Tarun-Kachhela** [phpmyadmin/phpmyadmin#15693]
### Describe the bug

After using refresh feature provided by pma page the focus of the active tab is lost and setting icon at the top right of the PHPMyAdmin page is not visible.

### Steps to reproduce the behavior:
1. Go to pma page, select the any table 
2. Click on the Refresh option provided by pma.
### Before clicking refresh button
![SharedScreenshot](https://user-images.githubusercontent.com/40022528/71423941-0e59f780-26b3-11ea-9ffb-96e39f419df2.jpg)
### After clicking the refresh button
![CorrectLostFocusNotVisibleSetting](https://user-images.githubusercontent.com/40022528/71423978-6ee93480-26b3-11ea-9c3b-5f7125c3567b.jpg)

3, The focus of the active tab has been lost And the setting icon at the top right of the page is not visible 

### Expected behavior
The setting icon should be visible, The Focus of the active tab should still be active after clicking refresh option.

**Comment by williamdes** [comment]
Reproduced, thank you for reporting this issue !

**Comment by Tarun-Kachhela** [comment]
Can I search a solution for this @williamdes

**Comment by williamdes** [comment]
@Tarun-Kachhela yes, you are welcome !
Please use `QA_4_9` branch

**Comment by Tarun-Kachhela** [comment]
can you guide me with the basic process? This is my first contribution

**Comment by williamdes** [comment]
Here is my first contribution guide:
- Fork the repository
- Clone the fork locally into a web folder eg:`/var/www`
- Checkout `QA_4_9` branch since it is a fix and create a new branch from `QA_4_9`
- Run `composer install`
- Create a `config.inc.php` if needed using the example file 
- Access your phpmyadmin website and login
- Find or apply the fix you created
- Do not forget to use [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))
- Push your changes and open a pull-request to this repository, branch: `QA_4_9`

Do you have any more questions @Tarun-Kachhela ?

**Comment by Tarun-Kachhela** [comment]
No.
Thanks for the help

**Comment by victorphoenix3** [comment]
@Tarun-Kachhela  sorry I didnt realize you were working on this. But I think I found a possible fix.
