### ISSUE TITLE
Layout: Bad alignment of sticky column headers after scrolling

### ISSUE THREAD

**Issue by markus-ksg** [phpmyadmin/phpmyadmin#15806]
### Describe the bug

When browsing a table, after scrolling down the sticky column headers are not aligned with the column data any more

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/index.php?route=/sql&server=1&server=1&db=opengis&table=world_borders&pos=0
2. Scroll down until the column headers reach the top of the page
=> Headers jump to the right; they are not aligned with the data any more

### Expected behavior

Layout of header row should not change when the headers go into sticky mode.

### Screenshots

![phpmyadmin](https://user-images.githubusercontent.com/47326631/72617909-4d8a0a00-393a-11ea-8971-67677a4a1781.png)

### Server configuration

- phpMyAdmin version: all 5.x until now

### Client configuration

- Browser: Firefox, Chrome
- Operating system: Windows 10

**Comment by jrdevforlife** [comment]
It's a second table + thead which is getting displayed on top of that table when the original thead scrolls up. Can be fixed with position: sticky; and top: 59.5667px; on that original thead from what I've simulated.

**Comment by gurrrung** [comment]
@jrdevforlife Can you make a PR or help me understand how you resolved it so that I can make a PR?

**Comment by williamdes** [comment]
> Has no IE11 Support, but there are polyfills available.

No problem for me, they will have the bug and that will be okay. IE is now replaced by Edge ^^
And Edge will be Chrome soon :laughing:

**Comment by jrdevforlife** [comment]
> @jrdevforlife Can you make a PR or help me understand how you resolved it so that I can make a PR?

@gurrrung 

It's currently in Projects: issues; and marked as 'to be fixed soon'. Guess you don't have to take action here. But if you wanna do it anyway for the sake of learning or whatever, so here's how I would go about it if I had no clue.

- Find the corresponding table element in your devtools and check what class it has
- Since I would bet the scroll event is controlled with JS through jQuery, I did use the GitHub repo search functionality and search for that class name
- You wanna disable the current feature which enables the sticky table, then remove the sticky table as a whole from the corresponding twig file
- Last but not least, you wanna give the actual thead element position: sticky and the top value at which it should become active

There are probably plenty of ways to get that done, but that would be mine. I would obviously put some effort into it to get that jQuery killed 🤮

**Comment by williamdes** [comment]
> There are probably plenty of ways to get that done, but that would be mine. I would obviously put some effort into it to get that jQuery killed 

I agree !

**Comment by LordRegentTB** [comment]
I have locally developed and tested the code to fix this issue in v4.9 and v5.0. Changing to use CSS `position: sticky` is modern, but patching the issue retains support for IE11 and other older browsers. 

I don't intend to be rude, but I've been lurking here wanting to publish several patches, and the docs haven't helped me dive in; should I patch only master (and let someone [else] migrate it to earlier versions), or do I need to do PRs against QA_4_9 and QA_5_0 and STABLE and master?

**Comment by williamdes** [comment]
> I have locally developed and tested the code to fix this issue in v4.9 and v5.0. Changing to use CSS `position: sticky` is modern, but patching the issue retains support for IE11 and other older browsers.
> 
> I don't intend to be rude, but I've been lurking here wanting to publish several patches, and the docs haven't helped me dive in; should I patch only master (and let someone [else] migrate it to earlier versions), or do I need to do PRs against QA_4_9 and QA_5_0 and STABLE and master?

@LordRegentTB You can open a PR from and to the branch QA_5_0
Then I will merge your PR into QA_5_0 and QA_5_0 into master

QA_5_0 is merged into STABLE at each release.

Forget QA_4_9, we only accept security fixes ;)

Do not forget to use [`--signoff`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff) option to add your signoff line in the commit body, please use your real name (this option is an agreement to our [policy](https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission))

**Comment by williamdes** [comment]
Closed by #16277
