### ISSUE TITLE
Autocomplete makes use of phpmyadmin impossible on mobile

### ISSUE THREAD

**Issue by braindigitalis** [phpmyadmin/phpmyadmin#15852]
### Describe the bug

Using latest mobile chrome on Android, phpmyadmin can't be used to issue queries because the auto complete randomly inserts keywords whenever the cursor moves.

### To Reproduce

1. Click "edit inline"
2. Attempt to type or tap to move cursor to new position

### Expected behavior

Editor should be usable.

### Screenshots

![Screenshot_20200126-101727](https://user-images.githubusercontent.com/1556794/73133796-9f5f1e00-4025-11ea-8cf5-5f6f0344fe10.jpg)

### Server configuration

- Operating system: Debian 10
- Web server: Apache 2.4
- Database version: MariaDB 10
- PHP version: 7.3.11
- phpMyAdmin version: 4.6.6deb4

### Client configuration

- Browser: Mobile chrome latest stable
- Operating system: Android 9

### Additional context

Debian's packaged phpmyadmin

**Comment by williamdes** [comment]
Hi @braindigitalis  
I could not reproduce this issue on 4.9.x https://demo.phpmyadmin.net/QA_4_9/db_sql.php?db=opengis&server=1

Demo servers (`root`, no password)
- [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

You can upgrade the version you are using with our PPA #15515 or see the progress of packaging 4.9.x in debian in #15236   

I hope you can reproduce this issue on 4.9.x because if not you can close this issue.
Thank you for report

**Comment by braindigitalis** [comment]
Thanks very much!

I have installed 4.9 from PPA, and this appears to have fixed the issue.
