### ISSUE TITLE
Misleading translation to portuguese

### ISSUE THREAD

**Issue by apaulo** [phpmyadmin/phpmyadmin#15861]
Hi,

When exporting data I noticed the word "dump" has been translated to "eliminar".
"Eliminar" means "delete", in portuguese.

So you have (in portuguese):
"Dump some row(s)" and "Dump all rows" translated as "Delete some row(s)" and "Delete all rows"... it's pretty scary.

### To Reproduce

1. Change language do Portuguese
2. Select a table
3. Click on 'export'

### Expected behavior

Translation should be: "Exportar alguma(s) linha(s)" and "Exportar todas as linhas"

### Server configuration
- phpMyAdmin version: 4.9.0.1

**Comment by ibennetch** [comment]
Hi,

Thanks for your detailed report. The easiest way to fix translations is
through the Weblate interface at
https://hosted.weblate.org/projects/phpmyadmin/ — since you already have a
GitHub account it should be pretty straightforward.

Specifically, (if these links work correctly), you may wish to review these
three items:
*
https://hosted.weblate.org/translate/phpmyadmin/4-9/pt/?q=eliminar&offset=15
*
https://hosted.weblate.org/translate/phpmyadmin/4-9/pt/?q=eliminar&offset=19
*
https://hosted.weblate.org/translate/phpmyadmin/4-9/pt/?q=eliminar&offset=20

I often hesitate to make such changes myself when I don't speak the
language, it's usually better to have someone who is fluent supervise the
changes.

Best wishes

**Comment by ibennetch** [comment]
Hi,

Thanks for your detailed report. The easiest way to fix translations is through the Weblate interface at https://hosted.weblate.org/projects/phpmyadmin/ — since you already have a GitHub account it should be pretty straightforward.

Specifically, (if these links work correctly), you may wish to review these three items:
* https://hosted.weblate.org/translate/phpmyadmin/4-9/pt/?q=eliminar&offset=15
* https://hosted.weblate.org/translate/phpmyadmin/4-9/pt/?q=eliminar&offset=19
* https://hosted.weblate.org/translate/phpmyadmin/4-9/pt/?q=eliminar&offset=20

I often hesitate to make such changes myself when I don't speak the language, it's usually better to have someone who is fluent supervise the changes.

Best wishes

**Comment by mauriciofauth** [comment]
Hi, @apaulo. Looks like this issue is already fixed. Could you please try using a new version to confirm that?

**Comment by williamdes** [comment]
:ping_pong:

**Comment by mauriciofauth** [comment]
Fixed by 079e911cfbc6b6c92aaad3d2e9a9d7fb856b746c.
