### ISSUE TITLE
Demo link gives: 502 Bad Gateway

### ISSUE THREAD

**Issue by blaasvaer** [phpmyadmin/phpmyadmin#15924]
As the title says: On https://www.phpmyadmin.net/ – upper right corner, button labeled "O- Try demo".

**Comment by williamdes** [comment]
@blaasvaer maybe an update is in progress, please wait an hour and it should be solved

**Comment by blaasvaer** [comment]
OK, so an hour for updating a broken link ... has some CI/CD process gone wrong? ; )

**Comment by williamdes** [comment]
@blaasvaer the link is not broken, the service behind the link is maybe broken and I have no access to fix it
Only @ibennetch does
So I hope it will go back online soon

**Comment by blaasvaer** [comment]
No, worries. But have me made sure that someone at their end are made aware of the issue? Or are we just going "this is their problem, not mine"?

**Comment by blaasvaer** [comment]
Seems not, it's up again. Thanks.

**Comment by williamdes** [comment]
> No, worries. But have me made sure that someone at their end are made aware of the issue? Or are we just going "this is their problem, not mine"?

It is a problem and I am aware of it but I can not do anything and sure I agree with you something must be done because I also had it multiple times

https://github.com/phpmyadmin/scripts/tree/master/demo

It I'll take me time or someone else to investigate what Is going on to crash the php-fpm service or another service. 

So we are taking this issue seriously, and will make sure it "never" happens anymore often.

**Comment by ibennetch** [comment]
Thanks for the report! Despite our monitoring, it's always helpful to get reports like this in case something slips through the cracks.

>  has some CI/CD process gone wrong?

No, I'm not sure why you would think that — we don't run the CI server on the same server the demo server runs on in order to isolate processes a bit.

>  please wait an hour and it should be solved
> -- *williamdes*

William is right that there is a...I think the term is "heartbeat monitor" that (usually) acts like a failsafe and resets the service if it's gotten really haywire; that process only runs approximately once per hour (since it's really meant as a last resort), so it seems from the comment timestamps like you probably caught it in the gap between when things stopped working and when services were restored.

> But have me made sure that someone at their end are made aware of the issue

Yes, between you creating the issue in the first place and William assigning it to me, I definitely saw it right away.

It seems to be up right now. The logs aren't clear on what the exact problem is, there are some hints that the service is getting too many requests at once. That could be related to an issue we're seeing where our CDN seems to be dumping all the download requests directly on our web server for an hour each day, but since the download server and demo server are again two different instances, I'm not sure that the two problems are directly related.

Also, the demo server isn't really treated as critical infrastructure, it's more like a best effort resource. Since it's simply meant for curious users to try out the software (and also referring users to in order to test bugs they're seeing), it's not something we view as vital to maintain with utmost reliability.

I'll try to step up the monitoring to see if we can better identify exactly what's going on, and we can try to react more quickly next time as well. If this happens again, feel free to re-open this or leave another comment here.

I hope my response has been helpful to you, and thanks again for the report.
