### ISSUE TITLE
setup doc links broken (w/fix)

### ISSUE THREAD

**Issue by hcoin** [phpmyadmin/phpmyadmin#15996]
In current stable, unchanged from the main download page:

On the various ~/setup screens there are blue circle links to related docs.  These reside in the ~/doc directory, however during setup the links refer to /setup/doc which doesn't exist and so none of the docs are actually available.

Solution:
Add a symbolic link to ~/doc in ~/setup/doc 
or fix all the references in ~/setup/*

OS: Ubuntu/eoan, nginx, (phpmyadmin not using the distro version, but rather the stable version off the main webpage), and firefox.

**Comment by williamdes** [comment]
Hello @hcoin 
Can you share a screenshot and let us know the version you are using ?

**Comment by ibennetch** [comment]
Confirmed, thanks for reporting.

This broke somewhere between 4.9 and 5.0 but I'm having a bit of trouble using git bisect to find where exactly, because it broke in several different ways (at one point, paths became relative to the location on disk, at one point rendering the page broke completely). So I'm still looking in to *why* this happened, but it definitely seems broken to me.

**Comment by williamdes** [comment]
![image](https://user-images.githubusercontent.com/7784660/82148213-365d1980-9853-11ea-84b6-b2d0d9bd79cd.png)

By "Check my links" for Chrome

**Comment by williamdes** [comment]
> Add a symbolic link to ~/doc in ~/setup/doc

I will not use this option because of #16033 (#16034)
Some users need more permissions for symlinks to be extracted

**Comment by ibennetch** [comment]
Thanks @williamdes, nice work!
