### ISSUE TITLE
Replace the phpMyAdmin coding standard package

### ISSUE THREAD

**Issue by mauriciofauth** [phpmyadmin/phpmyadmin#16140]
Instead of maintaining a custom package for the [phpMyAdmin coding standard](https://github.com/phpmyadmin/coding-standard), we can adopt an external CS that's more complete and maintain the differences in the `phpcs.xml` file.

My proposal is to use the [Doctrine coding standard](https://github.com/doctrine/coding-standard) since it's very complete and stricter and it's actively maintained.

**Comment by williamdes** [comment]
### Doctrine
```json
        "php": "^7.2",
        "dealerdirect/phpcodesniffer-composer-installer": "^0.6.2",
        "slevomat/coding-standard": "^6.2.0",
        "squizlabs/php_codesniffer": "^3.5.4"
```
### slevomat/coding-standard
```json
		"php": "^7.1",
		"dealerdirect/phpcodesniffer-composer-installer": "^0.6.2",
		"phpstan/phpdoc-parser": "0.4.5 - 0.4.7",
		"squizlabs/php_codesniffer": "^3.5.5"
```


I am satisfied with the dependencies they have, and agree to replace by  slevomat or doctrine

I would prefer that we only alter our coding standard package to have a consistent setup on all of our repos by keeping our package

**Comment by mauriciofauth** [comment]
I want an opinion on some Doctrine CS rules. Should we follow them?

- `Generic.Formatting.MultipleStatementAlignment`:
  ```diff
  - $a = $b;
  - $ccccccc = $d;
  - $e = $f;
  + $a       = $b;
  + $ccccccc = $d;
  + $e       = $f;
  ```

- `SlevomatCodingStandard.Classes.SuperfluousAbstractClassNaming`, `SlevomatCodingStandard.Classes.SuperfluousExceptionNaming` and `SlevomatCodingStandard.Classes.SuperfluousInterfaceNaming`:
  ```diff
  - PhpMyAdmin\Controllers\AbstractController
  + PhpMyAdmin\Controllers\Controller
  
  - PhpMyAdmin\Exceptions\ExportException
  + PhpMyAdmin\Exceptions\Export
  
  - PhpMyAdmin\Plugins\TransformationsInterface
  + PhpMyAdmin\Plugins\Transformations
  ```

- `Squiz.PHP.GlobalKeyword`:
  ```diff
  - global $db;
  - $db = 'db';
  + $GLOBALS['db'] = 'db';
  ```

- `SlevomatCodingStandard.TypeHints.ReturnTypeHintSpacing`:
  ```diff
  - public function getSomething(): string
  + public function getSomething() : string
  ```


- `SlevomatCodingStandard.PHP.RequireExplicitAssertion`:
  ```diff
  - /** @var Response $response */
    $response = $containerBuilder->get(Response::class);
  + assert($response instanceof Response);
  ```

**Comment by williamdes** [comment]
> I want an opinion on some Doctrine CS rules. Should we follow them?

Unfortunately I hate all the rules you mentioned :worried:, maybe you also agree.

`globals $xyz` is the good way

The class naming things make it more complex to understand the naming
The variable spacing is a waste of time
The assert is useless, and a waste of code

And WTF for `ReturnTypeHintSpacing`:   `): string` is the right way :thinking:

**Comment by ibennetch** [comment]
I have a slight preference towards maintaining our own coding standard, but I don't feel too strongly about this or have a particularly good reason for it. If we're going to have to maintain our own custom differences in phpcs.xml, we might as well maintain them in the coding-standard repository instead. I don't feel like this is something that changes much over time and that we're pretty happy with what we've got.

> Generic.Formatting.MultipleStatementAlignment

I really dislike this; it looks good but can lead to larger diffs than needed when making a change, just to fix whitespace.

> SuperfluousAbstractClassNaming, SuperfluousExceptionNaming, SuperfluousInterfaceNaming

I also dislike these three, but don't feel strongly about that position. I think using the name as a hint is strongly desirable and don't understand why the style would remove it.

> GlobalKeyword

I rather like this but again don't have a strong position about it. I do feel it *decreases* readability with longer statements because `$GLOBALS[` adds extra characters and makes lines longer, but overall I think it is acceptable.

I'm quite used to doing `global = $db;` but I could adapt to a new style.

> ReturnTypeHintSpacing

This looks goofy to me, I'm not a fan of this style. There shouldn't be a space before the colon.

> RequireExplicitAssertion

I don't care for this, but really I have no strong opinion about this style and could adapt to either case.

**Comment by mauriciofauth** [comment]
I agree with your opinions.

> I have a slight preference towards maintaining our own coding standard

We have a code style, but our coding standard do not enforce it. The Doctrine CS matches the majority of our code style and have the benefit of enforcing it. The only differences are the mentioned rules, but we can easily disable them in the `phpcs.xml` file.

**Comment by williamdes** [comment]
> I have a slight preference towards maintaining our own coding standard, but I don't feel too strongly about this or have a particularly good reason for it. If we're going to have to maintain our own custom differences in phpcs.xml, we might as well maintain them in the coding-standard repository instead. I don't feel like this is something that changes much over time and that we're pretty happy with what we've got.

I agree and think that we need to maintain our package, even if it is only depending on the doctrine coding standard.
It will help our projects to be aligned and in sync.

We are not doctrine, having a custom standard is like we should be: custom and flexible ;)

**Comment by mauriciofauth** [comment]
I agree that maintaining our package is a good idea.

I opened a pull request that uses the Doctrine CS as a base standard and disable the rules that we discussed here.
https://github.com/phpmyadmin/coding-standard/pull/8

**Comment by ibennetch** [comment]
Thanks William
