### ISSUE TITLE
Missing padding on error messages

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16217]
![image](https://user-images.githubusercontent.com/2218936/85395059-de02f100-b54f-11ea-9f8c-0097cedd40be.png)

Maybe the error box should be as big as the input box?

v: master

**Comment by Spring-dot** [comment]
@OlafvdSpek  Can I work on this issue?

**Comment by OlafvdSpek** [comment]
Sure

**Comment by roshnaeem** [comment]
Hey @OlafvdSpek , I want to work on this issue, but I could not find the specific file in which to make a change.

**Comment by OlafvdSpek** [comment]
@williamdes Could you help roshnaeem ?

**Comment by mauriciofauth** [comment]
Hi @roshnaeem.

You can see this error message when inserting a new row or searching a table.

For example in the [demo server](https://www.phpmyadmin.net/try/), try enter a value higher than 127 to the `active` field of the `sakila.customer` table.

For the `QA_5_0` branch: https://demo.phpmyadmin.net/QA_5_0/tbl_select.php?db=sakila&table=customer&server=1
![Screenshot from 2020-07-11 15-03-11](https://user-images.githubusercontent.com/120970/87230666-e6e52680-c387-11ea-81e2-4d01039e212d.png)

For the `master` branch: https://demo.phpmyadmin.net/master-config/index.php?route=/table/search&db=sakila&table=customer&server=1
![Screenshot from 2020-07-11 15-09-22](https://user-images.githubusercontent.com/120970/87230823-93270d00-c388-11ea-965a-1481eae2858b.png)

The master branch does not have the `.error` class, since it has removed by https://github.com/phpmyadmin/phpmyadmin/commit/e8c5ba4f80479e9043ad01e688094db1192c30a4#diff-649994e1ddb18e7e201b0b0696e968ccL837.

A quick fix is adding this class back and then applying the necessary changes.

**Comment by felipe-dmb** [comment]
Hello,

I'm new in GitHub and I'm working in this issue too.

I saw the @roshnaeem pull request #16259 and it didn't work for me. So, I edited the _common.scss files as described but I can't push to the pull request. Can anyone help me?

**Comment by williamdes** [comment]
Hi @felipe-dmb  
I used the interface like you and this link should be pre-configured to help you : https://github.com/phpmyadmin/phpmyadmin/compare/master...felipe-dmb:add-padding?expand=1
