### ISSUE TITLE
Cannot activate 2FA

### ISSUE THREAD

**Issue by sorinsfirlogea** [phpmyadmin/phpmyadmin#16210]
### Describe the bug
After a fresh manual install of 5.0.2 version I have successfully configured phpmyadmin and it works just fine. But it seems to be impossible to activate the 2FA feature. It keeps returning an error "The two factor authentication failed." as an red box on the page. 
I am using Google Authenticator to generate the key, through the QR code. I don't know how to enable debugging so I can see a more detailed error message.

### To Reproduce
Just trying to activate 2FA

### Server configuration
- Operating system: Ubuntu 16.04
- Web server: Apache 2.4
- Database version: MySQL 5.7.30
- PHP version: 7.4.6
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Google Chrome
- Operating system: Ubuntu 18.04

**Comment by ibennetch** [comment]
I just tested this and it worked correctly. Could you confirm how you installed phpMyAdmin — did you download directly from phpMyAdmin, are you using the packaged version, or are you using some kit such as XAMPP?

I don't have an immediate answer for you but we will look at this.

**Comment by ibennetch** [comment]
One thought I had is that this could be related to clock drift issues. Is there a chance you are running this on a virtual machine or some other system that might have an unstable clock or that the clock might drift? The standard window is 30 seconds, so it seems unlikely that your clock would deviate by that much, but it's the only thing that comes to immediate mind.

**Comment by sorinsfirlogea** [comment]
Ha! That might be the problem. Never thought about it. My Linux box is
somewhere in Frankfurt (Upcloud cloud). What should be the timezone on the
server? The same as in Bucharest? Or is there a translation depending on
server timezone?

Regards,
Sorin

**Comment by ibennetch** [comment]
I am not an expert in the TOTP algorithm, but my understanding is that all systems work off of the Unix Epoch (POSIX time), and calculating the 30 second window is based on each machine's ability to keep track of time since then.

I suspect that having a hardware clock set to the local time zone rather than UTC would cause this problem; most Linux distributions expect the hardware clock to be set to UTC and use the tzdata package to manage using the proper timezone.

There could be other problems associated with switching the clock, and at this point I'm speculating anyway, so please don't break your system :)

**Comment by sorinsfirlogea** [comment]
I google it a bit and I found more details that allowed me to fix the
problem. It was indeed the clock drift. Thank you for your helpful tip.

Regards,
Sorin
