### ISSUE TITLE
Can't use search page when table have a special characters

### ISSUE THREAD

**Issue by CarlosSLoureiro** [phpmyadmin/phpmyadmin#16222]
### Describe the bug

I got error when I try to search in some table that contains special characters in the table name.

### To Reproduce

1. Create some table with a special character as "ç", "ã", "õ" and others.
2. Select the created table.
2. Click in the search button.

### Expected behavior

The search page with the selected table columns as options to search/select.

### Screenshots

![error](https://user-images.githubusercontent.com/19580424/85505745-61aaf500-b5c5-11ea-8d88-a8df79004430.png)

### Server configuration

- Operating system: Windows Server 2016
- Web server: Microsoft-IIS/10.0
- Database version: MySQL 8.0.19
- PHP version: 7.4.1
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Google Chrome Version 83.0.4103.116
- Operating system: Windows 10

### Additional context

In the screenshot I've reproduced the same problem in my own desktop using xampp 7.2.31

**Comment by williamdes** [comment]
Thank you for report, confirmed on my side

**Comment by williamdes** [comment]
Master version seems not affected, but demo server has an error 500
@ibennetch Could you please send us the stacktrace ?

**Comment by williamdes** [comment]
@Tithugues You where the author of this DI change, would you agree to try to fix this issue ?
Symphony thinks the value of the parameter is to be replaced by something

**Comment by Tithugues** [comment]
I'll try to have a look in the next days.

**Comment by Tithugues** [comment]
Just something not to forget. Looking at [ASCII table](http://sebastienguillon.com/test/jeux-de-caracteres/windows-ascii-fr.html), the "C3" could come from the "alt 199" which is usually a character displayed when not found.

Not sure at all that's it, but that maybe linked.

**Comment by williamdes** [comment]
Thank you, #16225 seems to be similar

**Comment by Tithugues** [comment]
I don't have a fix for now, but maybe if I explain, someone would have an idea.

For many pages, we have this kind of dependencies which are defined:
```php
$dependency_definitions = [
    'searchType' => 'normal',
    'url_query' => &$url_query,
];
```

The issue is that this `$url_query` looks like `?db=gh16222&table=gar%C3%A7on` (table = `garçon`).

But... as this is a parameter, Symfony DI reads it and see `%...%`, so it considers this is a parameter that should be replaced...

How to fix this?

I would say that, before setting the parameter `url_query`, we should replace these encoded characters by something else, maybe the original character.

Just to let you know: currently, the URL is encoded here \PhpMyAdmin\Url::getCommonRaw with `http_build_query`.

**Comment by Tithugues** [comment]
Can someone also try this fix please? I went through a few pages and didn't get the issue anymore. :pray:

**Comment by williamdes** [comment]
Fix confirmed, thank you so much !

**Comment by CarlosSLoureiro** [comment]
Thank you
