### ISSUE TITLE
Import ignores 2nd, 3rd, ... attempt to import

### ISSUE THREAD

**Issue by hfrmobile** [phpmyadmin/phpmyadmin#16282]
### Describe the bug

When providing invalid value(s) for import (e.g. separator: "," when it is ";") and start import (by clicking "Go" button) I get no information about this. When correcting the value(s) then nothing is importet.

### To Reproduce

1. Go/click an existing table
2. Click on 'Import'
3. Select CSV file to import
4. Keep all setting as is (even Columns separated with: , - even the provided CSV contains ; as column separator)
5. Click 'Go'
6. "Nothing" happens - **would expect, at least, "0 rows imported" or something similar**
7. Correct the value "Columns separated with" and provide ";" as value (without quotation marks of course)
8. Click "Go"
9. Again, nothing happens (**also no import, even provided settings are okay**)

WORKAROUND:
Provide  correct values/settings on 1st attempt, then import will work (once). To do additional import, you have to leave the "Import" page and go to "Import" page again

### Expected behavior

At least there should be a message when the import is done/failed (e.g. "{count} row(s) imported from {file} to {table}").
Import should work every time when valid settings were provided, not only the first time.

### Server configuration

- Operating system:
- Web server: Apache (Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407)
- Database version: Server version: 5.6.37-log - MySQL Community Server (GPL)
- PHP version: 7.0.33-0+deb9u8
- phpMyAdmin version: 4.6.6deb4+deb9u1

### Client configuration

- Browser: Chrome
- Operating system: Windows 10, 64 bit

**Comment by williamdes** [comment]
Hi @hfrmobile 
I can see you are using the latest version of the Debian package for Debian 9 (https://tracker.debian.org/pkg/phpmyadmin) but you can update using `buster-backports` or our Ubuntu PPA.

For Debian `buster-backports` please refer to https://github.com/phpmyadmin/phpmyadmin/issues/15236#issuecomment-615954993 or https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410 to use our Ubuntu PPA

Let us know if the issue is fixed for you
