### ISSUE TITLE
Use PDO instead of mysqli

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/phpmyadmin#16281]
Replace mysqli by PDO.

### Additional context

- phpMyAdmin version: 5.1-dev

Ref: #16183

**Comment by mauriciofauth** [comment]
I don't think we should replace mysqli. We can try to add PDO as an alternative driver, but not as a replacement.

**Comment by MESWEB** [comment]
> I don't think we should replace mysqli. We can try to add PDO as an alternative driver, but not as a replacement.

Personally I prefer PDO and this driver is default enabled for servers. For mysqli you need usually enable it manually. Any way PDO is OOP.

**Comment by mauriciofauth** [comment]
> > I don't think we should replace mysqli. We can try to add PDO as an alternative driver, but not as a replacement.
> 
> Personally I prefer PDO and this driver is default enabled for servers. For mysqli you need usually enable it manually. Any way PDO is OOP. 

PDO is great for general use, however since PDO is an abstraction layer, I don't really know if it will have all the features phpMyAdmin uses. The mysqli extension have an object-oriented interface as well. 

Usually, both the mysqli and PDO MySQL extensions are installed in the system by the same package. For example, for Debian 10, this package is called `php-mysql`.

**Comment by ibennetch** [comment]
I tend to agree with @mauriciofauth; I don't think an abstraction layer here is needed or brings any advantage over what we have now.

Aside from the handful of users who might want to install PHP with PDO and not MySQLi, is there any other compelling reason to make this change?

**Comment by MESWEB** [comment]
@mauriciofauth  Nope you are wrong. When I was install apache 2, MYSQL and PHP there was no mysqli mod installed. I do that manually.

PDO will work on 12 different database systems, whereas MySQLi will only work with MySQL databases.

So, if you have to switch your project to use another database, PDO makes the process easy. You only have to change the connection string and a few queries. With MySQLi, you will need to rewrite the entire code - queries included

**Comment by ibennetch** [comment]
Using PDO won't automatically make phpMyAdmin work with any other database system, though. For instance, the user management relies on direct SQL queries that are specific to the database system, so even though the connection is abstracted through PDO the query wouldn't be. I highly doubt that a lot of the specific features such as GIS integration and Designer can be handled successfully through other database systems without major modification, either.

Whether we should migrate the codebase to PDO instead of MySQLi is an interesting idea, but I don't think doing so would allow us to support more database systems than we already do.

**Comment by mauriciofauth** [comment]
> Nope you are wrong. When I was install apache 2, MYSQL and PHP there was no mysqli mod installed. I do that manually.

PDO is enabled by default, but PDO_MySQL is not, which enables the MySQL support for PDO. And packages like `php-mysql` usually installs and enables both `mysqli` and `pdo_mysql` extensions.

> PDO will work on 12 different database systems, whereas MySQLi will only work with MySQL databases.
> So, if you have to switch your project to use another database, PDO makes the process easy. You only have to change the connection string and a few queries. With MySQLi, you will need to rewrite the entire code - queries included

phpMyAdmin is a tool specialized in MySQL/MariaDB servers. In other words, it is necessary that the extension support all features from the server. That's why I said that _"I don't really know if it will have all the features phpMyAdmin uses."_

**Comment by Bllacky** [comment]
Not sure if I am correct, but I think MYSQLi is slightly faster than PDO. Also, as PHPMyAdmin is designed for MySQL and MariaDB, I do not really see the benefit of PDO. I believe dev effort and time would benefit more if directed at other features and issues, rather than this.
