### ISSUE TITLE
MacOS warning

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16468]
> Mac users should note that if you are on a version before macOS,

Shouldn't this refer to a specific version of MacOS?

https://docs.phpmyadmin.net/en/latest/setup.html#

**Comment by ibennetch** [comment]
*Technically*, this is correct (the best kind of correct!) because the warning applies to anything prior to Mac OS X, that is, any of the "Classic" versions such as Mac OS 9. Apple changed the name of the operating system starting with OS X, so this used to read "Mac OS X" and was changed with 93b00f86e18a128b0b44ee162b562c515f3ae6ad to read "macOS" which is in keeping with the Apple style.

Technicalities aside, I think this is confusing and that keeping it as "Mac OS X" (which was the original name, after all) is the best solution.

**Comment by OlafvdSpek** [comment]
Is anyone still using 9?

**Comment by ibennetch** [comment]
That is an excellent question.

**Comment by ibennetch** [comment]
Fixed with e21190cadd46ce0206661d9843e765709fdd5409. Thanks Olaf.
