### ISSUE TITLE
Resolving deltas takes forever

### ISSUE THREAD

**Issue by WarpMee** [phpmyadmin/phpmyadmin#16529]
It takes a good 20 minutes to resolve deltas when cloning this repo.

To reproduce, clone the repo.

**Comment by ibennetch** [comment]
I'll have to test this a little bit further because I definitely don't remember it taking nearly that long, but I'll try again.

However, I don't know what we can do about this. I don't think there's a solution that would improve this processing time. My understanding is that `git gc` on the server would help, but GitHub already runs that periodically and automatically.

I'd love to get some ideas here for how to improve this.

**Comment by williamdes** [comment]
I think there is nothing we can do about that because the history can not be re-written.

That said you can use https://github.com/code-lts/phpmyadmin-releases that should be lighter to clone
