### ISSUE TITLE
Use an UI framework like Angular

### ISSUE THREAD

**Issue by Thomas1664** [phpmyadmin/phpmyadmin#16648]
### Is your feature request related to a problem? Please describe.
Right now, there are many issues related to JavaScript errors open and the code should be refactored to be more modular. 
UI frameworks like [Angular](angular.io) will make the code more modular and readable. Furthermore, bugs are easier to spot and to solve and the performance could be increased.

I know that this will be a lot of work e.g., all responses must be converted to return JSON data and therefore, I consider this more as a long term project.

### Describe the solution you'd like
Use a UI framework to replace the current JavaScript code

### Describe alternatives you've considered
Of course, there are other UI frameworks as well.

**Comment by williamdes** [comment]
Hi @Thomas1664 

I understand your point of view, but for me this would not benefit to ours users.
It would make development harder and slow our users down.
We are working on the JS codebase to improve it and we did add Babel for that.

If Angular is added to phpMyAdmin, I quit the project. Why: because I want to keep things simple and minimal.
I used Angular, it works, is very painful to upgrade, consumes time, etc..
Angular for phpMyAdmin is just like having a skyscraper to host 3 people.

But still I thank you for bringing this up

For now the goals are:
- Add more tests to our new jest test suite
- Remove some useless JS code
- Improve the actual JS code to remove any useless line

**Comment by williamdes** [comment]
cc @mauriciofauth and @ibennetch

**Comment by Thomas1664** [comment]
> Hi @Thomas1664
> 
> I understand your point of view, but for me this would not benefit to ours users.
> It would make development harder and slow our users down.
> We are working on the JS codebase to improve it and we did add Babel for that.
> 
> If Angular is added to phpMyAdmin, I quit the project. Why: because I want to keep things simple and minimal.
> I used Angular, it works, is very painful to upgrade, consumes time, etc..
> Angular for phpMyAdmin is just like having a skyscraper to host 3 people.

We don't necessarily need to use Angular. We could use any other framework as well like [React](https://reactjs.org/) or [Vue](https://v3.vuejs.org/).
Although Angular is a high level framework and might seem to be overkill, it is sufficient for our needs. In recent years, Angular became easier to upgrade and better in performance and probably won't make phpMyAdmin slower than it is today. However, learning Angular is not easy in the beginning and requires some time.

**Comment by williamdes** [comment]
Used Angular: overkill, big bundles, a pile of overkill things to just display UI stuff
Used React: quite nice and easy, but also a pile of useless things for phpMyAdmin

IMO we should not use any UI Framework at phpMyAdmin because we are doing back-end rendered HTML using Twig

If we use a UI Framework we would need to only respond JSON payloads and refactor a lot of our display code
And that would make phpMyAdmin an API, this was discussed here and refused: https://github.com/phpmyadmin/phpmyadmin/issues/15303

**Comment by mauriciofauth** [comment]
I'm not against using an UI framework and I agree that using a UI framework will benefit phpMyAdmin. But as you said, this will be a lot of work and we can't afford that amount of work right now. We are focusing on improving our current code.
