### ISSUE TITLE
Creative account -problem

### ISSUE THREAD

**Issue by Michalburk** [phpmyadmin/phpmyadmin#16695]
hello can i ask you for advice or help? I accidentally deleted the root user who had administrator access to manage the database. I wanted to create a new user, which I created, but unfortunately I did not notice that I did not assign him administrative rights and under this account it is not possible to manage databases. unfortunately there is no other account. Could I ask you how can I add users even if there are not enough rights to use the sql display?

**Comment by Michalburk** [comment]
this is error massege 

#1227 - Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation

Creative account doesn´t work :-(

**Comment by ibennetch** [comment]
Hello,

Are you using MySQL or MariaDB, and which version? The create user syntax can vary slightly.

The general directions are to write the CREATE USER commands in a text file and tell the database server to run that when starting (or tell it to bypass permissions and execute the commands manually). 

The MySQL manual https://dev.mysql.com/doc/refman/5.7/en/resetting-permissions.html has instructions for starting your server without permissions in place. You can start with that, but when it gets to the part about ALTER USER it won't be helpful because your root user doesn't exist. You would need to refer to your specific database version for the exact syntax for creating a user with full permissions.
