### ISSUE TITLE
Wrong Absolute Links In Navigation ("/" instead of "./")

### ISSUE THREAD

**Issue by AJK-Muc** [phpmyadmin/phpmyadmin#16698]
### Describe the bug
With or without defined PmaAbsoluteUri ($cfg['PmaAbsoluteUri'] = 'https://' . $_SERVER['SERVER_NAME'] . '/mysql_latest/';) I got the wrong navigation links on the left menu (see screenshot of the source code in browser). Only the link to a new database is correct (index.php?...), all other links to existing databases are wrong (/?...) I guess instead of (./?...). Where can I change this strange behavior, i.e. changing [slash] with [dot][slash] in href of the pma_navigation_tree_content?

### To Reproduce
As soon as I log in (/mysql_latest/), any link in the navigation translates to href="/?..." instead of href="./?..." or href="[absolute or relative URL defined by PmaAbsoluteUri]?..." which makes phpMyAdmin 5.1.0 unusable for me 😢

### Expected behavior
Correct links to the expected functions.

### Screenshots
![SourceCodeScreenshot](https://user-images.githubusercontent.com/46240166/109654270-4c2d9800-7b62-11eb-9825-62f507161a59.png)

### Server configuration
- Operating system: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-66-generic x86_64)
- Web server: Apache 2.4.46
- Database version: MySQL 5.7.33
- PHP version: PHP 7.4.15
- phpMyAdmin version: 5.1.0

### Client configuration
- Browser: Safari 13.1.2 & Firefox 86.0 & Chrome 88.0.4324.192
- Operating system: MacOS 10.13.6

**Comment by csware** [comment]
The reason is that `Util::getUrlForOption($target, $location')'` returns null.

In my config.ing.php I have `cfg['DefaultTabDatabase'] = 'db_structure.php';`, this seems to be the reason here. However, commenting this line in the config file or changing this option in the config does not fix the issue.

Only fix was to add `case 'db_structure.php':` to the abovementioned function.

I use php-fpm if it makes any difference. When I grepped the phpMyAdmin directoy, I could not find 'db_structure.php', so I expect that this comes from the userconfig.

Please add a smooth upgrade path,

**Comment by AJK-Muc** [comment]
Thanks 😃
