### ISSUE TITLE
Syntax error in the "Export" section in Spanish

### ISSUE THREAD

**Issue by emanuel-c4** [phpmyadmin/phpmyadmin#16752]
When selecting custom in the "Data creation options" section where it says "both of the above" appears `& nbsp;` 3 times instead of `&nbsp;`.

It is in the `<label for="radio_sql_insert_syntax_both">`

![Screenshot of syntax error in Data creation options, option both](https://user-images.githubusercontent.com/36056518/111919535-d3e43380-8a8a-11eb-8c53-059e218c28d6.png)

**Comment by williamdes** [comment]
Hi @emanuel-c4 
I logged in into https://hosted.weblate.org/languages/es/phpmyadmin/ and edited the text.
Seems like the previous translator just used an automatic translating tool and did a sloppy work.
Thanks for reporting that to us.
If you want to help you only need to create an account and translate what you want.
https://hosted.weblate.org/projects/phpmyadmin/5-1/es/ needs some help

Fixed by 1a03bc76598219f781da997243baadf3a42bd93b and a0a95120c9294a630f5d7d066772dfb10dd989b7
