### ISSUE TITLE
Vertical alignment issue

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16843]
5.1.1-dev+20210420.2d9aad5ab2

Might be caused by labels having a 8px bottom margin.

![image](https://user-images.githubusercontent.com/2218936/115542819-f55e5800-a2a0-11eb-9f6d-1ce02b434a1e.png)

?route=/server/privileges&viewing_mode=server

**Comment by joffreycarle** [comment]
Hi @OlafvdSpek!
Just installed PMA locally to fix this and also to give my first open source contribution as PMA helped me many times.
I had `yarn install && composer install` from master and then checked out 2d9aad5ab2 without `yarn install` and the issue wasn't there.
After doing `yarn install` on the concerned commit, the issue is here.
Should I still fix it or let future merges fix it?
Thanks.

**Comment by williamdes** [comment]
> without yarn install and the issue wasn't there.

This is strange because you should not have a working UI without the yarn step that does `js-compile` and `css-compile`

> Should I still fix it or let future merges fix it?

You can fix it, I confirmed the issue yesterday :)
But you need to use `QA_5_1` as a base branch and re-run `composer update && yarn` for this fix because it also affects 5.1 verions

> Just installed PMA locally to fix this and also to give my first open source contribution as PMA helped me many times.

Welcome !
Let me know if you need some help

**Comment by joffreycarle** [comment]
@williamdes : Sorry, I just read again my post and it isn't clear.
I meant that I did the `composer update && yarn` when I've cloned the repo but not again when I checked out 2d9aad5 
That's why at first, I didn't have the issue I guess.
Anyway, I will base on `QA_5_1`, open a branch for the fix and ask for a PR.
