### ISSUE TITLE
Weird database-name "nesting" in the left menu when underscore signs are used in their names

### ISSUE THREAD

**Issue by grebenarov** [phpmyadmin/phpmyadmin#17003]
### Describe the bug
Before posting this as a "bug", I did a little research and found out that whenever you create 2 databases, in phpMyAdmin, with underscores in their names, like **db_one** and **db_two**, phpMyAdmin will display them "grouped" in the left menu as follows:
**db
    ->db_one
    ->db_two**

My impression was that - that is intentional. Ok, but when I tested creating databases with MULTIPLE underscores in their names that produced a WEIRD MULTIPLE NESTING. Just look at the screenshot I am posting here and you will see what I mean.

### To Reproduce
1. Go to [phpMyAdmin Demo](https://demo.phpmyadmin.net/master-config/) 
2. One by one create 2 databases with the names: db_with_more_underscores_1 and db_with_more_underscores_2 (no need to add any tables in them)

...and you should immediately see the weird multiple nesting seen in the screenshot

### Expected behavior
If that is not some intentional effect - I believe ALL databases should display in a perfect column - below one another - regardless of any underscore signs in their names. And no nesting should occur.

### Screenshots
![underscore_issue](https://user-images.githubusercontent.com/5733212/125180068-d4344600-e1c3-11eb-8e28-b952f37843f0.jpg)

### Server configuration
- Operating system: ? (It's the Demo site)
- Web server: nginx/1.14.2
- Database version: MySQL
- PHP version: 7.4.20
- phpMyAdmin version: 5.2.0-dev

### Client configuration
- Browser: Chrome, Firefox
- Operating system: Windows 10

### Additional context
I found similar issues with underscores dating back to 2013

**Comment by ibennetch** [comment]
Hi, thanks for the report and good research in to the matter.

You're (mostly) talking about behavior controlled by these three configuration directives:
* https://docs.phpmyadmin.net/en/latest/config.html#cfg_NavigationTreeEnableGrouping,
* https://docs.phpmyadmin.net/en/latest/config.html#cfg_NavigationTreeDbSeparator, and
* https://docs.phpmyadmin.net/en/latest/config.html#cfg_NavigationTreeTableSeparator

This feature allows people to group related sets of databases or tables together to make navigation easier, and can be disabled completely, if you prefer, by setting `$cfg['NavigationTreeEnableGrouping'] = false;`.

The strange part about it to me is that I thought we only go through the first separator. I was pretty confident of that being the design goal for this, so the way it is working for you seems wrong to me (it should only show 'db' and then group them all under that. We'll have to look back to see if I'm misremembering. I confirm that I see the same behavior you see, so it's not just you.

**Comment by grebenarov** [comment]
Hi Isaac,

Thank you for confirming you see the same thing. Yes, I also came across information that databases are supposed to group only after THE FIRST separator - kind of: only ONE level, but apparently that is not what happens.

And thank you for pointing out those directives. I will make sure to familiarize myself more with them.

Best,
Angelo

**Comment by lrb2** [comment]
For database names, the separator nesting depth seems to have been 10000 ever since 2b12872c2a1ffff7bdded52b8d3e63e5dd8f7e67, and cannot be configured. However, for table names, the separator nesting depth is controlled by `$cfg['NavigationTreeTableLevel']`, and is by default 1 (as is apparent at the bottom of the image). Though values greater than 1 aren't really working properly either.

![image](https://user-images.githubusercontent.com/59065888/129078236-adb2a825-9a35-458b-bb48-f7ab56ba5610.png)

Probably what should happen is that the nested groups `db`, `with`, and `more` should be combined into a single group `db_with_more`. Though, if there is a database `db_with` as well, then the main group would be `db_with` with the group `more` nested inside. I'll see if I can fix this issue.

It does seem like there should be a configuration variable for database nesting depth `$cfg['NavigationTreeDbLevel']` just like `$cfg['NavigationTreeTableLevel']` as well.
