### ISSUE TITLE
Malicious users can gain access to databases not intended for access through the phpMyAdmin application.

### ISSUE THREAD

**Issue by mohankara** [phpmyadmin/phpmyadmin#17031]
Malicious users can gain access to databases not intended for access through the phpMyAdmin application.

**Description:**
The phpMyAdmin application includes a feature called “Show only listed databases” which allows a user to specify the databases listed within the database navigation menu. Configuration for phpMyAdmin has the feature labeled as “disabled”. However we were able to utilize the feature to show databases not intended to be shown. The “Show only listed databases” feature does not appear to be disabled.

**Steps to Reproduce**
Get a list of databases
1. Open phpmyadmin.
2. Click on the “SQL” tab. This will open the SQL editor.
3. Run the following SQL statement: `show databases`.
4. Observe the list of databases within MySql instance.
Add databases to the navigation pane
1. Click on the “Settings” tab.
2. Click on the “Features” button.
3. Click on the “Databases” button.
4. Within the “Show only listed databases” text box add a new line and enter in a database from the list of databases returned from the previous steps listed above.
5. Click the “Apply” button.
6. Observe the left hand navigation includes the databases.

### Expected behavior
Ensure configuration settings for disabled functionality is working as intended.

### Server configuration
- Operating system:CentOS
- Database version: MySQL 5.7+ / MariaDB 10.5x
- PHP version: 4.9.7
- phpMyAdmin version: 4.9.7

### Client configuration

- Browser: Any
- Operating system: Windows/Mac

**Comment by ibennetch** [comment]
Hi,

Thanks for your report. This is pretty much the expected behavior (you can see it's documented as such at https://docs.phpmyadmin.net/en/latest/config.html#cfg_Servers_only_db). That setting (and the `only_db` configuration directive) are intended for the visual interface and aren't a replacement for proper MySQL (or MariaDB) permissions on the user account.

While perhaps it doesn't work the way you desire, you are describing the expected behavior for this.
