### ISSUE TITLE
No page selector for system database tables

### ISSUE THREAD

**Issue by kroloq** [phpmyadmin/phpmyadmin#17055]
### Describe the bug

When browsing the system database tables (e.g. information_schema.COLUMNS), the navigation bar does not display any page selector or forward/backwards buttons to browse through the database table.
In non-system tables the page selector as well as the forward/backwards buttons are shown, if the number of records in the table exceeds the number of displayed rows.

### To Reproduce

1. Select a system table (e.g. information_schema.COLUMNS)
2. See that page selector and forward/backwards buttons are missing in the navigation bar

### Expected behavior

Page selector and forward/backwards buttons should be displayed, if the number of records in the table exceeds the number of displayed rows. It should be displayed regardless of whether it is a system table or not.

### Screenshots

Screenshot of system table:
![Screenshot_system_tables](https://user-images.githubusercontent.com/88189451/128494661-d8c2e70f-cf33-4321-b648-5e056208f246.png)

For comparison, screenshot of non-system table:
![Screenshot_non_system_table](https://user-images.githubusercontent.com/88189451/128494888-71399dea-abad-47bc-8a0a-d38d3b8accc9.png)

### Server configuration

- Operating system: Debian 10
- Web server: Apache2
- Database version: MariaDB 10.3.29
- PHP version: 7.3.29
- phpMyAdmin version: 5.2.0-dev (clone of current Github master branch)

### Client configuration

- Browser: Firefox 90.0.2
- Operating system: Linux Manjaro

### Additional context

In phpMyAdmin v. 5.1.1 the forward/backwards buttons are displayed, but the page selector is also missing.

Edit:
I figured out where this issue originates from. I would really like to contribute to phpMyAdmin, so would you accept a pull request for it? It would be a one line change in getTableNavigation.

**Comment by kroloq** [comment]
As an additional comment I would like to add that the number of total rows (light green bar above the SQL text) is not displayed. It can also be seen in the screenshot.
Not sure if I should create an extra issue for that.

**Comment by lrb2** [comment]
I was just looking into a similar issue and I came across this one. The issue affects all results with an unknown number of rows and is caused by 8f992a4fbfbca92b83a3e4f21d70c1fca1274e4c, where the check for the number of rows (`unlim_num_rows`) was changed from `=== false` to `=== -1` in Results.php. I traced the source of `false` to the `countRecords` function in Table.php. So the solution is either to revert back to `=== false` or, if the goal is for `countRecords` to eventually return `-1` instead of `false`, add a temporary fix in the `countQueryResults` function in Sql.php (`if ($unlimNumRows === false) { $unlimNumRows = -1; }` or something) until `countRecords` (and everywhere it's used) is updated to return `-1`.

**Comment by kroloq** [comment]
@lrb2,

you are right. I addressed it in PR #17059 three days ago. You are not happy with my PR?
The PR is awaiting a review by @mauriciofauth, because he added `=== -1`.

**Comment by lrb2** [comment]
@kroloq,

Sorry, I must be blind - I glanced right over your PR as I thought it was another issue that was linked or something. No clue how I missed it, and pretty much everything that I mentioned was already discussed. Though I still needed to make a commit in my fork because I have another PR that relies on this issue being solved.

**Comment by kroloq** [comment]
@lrb2, 
no worries. Just wasn't sure, if I did something wrong (I am new to Github).
