### ISSUE TITLE
Unknown error connecting database mysql

### ISSUE THREAD

**Issue by YAABITECH** [phpmyadmin/phpmyadmin#17295]
9:39:48 PM  [main] 	Initializing Control Panel
9:39:48 PM  [main] 	Windows Version:  Home  64-bit
9:39:48 PM  [main] 	XAMPP Version: 7.4.23
9:39:48 PM  [main] 	Control Panel Version: 3.3.0  [ Compiled: Apr 6th 2021 ]
9:39:48 PM  [main] 	You are not running with administrator rights! This will work for
9:39:48 PM  [main] 	most application stuff but whenever you do something with services
9:39:48 PM  [main] 	there will be a security dialogue or things will break! So think 
9:39:48 PM  [main] 	about running this application with administrator rights!
9:39:48 PM  [main] 	XAMPP Installation Directory: "d:\zzserver\"
9:39:48 PM  [main] 	Checking for prerequisites
9:39:54 PM  [main] 	All prerequisites found
9:39:54 PM  [main] 	Initializing Modules
9:39:54 PM  [main] 	Starting Check-Timer
9:39:54 PM  [main] 	Control Panel Ready
9:40:57 PM  [Apache] 	Attempting to start Apache app...
9:40:58 PM  [Apache] 	Status change detected: running
9:41:00 PM  [mysql] 	Attempting to start MySQL app...
9:41:00 PM  [mysql] 	Status change detected: running
9:41:02 PM  [mysql] 	Status change detected: stopped
9:41:02 PM  [mysql] 	Error: MySQL shutdown unexpectedly.
9:41:02 PM  [mysql] 	This may be due to a blocked port, missing dependencies, 
9:41:02 PM  [mysql] 	improper privileges, a crash, or a shutdown by another method.
9:41:02 PM  [mysql] 	Press the Logs button to view error logs and check
9:41:02 PM  [mysql] 	the Windows Event Viewer for more clues
9:41:02 PM  [mysql] 	If you need more help, copy and post this
9:41:02 PM  [mysql] 	entire log window on the forums

This is the log shown. I tried changing the port. But not worked.

**Comment by ibennetch** [comment]
Hi,

This forum is for discussing problems with the phpMyAdmin application, which is a single component out of the entire XAMPP installation you have. Since we only work with phpMyAdmin and not the other aspects, specifically the MySQL database you're having a problem with, you might get better help asking in the XAMPP forums directly.

However, this seems rather straightforward, however you'll need to find the logs as described in the third to last line (clicking the log button for MySQL) , which I suppose is in an obvious place in the interface. If you can provide some hint from those logs, we might have some clue as to why your MySQL isn't starting. Most often, it's because users have also installed their own MySQL or MariaDB alongside XAMPP and the two are conflicting over using the same port, but the error message should tell us more.
