### ISSUE TITLE
Cannot Log into Database. Max Users Connected

### ISSUE THREAD

**Issue by BlueLord444** [phpmyadmin/phpmyadmin#17297]
I don't know if this is the correct place to put this... but

When I try to log into the database. I cannot log in.

https://imgur.com/a/bkp1VSd

If applicable, add screenshots to help explain your problem

- Browser: Google Chrome
- Operating system: Windows 10

**Comment by ibennetch** [comment]
Hi,

Usually this is caused by using the wrong username or password. You could check with your hosting provider to make sure you're using the correct credentials.

**Comment by ibennetch** [comment]
Oh, also your subject uses a different error message than I see in the screenshot; the screenshot looks like just a problem with the username or password, but the message you reference in your subject implies that too many users are trying to connect at once, in which case your hosting provider should probably either re-allocate resources so that their server isn't under such loads or they need to increase the number of users allowed. Either way, it points at an issue that only your provider can resolve.

**Comment by BlueLord444** [comment]
Okay, thank you so much. I'll contact my provider
