### ISSUE TITLE
request for passport

### ISSUE THREAD

**Issue by ronald2022-ai** [phpmyadmin/phpmyadmin#17313]
I set my phpmyadmin password and i forgot it, how can i be helped. Also my website is not displaying how can i be assisted.

**Comment by ibennetch** [comment]
Hello,

If your database is hosted or managed by someone else, you should ask them for assistance. If you manage it yourself, here are instructions for resetting your database password: https://docs.phpmyadmin.net/en/latest/faq.html#i-have-lost-my-mysql-root-password-what-can-i-do

As far as your site not displaying, you would have to ask your hosting provider or web developer for assistance; since we aren't your hosting we don't have any access to check anything nor do we have any knowledge of how your site is build.

Regards,
Isaac
