### ISSUE TITLE
Multiple backticks in ORDER BY clause when clicking on column header

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17339]
### Describe the bug

Additional backticks are added to the query, when clicking on column header, to sort ASC/DESC.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/sql&db=sakila&table=payment](https://demo.phpmyadmin.net/master-config/index.php?route=/sql&db=sakila&table=payment)
2. Run this query SELECT \`customer_id\`, SUM(\`amount\`) FROM \`payment\` GROUP BY \`customer_id\`;
3. Click on SUM(\`amount\`) to sort.
4. The new query looks like this
SELECT \`customer_id\`, SUM(\`amount\`) FROM \`payment\` GROUP BY \`customer_id\` ORDER BY \`SUM(\`\`amount\`\`)\` ASC

### Screenshots

![scr](https://user-images.githubusercontent.com/25424343/152603861-4199d5d1-f9ab-4ec1-bc0f-ad04619a7fb6.png)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by mauriciofauth** [comment]
Hi @liviuconcioiu. Thank you for all your reports.

There is no issue here. MySQL/MariaDB creates a column name called ``SUM(`amount`)`` and you want to use that column to order the results. So to not confuse the column name with the function, the backticks are added to escape it, but because the name already has backticks in it, phpMyAdmin adds a backtick before each backtick to escape them.

From the [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/identifiers.html):
> Identifier quote characters can be included within an identifier if you quote the identifier. If the character to be included within the identifier is the same as that used to quote the identifier itself, then you need to double the character.
