### ISSUE TITLE
(HY000/1045): Access denied for user 'K17'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by kitscoms** [phpmyadmin/phpmyadmin#17343]
### Describe the bug

it shows mysqli::real_connect(): (HY000/1045): Access denied for user 'K17'@'localhost' (using password: YES)

### To Reproduce

Log in with K17
using password

### Expected behavior

mysqli::real_connect(): (HY000/1045): Access denied for user 'K17'@'localhost' (using password: YES)

### Server configuration

- Operating system:raspbian
- Web server:Homemade
- Database version:I dont know
- PHP version:i dunno either
- phpMyAdmin version:i dunno

### Client configuration

- Browser:Chromium
- Operating system:Raspbian

**Comment by ibennetch** [comment]
Hi, this seems like a local problem relating to your user account. Are you able to connect from the `mysql` command line client? Most likely either your password is wrong, the user account doesn't exist, or you are connecting via sockets (host `localhost`) when the user account is configured for host value `127.0.0.1` or `%`. The MySQL wildcard character % only matches TCP/IP connections, so if you've tried to create the K17 account with the wildcard character for the host you'll either need to change that to localhost or tell phpMyAdmin to connect to host 127.0.0.1 instead of localhost, which will force the connection to TCP/IP.
