### ISSUE TITLE
Support Docker Image of arm64

### ISSUE THREAD

**Issue by xareelee** [phpmyadmin/phpmyadmin#17460]
### Is your feature request related to a problem? Please describe.

It's a simple request.

For developers using Mac, we need a Docker Image of arm64 (Apple Silicon) which is currently not available on [DockerHub](https://hub.docker.com/_/phpmyadmin?tab=tags).

**Comment by williamdes** [comment]
Hi @tianon
Could you provide some feedback on this as I am not sure what to answer?
This issue should maybe be open somewhere else?

**Comment by ibennetch** [comment]
William maybe you're remembering https://github.com/phpmyadmin/docker/issues/348 ?

This is slightly odd to me because the Docker Hub page lists arm64/v8 support which I thought (perhaps incorrectly) is what Silicon would use. Am I off base here?

<img width="615" alt="image" src="https://user-images.githubusercontent.com/1443710/160242690-3be0a7c9-b68a-4dba-8fca-027af890b757.png">

**Comment by tianon** [comment]
Nope, you're spot on! The M1 should use those arm64 images natively.

**Comment by xareelee** [comment]
I'm new to Docker, and trying to follow some tutorials to deploy and inspect mySQL. I'm using M1 Max (Apple Silicon). 

```shell
$ docker --version
Docker version 20.10.13, build a224086

# pull latest
$ docker pull phpmyadmin/phpmyadmin:latest

# check images
$ docker images
REPOSITORY              TAG       IMAGE ID       CREATED         SIZE
phpmyadmin/phpmyadmin   latest    5682e7556577   6 weeks ago     524MB

# It downloads amd64, not arm64
$ docker image inspect phpmyadmin/phpmyadmin:latest | grep Architecture
        "Architecture": "amd64",
```

When I run `docker stack deploy ...`, it did not start up any phpmyadmin service, and there is no warning message.

**Comment by xareelee** [comment]
OK, I figure out what happened to me.

```
# Change this (from my tutorial)
$ docker pull phpmyadmin/phpmyadmin:latest

# to this
$ docker pull phpmyadmin:latest

$ docker image inspect phpmyadmin:latest| grep Architecture           
        "Architecture": "arm64",
```

It seems there are two separated repositories on DockerHub. Are they both official?

**Comment by williamdes** [comment]
> It seems there are two separated repositories on DockerHub. Are they both official? And there is another popular image named bitnami/phpmyadmin. What differences are between them? Could you put some info about Docker Image on README.md?

Only the images without a namespace (that have a link with `/_/` on Docker hub) are official.

> What differences are between them?

I am not sure but maybe they added some features. Anyway I would recommend you to use only our official image and if you need we could probably add some missing features :)

**Comment by ibennetch** [comment]
We maintain the https://hub.docker.com/r/phpmyadmin/phpmyadmin repository directly, mostly for historical reasons. The one at https://hub.docker.com/_/phpmyadmin is the more official one because it's part of the officially accepted images.

However, it may be time to discontinue the historical one and direct people only to the official repository, although we document the existence of it in the readme at https://hub.docker.com/r/phpmyadmin/phpmyadmin.

I don't have a strong position on this; it's very little work to maintain our own, but at the very least we should figure out why arm64 support doesn't exist there, and doing that might be more work than it's worth. One of the main reasons we've kept it going is to maintain support for those who are using `phpmyadmin/phpmyadmin` instead of `phpmyadmin` as their source, but there's no compelling reason to keep doing so.
