### ISSUE TITLE
Error in processing request. Error code: 404

### ISSUE THREAD

**Issue by jsk000** [phpmyadmin/phpmyadmin#17539]
Hello, 
I'm having trouble to access anything in PhpMyAdmin.
![image](https://user-images.githubusercontent.com/91481610/169534481-422f3386-6246-4188-b759-148533e44e4e.png)
The problem started when I wanted to export my db, but it kept showing me "network Error", so I downloaded the latest version 5.3 of PhpMyAdmin + Snapshot and replaced it with the PhpMyAdmin folder in Xampp. I'm using Xampp v3.3.0 and PHP 8.1.5

Can you please help me get my db back!

Thank you

**Comment by ibennetch** [comment]
Replacing the existing folder inside a packaged kit like XAMPP or WAMP is not a recommended upgrade path because they tend to make changes that affect the whole installation. The first thing I would recommend doing is to put your own phpMyAdmin folder in a different subdirectory of your XAMPP installation with a unique name so it doesn't interfere with the preinstalled one that comes with the XAMPP package. Once you've tried that, you can see if the error continues.

**Comment by williamdes** [comment]
Hi @jsk000 
> the latest version 5.3 of PhpMyAdmin

This is a dev/non released version

Can you install the latest 5.2.x version [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) ?

**Comment by MauricioFauth** [comment]
Duplicate of #17532

**Comment by jsk000** [comment]
> Hi @jsk000
> 
> > the latest version 5.3 of PhpMyAdmin
> 
> This is a dev/non released version
> 
> Can you install the latest 5.2.x version [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) ?

Thank you very much it helped
