### ISSUE TITLE
[donate] My address on the PayPal donation

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#17616]
Hello,

(I tried to send this request to developers@phpmyadmin.net, but I got a bounce back saying that it is just a mailing list --- is there an email I can use for private requests in the future?)

I donated to phpMyAdmin using PayPal, and I pressed the Pay button "too fast", noticing too late that my physical address was included in it.

I'm not sure why do you request the address to be included in the donation, but could you please remove my address from your records? (for privacy / data protection reasons)

(in the email I sent to developers@, I also included the email associated to the donation, but I can't type it here in GitHub, as it's public)

Thank you very much

**Comment by ibennetch** [comment]
Hi,

Thanks for reaching out about this.

> is there an email I can use for private requests in the future?)

donate@phpmyadmin.net is best for these matters. It's true that the developer list would reject your message automatically if you're not subscribed to that list because that, too, is a public list. We also have a team@ mailing list that really does only go to team members, but donate@ is best.

> I'm not sure why do you request the address to be included in the donation, but could you please remove my address from your records? (for privacy / data protection reasons)

I will reach out to Software Freedom Conservancy about this; I believe we don't require it at all and if it was forced on the PayPal screen that's a PayPal requirement, but I will check that with Conservancy as they handle most of the overhead of our administration and accounting.

I'll check with them, in the meantime if you'd prefer to take this conversation private you can email me directly or the donate list.

Thanks for your support,
Isaac and the team

**Comment by ibennetch** [comment]
I don't think I've seen your message to the donate address, have I missed it?

**Comment by nunoperalta** [comment]
Hey! Sorry - I didn't realize you were asking me to send the email to donate@. It says almost the same as what I wrote in this issue originally :)
Just sent it now anyway. Thank you.
