### ISSUE TITLE
How to install a definite version?

### ISSUE THREAD

**Issue by fedushok** [phpmyadmin/phpmyadmin#17622]
Good day!

I have the same problem as described in the [issue](https://github.com/phpmyadmin/phpmyadmin/issues/17523). I need to use php 7.4 for some reasons. In such situation I think it is reasonable to use appropriate version of phpmyadmin.
How should i write install command(s)
`... sudo apt install phpmyadmin`
to install 4.9.10 version of phpmyadmin?

**Comment by williamdes** [comment]
Hi @fedushok 

By design on Debian/Ubuntu there is only one version available by default in the archive (something like that). So you "can not" install a specific version with the apt command line :)
That said using the ZIP from our website you can install the latest 5.1 or 5.2 version and it will work perfectly for your PHP 7.4 web server.

I am sorry for the inconvenience caused by our symfony dependency..

See: Latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)
