### ISSUE TITLE
my website not open

### ISSUE THREAD

**Issue by Bossesoneroom** [phpmyadmin/phpmyadmin#17848]
### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment]
Hi @Bossesoneroom 
Could you detail a bit more what you are reporting ?
The title does not help guess what it is.

**Comment by Bossesoneroom** [comment]
My website is not open please  some body help me to open

**Comment by ibennetch** [comment]
@Bossesoneroom You haven't really provided enough information for us to help. What is the site and what is the problem are two questions that could help — but probably we won't be able to help because we work on the phpMyAdmin application. That's an interface that helps administrators manage a database, but isn't directly responsible for handling your web site.

You should probably seek assistance from your hosting provider or the person who maintains your web site.

**Comment by Bossesoneroom** [comment]
Mahoganyshop.wpcomstaging.com/ 
When i install plogin  starting not open

**Comment by Bossesoneroom** [comment]
What I do
