### ISSUE TITLE
Drop support for MySQL 5.5 and MariaDB 5.5

### ISSUE THREAD

**Issue by MauricioFauth** [phpmyadmin/phpmyadmin#17936]
Support for MySQL 5.5 and MariaDB 5.5 should be dropped on phpMyAdmin 6.0, as both versions are no longer maintained.

- [MySQL 5.5 EOL notice](https://www.mysql.com/support/eol-notice.html):
  > Per Oracle's Lifetime Support policy, as of December 31, 2018, MySQL 5.5 is covered under Oracle Sustaining Support.
- [MariaDB 5.5 EOL notice](https://mariadb.org/about/#unmaintained-releases):
  > As MariaDB 5.5 was included in multiple prominent Linux distributions with a lifespan beyond 2017, the Foundation committed to maintaining it until 2020.

For now, only new features shouldn't support these versions.
Users can use the [`$cfg['MysqlMinVersion']`](https://docs.phpmyadmin.net/en/latest/config.html#cfg_MysqlMinVersion) setting to bypass this limitation.

> **Note**
> MySQL only supports 5.7+ and MariaDB only supports 10.3+.

**Comment by MauricioFauth** [comment]
What do you think about this? @phpmyadmin/developers

**Comment by ibennetch** [comment]
Good point, although it's hard to know what justifies a jump to version 6. It seems possible to me that this could be part of 5.3.

I feel the semver standard is a great guideline, but often fails to account for the nuances of versioning when we don't provide any API and just depend on other software.

As far as dropping those old versions, we should maybe check whether they are in common use on any active popular Linux distributions or packaged kit like WAMP. I doubt it, but we might not want to drop support yet if they're still in common use.

Overall yes, I agree.

**Comment by williamdes** [comment]
I think I see no point dropping versions, people have old servers still running and I know a client that has. It will make people use older phpmyadmin versions and that's really not good for us. I think we should invest some time in making a library or class with all security bug versions of php/mysql/perconadb and MariaDB
And then displaying a big warning box somewhere very obvious
People hate warnings, it should be better to encourage upgrade?

Upgrading versions of db servers is sometimes pointless or already ongoing for some companies.
I currently help a client with 10+ years old debian and db servers with it of course

What do you think?

**Comment by MauricioFauth** [comment]
> Good point, although it's hard to know what justifies a jump to version 6. It seems possible to me that this could be part of 5.3.

The reasoning is that 5.3 is close to release and I want the next version to be 6.0, so I can work on the public directory issue.

- https://github.com/phpmyadmin/phpmyadmin/issues/16229

>  I think we should invest some time in making a library or class with all security bug versions of php/mysql/perconadb and MariaDB
> And then displaying a big warning box somewhere very obvious
> People hate warnings, it should be better to encourage upgrade?

I really like this idea. I think it's a better option than removing support for old versions.
Increasing MySQL/MariaDB versions is different than increasing the PHP version, because it doesn't cost too much to us to maintain an old version. So showing some kind of warning for an unmaintained MySQL/MariaDB version is a good idea.

**Comment by williamdes** [comment]
> The reasoning is that 5.3 is close to release and I want the next version to be 6.0, so I can work on the public directory issue.

I think this can be included into 5.3 and we say to people they need to migrate their server configuration and we provide all possible examples
See #16879

And in 6.0 we drop the old index.php and setup/index.php
What about that?

> I really like this idea. I think it's a better option than removing support for old versions.
Increasing MySQL/MariaDB versions is different than increasing the PHP version, because it doesn't cost too much to us to maintain an old version. So showing some kind of warning for an unmaintained MySQL/MariaDB version is a good idea.

Exactly, it costs nothing to spin an instance with docker or a web server just for phpMyAdmin to continue to work. Companies will do it as the effort is not much.
Let's not ask the impossible to ones having datasets they can not move or migrate.

Also, Amazon has versions of MySQL named Aurora MySQL and we can not really upgrade because there is ko version available. They still ship some minor versions from time to time. But we are stuck on some minors for years.
