### ISSUE TITLE
Allow rollback in compound queries involving SET statement

### ISSUE THREAD

**Issue by AgentFriday** [phpmyadmin/phpmyadmin#17951]
I often save useful queries for future use, and when I do I tend to factor out all the inputs at the top, like so:
```sql
    SET
        @resId = xxx,
        @activeSince = '2021-01-01';
    
    DELETE 
    FROM customer_profiles
    WHERE customer_profile_id IN (
        SELECT customer_profile_id 
        FROM (
            SELECT customer_profile_id, last_check, last_order,
                GREATEST(last_check,last_order) AS last_active_date
            FROM customer_profiles
            LEFT JOIN (
                SELECT restaurant_id, customer_profile_id, MAX(create_time) AS last_check 
                FROM checks 
                GROUP BY customer_profile_id
            ) AS c USING (restaurant_id,customer_profile_id)
            LEFT JOIN (
                SELECT restaurant_id, customer_profile_id, MAX(create_time) AS last_order 
                FROM checks 
                GROUP BY customer_profile_id
            ) AS o USING (restaurant_id,customer_profile_id)
            WHERE restaurant_id = @resId
            GROUP BY customer_profile_id
            HAVING last_active_date IS NULL OR last_active_date < @activeSince
        ) AS inactive
    )
```

The problem is that I often want to do a sanity check before doing something like deletions by using the `ROLLBACK` checkbox.  But in this case, PhpMyAdmin refuses to allow it, complaining that ` Only INSERT, UPDATE, DELETE and REPLACE SQL queries containing transactional engine tables can be rolled back.`

This is rather unfortunate, as I have to undo the factoring and replace the identifiers with literals throughout the query.

Would be nice if such use cases were recognized and the parser was smart enough to recognize that there _really is_ a DELETE statement in there, and no one in their right mind expects the temporary variables to be rolled back and so it doesn't hurt to let that slide...

Heck, I've always found this restriction rather silly anyway, because no one expects that a SELECT statement would be rolled back, and nobody is being harmed by allowing it to run with the box checked...  because when I do change it back to a DELETE or UPDATE statement I might forget to tick the ROLLBACK box again and would rather leave it checked just to be safe.  COULD WE JUST REMOVE THE BLOODY CHECK?  It's really not as helpful as one might imagine, and just a legalistic pain in the arsenal.

**Comment by williamdes** [comment]
Thank you for the report !

**Comment by ansavin** [comment]
Hello, may I try to fix this bug?

**Comment by williamdes** [comment]
> Hello, may I try to fix this bug?

Yes, sure
Let me know if you need some help

**Comment by ansavin** [comment]
Hello, sorry for long answering!
First of all I think that completely removing of check is bad idea - some users may occasionally lost their data, for example, if they will run queries like ALTER TABLE .. DROP COLUMN .. and hope that rollback will return column back (actually it won't).

Also, I have a couple of questions:

1) I tried to prevent executing of SET queries with additional keywords like GLOBAL in order to prevent user from trying to rollback queries like SET GLOBAL max_connections = 1000. Also, current implementation  prevents user from rollbacking queries with SESSION keyword - which may be unnecessary, because, if I'm not mistaken, after query in textblock is executed, the session is over. Should we allow to rollback this kind of queries?
2) I think allowing of SELECT is dangerous - some kind of SELECT queries have a side effects - for example, SELECT .. INTO OUTFILE allows you to write query result to file - and this file won't be deleted after rollback. Of course, we may disallow only SELECT .. INTO, but I'm not sure that there is the only possible kind of SELECT query with side effects - I guess in this case we need somebody with deep knowledge of SQL to help us. So, should we try to find such a man or it is ok to allow only SET queries?
Thanks in advance!

P.S. my WIP PR is here https://github.com/phpmyadmin/phpmyadmin/pull/18349
