### ISSUE TITLE
Fresh install from apt- include path problem?

### ISSUE THREAD

**Issue by terraping** [phpmyadmin/phpmyadmin#18299]
Ubuntu 22.04.2
Apache 2.3.52
PHP  8.1.2

`PHP Warning:  require_once(PhpMyAdmin/MoTranslator/autoload.php): Failed to open stream: No such file or directory in /usr/share/phpmyadmin/autoload.php on line 2
 PHP Fatal error:  Uncaught Error: Failed opening required 'PhpMyAdmin/MoTranslator/autoload.php' (include_path='.') in /usr/share/phpmyadmin/autoload.php:2\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/common.inc.php(95): require_once()\n#1 /usr/share/phpmyadmin/index.php(15): require_once('...')\n#2 {main}\n  thrown in /usr/share/phpmyadmin/autoload.php on line 2`

'php -r "echo get_include_path();"
.:/usr/share/php
'

Seems like I am overlooking something simple but I have checked and rechecked everything I can find in the wiki and previous issues. Any help would be much appreciated!

**Comment by williamdes** [comment]
Hi @terraping 

That's weird bu looks similar to #17957 

How did you install the package ?
Only apt install ? 

You should try to install the version from our PPA, it's more up to date. But the packaging it the same.

Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by terraping** [comment]
Yes from the apt install. I just tried installing manually by unzipping the latest stable release into /var/www/html and it works fine this way. Strange, but I am ok with this solution. Thanks!

**Comment by terraping** [comment]
Well, it looks like doing it this way did not create a database user or the phpmyadmin database, so to save work I ended up deleting that and using this method that somehow I missed before.

'sudo add-apt-repository ppa:phpmyadmin/ppa
sudo apt-get update
sudo apt-get install phpmyadmin'

I prefer this so that it can be automatically updated in the future. This seems to have worked perfectly other than the default user 'phpmyadmin' does not have privileges to create databases, easy enough to fix that.

**Comment by williamdes** [comment]
Thanks for the feedback, I think we can agree it's solved

Also I would want to say that in your backtrace it said `(include_path='.') ` and that's a different value than for the CLI.

And it's probably solved because the package has an `open_basedir` for PHP 8 now
But it's most probably because this fix was not present on the package you used from Ubuntu.
See fix: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/commit/094c74e2d59edd772bd1a07254c4aa7f0e1a80c8

I think it was that 🤔 

https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/blob/debian/4%255.2.1+dfsg-1/debian/conf/apache.conf#L18

**Comment by williamdes** [comment]
Hi @utkarsh2102 
Do you think I could port into Ubuntu 22 this fix: https://salsa.debian.org/phpmyadmin-team/phpmyadmin/-/commit/094c74e2d59edd772bd1a07254c4aa7f0e1a80c8  ?
