### ISSUE TITLE
Symphony bug on Phpmyadmin, returns 500

### ISSUE THREAD

**Issue by DorianCoding** [phpmyadmin/phpmyadmin#18305]
### Describe the bug

Phpmyadmin is returning a 500 error when selecting a database or updating values in a table.

### To Reproduce

1. Go on phpmyadmin, try to select a database or update values in an existing table.
2. 
`[Fri Mar 31 19:17:11.936104 2023] [proxy_fcgi:error] [pid 13387:tid 1842316256] [client 192.168.1.29:29728] AH01071: Got error 'PHP message: PHP Fatal error:  Declaration of Symfony\\Component\\Cache\\CacheItem::get() must be compatible with Psr\\Cache\\CacheItemInterface::get(): mixed in /usr/share/php/Symfony/Component/Cache/CacheItem.php on line 49'
`

### Server configuration

- Operating system: Debian Bullseye
- Web server: Apache/2.4.56 (Raspbian)
- Database version:  10.11.2-MariaDB-1 - Raspbian
- PHP version: 8.2.2
- phpMyAdmin version: 5.2.1deb1

### Client configuration

- Browser: Firefox 
- Operating system: Windows 10

### Additional context

This bug is quite recent, but I don't see which packages was recently updated.

**Comment by williamdes** [comment]
Hi @DorianCoding 

This is most probably because your apt setup did enter a non coherent state. That said I do no maintain https://packages.debian.org/bullseye/php-symfony-cache

Can you try to `apt remove phpmyadmin` and `apt autoremove` to be sure `php-symfony-cache` is no longer installed. Nor `php-psr-cache`.
After re-installing `phpmyadmin` it should be okay

I am not even sure how you managed to install `5.2.1deb1` without enabling backports.
You should have installed https://packages.debian.org/source/bullseye-backports/phpmyadmin

Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by DorianCoding** [comment]
It was indeed a configuration conflict of Symphony, indépendant of phpMyAdmin.

**Comment by DorianCoding** [comment]
Wrong click

**Comment by williamdes** [comment]
> It was indeed a configuration conflict of Symphony, indépendant of phpMyAdmin.

Merci quand même :)
