### ISSUE TITLE
phpmyadmin in Ubuntu 22.04LTS not showing proper format after install

### ISSUE THREAD

**Issue by dreamcarrior** [phpmyadmin/phpmyadmin#18306]
I recently upgraded from Ubuntu 20.04LTS to 22.04LTS. I reinstalled apache2, mariadb, php, and phpmyadmin following the following a few tutorials, which are listed below. I followed the Github Ubuntu PPA installation guide. I also checked the FAQ. But I cannot find a solution to my problem.  By the way, mysql-server always ended up with corrupted package, and I cannot continue. This is the reason I use mariadb.

The problem is that no matter which tutorial I follow, the phpmyadmin always shows like plain format, as if the css is not shown properly. Images attached below. Browsers such as Safari or Google Chrome makes no difference.

phpmyadmin in Ubuntu 20.04LTS was working normally. Anyone has a clue? 

Tutorials.
https://linux.how2shout.com/how-to-install-phpmyadmin-with-apache-on-ubuntu-22-04-lts/
https://tecadmin.net/how-to-install-phpmyadmin-on-ubuntu-22-04/
https://medium.com/@laraveltuts/how-to-install-and-configure-phpmyadmin-in-ubuntu-22-04-3be9097b2a96
https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-phpmyadmin-on-ubuntu-22-04

Images using Google Chrome.
Log-in page
<img width="1413" alt="Screenshot 2023-03-31 at 12 46 49 PM" src="https://user-images.githubusercontent.com/5529264/229202712-2d35aafd-36ab-47db-926c-d660d5f1b8bf.png">
After log-in.
<img width="1413" alt="Screenshot 2023-03-31 at 12 45 07 PM" src="https://user-images.githubusercontent.com/5529264/229202716-e170d109-67ff-4d41-959d-fab142101ced.png">
Safari is the same. After log-in.
<img width="1360" alt="Screenshot 2023-03-31 at 1 19 19 PM" src="https://user-images.githubusercontent.com/5529264/229202708-515194ad-82eb-4537-82ce-4c39b4f3d985.png">

**Comment by williamdes** [comment]
> The problem is that no matter which tutorial I follow, the phpmyadmin always shows like plain format, as if the css is not shown properly. Images attached below. Browsers such as Safari or Google Chrome makes no difference.
> phpmyadmin in Ubuntu 20.04LTS was working normally. Anyone has a clue?

Well, some of those tutorials are not entirely correct or even up to date, knowing there is our PPA for Ubuntu jammy.
You should try installing phpMyAdmin from APT PPA: https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#ubuntu-ppa
Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

It should work out correctly for the installation part.
That said, this white screen already happened quite some time and most of the time it's because the mime type for css files is not sent correctly by the web server. Check your developer console, it may indicate what's wrong here

**Comment by dreamcarrior** [comment]
@williamdes  Thank you very much! I followed your instructions and reinstalled the phpmyadmin package using PPA. I also went back to check the old 20.04LTS phpmyadmin installation instruction. I deleted "SetHandler application/x-httpd-php" from /etc/apache2/apache2.conf (which was carried over from upgrade) and restarted the apache2 service, then phpmyadmin works perfectly.

If I had a fresh install, it should have worked out of box. However, I liked the upgrade so that I don't have to re-do the reconfiguration for other setup. 

Thank you for your assistance!

**Comment by williamdes** [comment]
Wow, indeed I better understand the bug now
I have been trying chat gpt 4 since some hours and here it what it says

> @williamdes -> Why should apache2 not have "SetHandler application/x-httpd-php" in it's configuration ?

----

The "SetHandler application/x-httpd-php" directive is used to set the handler for PHP scripts in the Apache HTTP Server (apache2) configuration. However, it is generally not recommended to use this directive with the "application/x-httpd-php" MIME type for several reasons:

- Security concerns: Using "SetHandler" to specify the handler for PHP scripts can lead to security vulnerabilities if the server is misconfigured or if malicious code is injected into the server. This can allow an attacker to execute arbitrary code on the server, potentially leading to data theft or other malicious activities.

- Compatibility issues: Some web servers and browsers may not support the "SetHandler" directive or may interpret it differently, leading to compatibility issues with certain web applications or platforms.

- Best practices: It is generally recommended to use the "AddType" directive instead of "SetHandler" to specify MIME types in Apache configurations. This is because "AddType" is more flexible and allows for better compatibility with different web servers and applications.

Therefore, it is generally not recommended to use "SetHandler application/x-httpd-php" in the Apache configuration for PHP scripts, and "AddType application/x-httpd-php .php" should be used instead to properly set the MIME type.

**Comment by williamdes** [comment]
That's just, wow, nothing more to say. Here it all is

Happy this is solved 🎉 , I will make a wiki section about it on the packaging wiki

**Comment by williamdes** [comment]
The other similar request was: https://github.com/phpmyadmin/phpmyadmin/issues/17999#issuecomment-1367877722

Time to document this in an FAQ entry !
