### ISSUE TITLE
Parser error shown with multiple statements in query box

### ISSUE THREAD

**Issue by M393** [phpmyadmin/phpmyadmin#18511]
### Describe the bug

An error is shown when multiple SQL statements are entered in the query box.

### To Reproduce

1. Go to the query box 
2. Input 
```sql
SELECT 1; SELECT 1; 
```
3. See error

### Expected behavior

No error shown.

### Screenshots
![image](https://github.com/phpmyadmin/phpmyadmin/assets/56256405/349d19b5-1a89-4e2d-a1ed-c39d38188d35)

### Server configuration

- phpMyAdmin version: 5.2 and 6.0

**Comment by williamdes** [comment]
Thanks, I can confirm this on the current 5.2-dev version

**Comment by williamdes** [comment]
> Can I work on this issue?

For sure, please use QA_5_2 as a base branch for yours. And feel free to ask stupid questions, this can be a complicated subject involving changes on the sql-parser repository

**Comment by MoonE** [comment]
The problem is here in line 59:
https://github.com/phpmyadmin/phpmyadmin/blob/99881debb52ed89b907583a2b32d999290a14ce2/libraries/classes/Controllers/LintController.php#L47-L59

Always setting the delimiter here doesn't seem right. I guess this should only be done if editing routines/triggers/events.

**Comment by williamdes** [comment]
Again that delimiter 🙄
This last line seems like my fix..
Could you try to fix it?
