### ISSUE TITLE
Editing procedure with BOOL param changes type to INT

### ISSUE THREAD

**Issue by M393** [phpmyadmin/phpmyadmin#18613]
### Describe the bug

BOOL type is converted to INT when editing a procedure.
It works with BOOLEAN type.

### To Reproduce

1. Create procedure 
```sql
CREATE PROCEDURE `p` (IN b BOOL) BEGIN END;
``` 
2. Edit procedure
3. See type of `b` changed to INT

### Expected behavior

The BOOL data type should be preserved

### Screenshots

![image](https://github.com/phpmyadmin/phpmyadmin/assets/56256405/9db559cb-48de-47b9-b28d-c610941153c3)

### Server configuration

phpMyAdmin version: 5.2 & 6.0

**Comment by kamil-tekiela** [comment]
This is an interesting problem. `BOOL`, just like `BOOLEAN` OR `INT1` are aliases of `TINYTINT`. MySQL doesn't have boolean types. PMA doesn't support aliases. This makes sense, because why would anyone need to see it on UI. However, as you observed above, MySQL keeps the alias in the procedure definition. When you execute `SHOW CREATE PROCEDURE p` you can see that it still reports type as `BOOL`. When we parse this SQL in PMA, we can't find a corresponding element in the select list. We can't find it in the list because PMA doesn't support aliases. 

I propose that we introduce type mapping in PMA and use it for routine edit form to avoid this bug. I will create a PR soon. 

IMPORTANT: Even though PMA doesn't support aliases, `BOOLEAN` is the only available alias in PMA. We should probably keep it consistent and remove it from PMA. @williamdes What do you think?
