### ISSUE TITLE
SHOW PROCESSLIST deprecated

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#18886]
https://github.com/phpmyadmin/phpmyadmin/blob/43e0ede84c0328007350290df8b8e6a26e228724/src/Server/Status/Monitor.php#L210

Just a heads-up that `SHOW PROCESSLIST` is now deprecated in MySQL:

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-35.html

`performance_schema.processlist` should be used instead.

**Comment by kamil-tekiela** [comment]
According to the docs you linked, it is not deprecated. The underlying implementation is deprecated though. Therefore, I don't think we need to change anything in PMA.

**Comment by nunoperalta** [comment]
Ha !!! You're right.

I was tricked by the description they give in the Percona change log:
https://docs.percona.com/percona-server/8.0/release-notes/8.0.35-27.html#deprecations

> **Deprecations**
> The following items are deprecated in this release and using any of these items may cause a warning:
> - INFORMATION_SCHEMA.PROCESSLIST and the SHOW PROCESSLIST command

Not sure why they would say that `SHOW PROCESSLIST` is deprecated... maybe a misinterpretation.

Reading the MySQL's change log I linked above, it really doesn't seem to be the case.

Thank you.

**Comment by nunoperalta** [comment]
Sorry, the change log says:

> INFORMATION_SCHEMA.PROCESSLIST is deprecated and subject to removal in a future MySQL release. As such, the implementation of **SHOW PROCESSLIST which uses that table is also deprecated**.

**Comment by kamil-tekiela** [comment]
I tested it locally and it is exactly what it says. The old implementation is deprecated. The new one is ok.

**Comment by nunoperalta** [comment]
Ah, very good. Thank you very much for demystifying this! 😊

**Comment by M393** [comment]
[This line](https://github.com/phpmyadmin/phpmyadmin/blob/f73ec94bb64029e7b66d8d0f74eb68e32b783b25/src/Server/Status/Processes.php#L40) is using `information_schema.PROCESSLIST` and could be changed to use `performance_schema.processlist`.

Performance schema is available since [MySQL 5.5.3](https://github.com/mysql/mysql-server/commit/67a48e1a4cfd73875e54f9416afa7328d676d7bd). Though the processlist implementation is only available when [`performance_schema`](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-system-variables.html#sysvar_performance_schema)=`on` and the deprecated [`performance_schema_show_processlist`](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-system-variables.html#sysvar_performance_schema_show_processlist)=`on`, whereas `information_schema.PROCESSLIST` should be always available.
