### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by gtbu** [phpmyadmin/phpmyadmin#18930]
I imported a huge mediawiki-file in phpmyadmin 5.21 (php 8.2, Xampp) and got
Warning in .\libraries\classes\Plugins\Import\ImportMediawiki.php#300  Array to string conversion

    Backtrace
    ImportMediawiki.php#234: PhpMyAdmin\Plugins\Import\ImportMediawiki->importDataOneTable(
    array,
    array,
    )
    ImportController.php#585: PhpMyAdmin\Plugins\Import\ImportMediawiki->doImport(
    ,
    array,
    )
    Routing.php#191: PhpMyAdmin\Controllers\Import\ImportController->__invoke(
    ,
    array,
    )
    index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
    ,
    string '/import',
    ,
    ,
    )
------------------------------------------------------------------------------------------
    Warning in .\libraries\classes\Plugins\Import\ImportMediawiki.php#300 
	Array to string conversion   --->:      ($this->setTableHeaders($table[1], $table[2][0]);)

    The   Problem is $table[2][0]   ---> undefined array key 0
--------------------------------------------------------------------------------------------------

**Comment by SachinBahukhandi** [comment]
Can you send some dummy file or the actual file for us to replicate?
Thanks.

**Comment by gtbu** [comment]
That is not possible : 940MB, but my above issue was a bit unprecise 

1. At first comes the error :   TypeError: PhpMyAdmin\Plugins\Import\ImportMediawiki::setTableHeaders(): Argument #2 ($table_row) must be of type array, null given, 
 called in F:\Xampp\xampp\phpMyAdmin\libraries\classes\Plugins\Import\ImportMediawiki.php on line 306
 
2. If i add  array ---> :  $this->setTableHeaders(array($table[1], $table[2][0])); then comes
Warning in .\libraries\classes\Plugins\Import\ImportMediawiki.php#306
 Undefined array key 0

Backtrace

ImportMediawiki.php#234: PhpMyAdmin\Plugins\Import\ImportMediawiki->importDataOneTable(
array,
array,
)
ImportController.php#585: PhpMyAdmin\Plugins\Import\ImportMediawiki->doImport(
,
array,
)
Routing.php#191: PhpMyAdmin\Controllers\Import\ImportController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/import',
,
,
)-
------------------------------------

**Comment by kamil-tekiela** [comment]
Without seeing the file that was used it's going to be difficult to analyse this problem. My guess is most likely that either the file is corrupted or that it has a header line but no body. It could also have something to do with interrupted upload due to reaching script execution time. If it's not possible to reduce the file to MCVE, maybe you could set a breakpoint on the error and tell us what are the contents of the variables being processed. Anything that could help us reproduce this issue or narrow it down would be really good.

**Comment by kamil-tekiela** [comment]
Thanks for the information. I think I got a little confused with the report initially, but now I understand the problem. This happens when the table being imported has no data. 

The mediawiki import seems to have been broken for many years. I must admit that it's a little bit of a weird file format. But I think this is fixable. I will check if I can come up with some easy bug fix to at least make this import work again. 

On unrelated note, the import/export feature in PMA is in the worst state of all the code. If anyone wants to rewrite this functionality, I think it would be a good idea. Refactoring and fixing this code is a nightmare.
