### ISSUE TITLE
Enhance security by adding support for 2-factor-authentication via Google Authenticator

### ISSUE THREAD

**Issue by pma-import** [phpmyadmin/phpmyadmin#6197]
My hoster recently added support for securing the hosting admin panel with 2-Factor-Authentification, using Google Authenticator. The only "weak" link left is the phpmyadmin access which does not support that.

It would be great if users would have the option within PMA settings to enable 2-Factor-Authentication to further secure their databases and prevent brute-force-attacks if the login site is publicly available.

More infos on Google Authenticator can be found here: http://code.google.com/p/google-authenticator/

---
- **Original URL**: https://sourceforge.net/p/phpmyadmin/feature-requests/1499/
- **Original author**: robertharm

**Comment by fedeisas** [comment]
:+1:

**Comment by Napoleon-BlownApart** [comment]
An excellent proposal!  PMA is the weak link in my server's security atm and I'm eager to see this implemented.  How is it coming along?
My server is based on Ubuntu 14.04, will I need to use a PPA or will this make it into Ubuntu's standard package database?  (I know you can't speak for Canonical, but this is really an important development.)

Cheers,
Nap

**Comment by emanuelb** [comment]
Another option is to support 2FA from MYSQL databases, more information (via PAM):
https://mariadb.org/improve-security-with-two-step-verification/
https://www.percona.com/blog/2013/02/24/using-two-factor-authentication-with-percona-server/

**Comment by nijel** [comment]
Unfortunately the PHP API doesn't support pluggable authentication (yet). It depends on client side plugin to ask additional credential, see https://mariadb.com/kb/en/mariadb/development-pluggable-authentication/#dialog-client-plugin.

PS: Anyway I don't think 2FA on MySQL server side is usable for usual MySQL hosting setup where most of the connections are done from programs than from users.

**Comment by Napoleon-BlownApart** [comment]
I don't agree. phpMyAdmin is an interface to access MySQL, so implementing 2FA in MySQL is a completely separate matter.  In so far as phpMyAdmin is concerned; Joomla is able to provide 2FA, so it should be possible to do likewise for phpMyAdmin (say taking the Joomla code and tweaking it).

**Comment by nijel** [comment]
I'm not against implementing 2FA (or U2F) in phpMyAdmin, I've just commented on @emanuelb suggestion to use 2FA from MySQL that it's currently not possible from PHP.

Still this will be a bit tricky as we start with MySQL credentials only and user would be forced to setup 2FA on first login. This would still leave window for attack for users who have never logged in.

**Comment by Napoleon-BlownApart** [comment]
@nijel, understand.  I read my comment after I submitted and realised that I misunderstood what you had said.  
I've put some thoughts below on how it could be managed in phpMyAdmin, particularly in light of (at least some) 3rd party tools that allow management of database users.
In some ways it's actually a good thing that this is being arranged outside of MySQL, because it would not break tools such as MySQL Workbench, and existing PHP applicaitons.
Also, not every user wants this feature.  For example, I don't want 2FA hassels on my localhost WAMP server that I use for development.  But I **do** want/need 2FA on my production server.

phpMyAdmin, under user management, should allow 2FA 
1) to be enabled/disabled,  (depending on the setting of the *2FA Usage* parameter described below)
2) credentials to be managed managed (if enabled).
This could be done per account using MySQL's permission system.

phpMyAdmin could provide an API for configuring 2FA which would allow externally created accounts, such as through cPanel, ISPConfig, etc. to setup credentials in addition to other account attributes.
Then, back in phpMyAdmin, the administrator could configure 2FA usage with the following two global switches; 
2FA Usage:
1) 2FA required for all accounts,
2) 2FA configured per account
3) Don't use 2FA

and, if *2FA Usage* is enabled:
2FA Credential configuration:
1) Only preconfigured 2FA,
2) Allow creation of 2FA credentials on 1st login

**Comment by pwallner** [comment]
Would love to have two-factor login (eighter google aut. or U2F)...

**Comment by modivivek** [comment]
will the user be able to use 2-factor authentication if he in not connected to the internet?

**Comment by nijel** [comment]
There is no need for internet connection with 2FA/U2F.

**Comment by pwallner** [comment]
Yes

Regards,
Patrick

**Comment by modivivek** [comment]
i have a few questions and would be glad if someone could answer them..
Are there any other authenticator except google authenticator? 
Is this authenticator a plugin or i will have to write its code from scratch?
And can someone please explain to me in little detail how this authenticator works so that i can frame my gsoc proposal for this feature accordingly?

**Comment by Achilles-96** [comment]
* Yes, there are other apps also (Google Authenticator is only one of them).
* There are existing libraries (for example - https://github.com/RobThree/TwoFactorAuth) which we can use. 
* You may find this helpful - https://security.stackexchange.com/questions/47901/how-does-authys-2fa-work-if-it-doesnt-connect-to-the-server

**Comment by ibennetch** [comment]
This is an interesting project that I do support, but I have some question about how we should also support the MariaDB pluggable authentication mentioned by Emanuel. I think we should, but also think that adding that support is outside the scope of this request and should be a new and separate issue.

**Comment by modivivek** [comment]
how will this work on windows phone(which i personally use..:P) and java phone which does not support google authenticator?

**Comment by nijel** [comment]
@ibennetch  Adding support for MariaDB pluggable authentication is IMHO unrelated to this.

@modivivek Find any application supporting [TOTP](https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm). A first query in Google showed me [
Authenticator+](https://www.microsoft.com/cs-cz/store/p/authenticator/9nblggh08h54), but there will be certainly more apps (at least I assume, there are at least 10 applications implementing this on Android).

**Comment by Achilles-96** [comment]
Hello. I am working on this as part of GSoC. I am stuck on storing the secrets. Where should we store the shared secrets generated?

**Comment by nijel** [comment]
Probably creating new table in the configuration storage...

**Comment by Achilles-96** [comment]
Do you mean the `phpmyadmin` database.

**Comment by nijel** [comment]
Yes, https://docs.phpmyadmin.net/en/latest/setup.html#phpmyadmin-configuration-storage

**Comment by nijel** [comment]
I've given this another try, you can find implementation of both U2F and 2FA in https://github.com/phpmyadmin/phpmyadmin/pull/13787, feedback welcome.

**Comment by nijel** [comment]
Implemented by https://github.com/phpmyadmin/phpmyadmin/pull/13787.
